apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: aria2
  namespace: aria
spec:
  interval: 15m
  chart:
    spec:
      chart: aria2
      version: 14.5.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  values:
    TZ: Europe/Berlin
    ingress:
      main:
        enabled: true
        hosts:
          - host: aria2.base.noitl.space
            paths:
              - path: /
                pathType: Prefix
        integrations:
          certManager:
            enabled: true
            certificateIssuer: ${CERTMANAGER_ISSUER}
          traefik:
            enabled: true
            middlewares:
              - name: local
                namespace: traefik
          homepage:
            enabled: false
    workload:
      main:
        env:
          RPC_SECRET: ${ARIA_RPC_SECRET}
    persistence:
      backup-google-max:
        autoPermissions:
          enabled: false
        enabled: true
        mountPath: /mnt/backup-google-max
        path: /mnt/pool1/backup/backup-google-max
        readOnly: false
        server: ${NFS_HOST}
        type: nfs
    resources: { }
    securityContext:
      container:
        UMASK: "0022"
        readOnlyRootFilesystem: false
        runAsGroup: 0
        runAsNonRoot: false
        runAsUser: 0
