apiVersion: v1
kind: Secret
metadata:
    name: datadog-secret
    namespace: datadog-operator
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:a0U/2Qo/Ce0hYRjRdYmoDxuoez163pfouREukq+0YJc=,iv:gP+iwgtNEXI/qOpteJbM+zgcIp95iLoapIl7EQkZ3D4=,tag:mb4otrc6VUmBRN4xaW0oZg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTbW1UQVVrT1pjc3U5Vy9B
            dWNqc1VXN0RIdFR4cnBXbEh4ZlhZNVJFU1RRCkhlQktDNHNJZWgyem8yYzJhS09K
            N01rVmwwWUxzV1Fpejh3Vm16aVdBNncKLS0tIGhxSDU3VEx0WFpGd3NjTGQvRzRU
            R3FTQjRLVDFLbU5zUUova1pUTzVLSDgKunmM27dfK6aUeh+ebesDp+eK4dsdYNvt
            hMXEujsJZtZIh8WZE+B/kN0K+DnWD1G380yWgD+hJLe60HqrexuE5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-08T15:08:25Z"
    mac: ENC[AES256_GCM,data:Myf17bNF7SqaDkpHulArGfrKFZ42hfdW9You4SowGQVatGoAfndumEzX5o5stE+7WqfwS2eyQZNDaWf7K4qVABd9BOSGSfNRfqxRiF/xNbdgdjYV2G3hSea4YhZSgJtUQ3oh4fWynVpMFaWqR8T0NHUCj421JilaozzqVNKLHgE=,iv:wAkMgSeSdJXsG9PAKAnHVAqSR+cfATUlLl9UNA7wczk=,tag:f7eOPSXPJsuzLZzoD4Ed2Q==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
