apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: datadog-operator
  namespace: datadog-operator
spec:
  interval: 5m
  chart:
    spec:
      chart: datadog-operator
      version: 1.9.0
      sourceRef:
        kind: HelmRepository
        name: datadog
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values: {}
