apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: truenas
  namespace: truenas
spec:
  interval: 15m
  chart:
    spec:
      chart: external-service
      version: 16.11.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  releaseName: truenas
  values:
    service:
      main:
        externalIP: "192.168.188.58"
        ports:
          main:
            port: 81
            protocol: http
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: truenas.${BASE_DOMAIN}
        integrations:
          certManager:
            enabled: true
            certificateIssuer: ${CERTMANAGER_ISSUER}
          homepage:
            enabled: true
            group: System
            name: TrueNAS
            icon: truenas-scale
            description: Betriebssystem der Noitl.Base
            widget:
              enabled: false
