apiVersion: v1
kind: Secret
metadata:
    name: datadog-secret
    namespace: datadog
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:Q/g3uBqXGetXABlc0N4Vv+DbXzVMB8xGdUUpNUXWz4yw5Jzy5SNRxaeAULU=,iv:9O0C9fOBkmxe5qiGnxGWlxD1NqkuVz5/F5GHjInq8y8=,tag:FWhk/ZieOfAQesPqUcTLqg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBScGx1VE85K2FHZ3lJN2Vz
            MEhoeDdzaTZ3ckVDcjF1K2I2NEd1c2xUc3dRCi9nbVYzUTdKR3N0S0Y3RFBiNFRk
            MGcwT3ZVRXNYczRNUEkyRWwvc1lzSlUKLS0tIHRoUlJmenJnaUNEUkRhQkM4bmwx
            c3B2UzBaSTNXV09oS3NncXQwdjhpODAK1sl1cM9zbGlfPYZ0++r4oVEF9qv52YBd
            c1kk/0cJyhxzjS8pNPx3inU7PPTHZnlt544StGw0pOGDXFoH1CvVLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-24T12:44:11Z"
    mac: ENC[AES256_GCM,data:OQVFXvDTnqxLufFVJBhyldRHpxuvAPi3TE86/dM7VJTUgeXqvMUIeIcRetGbOAZOpFiRzIv++rs663dTbgA0GRhcf5x2tCVVbPzfMHvnSmZFnMvLtWTQd9C/ZBUtKnW4DUwn8yjRKskyJwwrdZt0RjTayF/K5aFgZeT074cL3pE=,iv:sVTUg9oxId+dIuwRkhNWSY9SgXcY01FnxlUhiDO47zU=,tag:HSeX0xbeKeH72rR/Q81Z+g==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
