apiVersion: v1
kind: Secret
metadata:
    name: datadog-secret
    namespace: datadog
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:fxv+usjwHGBBxLdmcfb0YKhxVB4V3v8qEyDaFMYLcaYFmlPlX1jH0+/CvC0=,iv:1FMy5Wwx/kkZzTsQCkT5jpSPSR2W6vBFxJR7xSMQSQQ=,tag:FLj+m5aLZpw9zemSYwVq5A==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxMWxXUm9uS05xWHZBYzNv
            emh2Z0VNYmpROTZhd1YrcUZwY3Q3YS8wVG1vCjUyNUFzclI2V1BVb0t1dG8ydEZL
            TFpLMXh1Q1NDbC9YcDZYQkJJMG5GSVkKLS0tIEhUUWlYTkxNR3JDa3ZBbFJ1ank2
            ci9rbVQvdlRVUUxkYi9DNDNaMjVZaG8Kl7EX31ZGK1whtpL6RANlZ70UZVHVFeT2
            g0CvflUc8dQsAn+NWVtRy+3o2aro55fK/G7cNtHWOSbCwFN0/iSYIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-12T20:46:00Z"
    mac: ENC[AES256_GCM,data:BuGe99TVwTrUnzw9sqyYOhOgE+XjsEIq70JCOo5sPKYHQnQEWDcRgMSe85lg0mnQ8vpszCP1uuSL0AIsEN9xRoJz3cpdF8yjIsiw3xPjSahBK/K3kohQs/brmAOjjyLOihE5pqVTkX7C69gSjQNuqfXD3qI8aI1KsqWIIoetNxc=,iv:GYytlYRzIyacWmSHdE8/bwBb/IDQOahYmBHsfhD8aw0=,tag:vtUFJE7/w7ITbc5vrLUDBg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
