apiVersion: v1
kind: Secret
metadata:
    name: datadog-secret
    namespace: datadog
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:z3YADNI8Gev7HG82AWwZ3fTBa0je5Xf2VSnM0kdsYnEbVPWVctNheYIlTy0=,iv:tlE2feU9tcAh7aYWf8dXrrMfCiZtWdjp3HnnCKCDcAU=,tag:7B6mwx+LkRy/kEH4dVH6qw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFdVAydlhyNUd4Y2R4a1ZI
            Q1d1bWUwWVRJaklmQ3BGMXExRXNtZVdOamlJCnFIZjhkVWtuYmw2ZUVrT282c3VQ
            dmlpRTZaK3dTd1Jha25WRmY1Zi80TmcKLS0tIFNFY3IxNzh4cFZWYlliektFcU1p
            ZnV3SStVMDU2dWZoUU96ekk2MEFISWsKLdeHZqrf/krqllYG/QNFtbJJklT9X4Ie
            d+mlG7yuST/jh4dsFcozx8BfxtvgSzko0kS6wH6V84/ByZ7kELS9xg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-06T12:42:27Z"
    mac: ENC[AES256_GCM,data:d6P2aD/Lwa2vs22PsvTFCHUQBDmcI+/dbCG2N95v6joCE8cYD4MhqSLlWWdSgKLhory90sbGRM8Z3ASKij5qVHnB5KfrlxvdchlU1LoA7z2YgezCONBBfIl9rq+3HQMWnWiFPMY1HMtGhmi4qHU+PtLiLO0ArKb81IoAE/7CzC4=,iv:KnfJ7SFTBpxKec1p9diVcXY9csyuy97SDyIoU61kdaM=,tag:Q0X+1ThbPeaF2UOoaYhiPg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
