apiVersion: v1
kind: Secret
metadata:
    name: datadog-secret
    namespace: datadog
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:LD6Hx2TWUfCa1T9pbtbvOxB3SHQUSR5aCuqgZETrS41gadhzQw8Id56kNR4=,iv:3wmMy330y09NMgioRVE8Qvu6rFXTsH84ulJyBwsEh+Y=,tag:LhsAXnN0fUWFtcmLMoX3Og==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaaUxOZFBKcE0wNmtEaFFF
            QnJtQ0pRUjc2OE4vRVJub1dEcFlsaFFPYlZnClVOYkhMQ29QT1k4WnJEN1B5YkUy
            czRnUFBrRGptbkltMnZMMUNXTXpwNTgKLS0tIEtKcmRoT2YxbFBabDE3RVFQMTFG
            ZEpSMSs0ZjBUT2pGRjMrWDV5WkpvUUkKt431xfv39AlEvOSp0zEW0Q68iYH7uRZ3
            uxFp5YyCQx//mVBssTObHiAPbBzuw8E+Y/j6y8Fqne08zuJoC+IBiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-06T12:43:24Z"
    mac: ENC[AES256_GCM,data:eWmhquis8bTvtbbYtXE7AVkgFb8dG+AEKnsqgdDxHTu82yL/eV9g7+J4G+a2JO5truSYqwWbDpBlxVOJMMZJO/JHQZsUjmozgJJrplZFqbQaVVWHh2kqeF5qOTSISla6xYUZdlvHZNGPXLVVBVBmcOyPV9SIigrfxJ27Qiz8jo8=,iv:REZjQc18BpqWAlcOOL9m01UEjLzaLN6UyMu/D5Avyi4=,tag:4mHZhzzGwicc6gGXpqyjyQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
