apiVersion: v1
kind: Secret
metadata:
    name: datadog-secret
    namespace: datadog
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:0/ggbFb2grBW2RrU7NMCYYdHOWiYlDfInzF+TOd1HDrKtuJwjrYhSPR3cxA=,iv:kdaiGEURSSNbPUmMIrbri2C7ducmVFy28CbweK3MCnk=,tag:KoSgMoYPfBQLYLHYUMxujw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWcWtKZEszUXdWQUppdU9N
            SU1yK2k1MndTVkR6MGFEekxGcGZINW11WFRjCmFLR1ZCNWFBZlB4Z0FVZThhbHBl
            SzBQSkE2WWFvYS9tUS9ZTTY2SFhNMmMKLS0tIHR5VmVJeWUxdXQ5WFMwdTdpdGpC
            bzQvOFl5emozMmJKU2pDYWo1cUlIb1kK2XNqOMTmd2emSHlMGyt+CQe/kwAcAPpJ
            z3hlO6NTdszEuA7nlE5PLU0xSKdt6CCmOkYaA1U9ua9c1mk+YM61+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-05T16:24:58Z"
    mac: ENC[AES256_GCM,data:g7Qy9KopeD8efY2oFMTT1RrnQDR575KVcNAgqGkKp39YsLvLavxDU2Wx34Cogn4vkCc00Rnfy3m8MFisyeOyyRsM133szt7vR8Zr9QIVUtYuFH77q6otpfXWFTSkCQGt85ZY9fK8F85u9pUZu2jzSf3xENl5KDCysA+M6osMQ8c=,iv:BgcRHKdR+QXAIQ21mz2rPvP1tHNjTTMu425rn3WEOWE=,tag:wrf7UQHFtPSbDPFd9vGULA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
