apiVersion: v1
kind: Secret
metadata:
    name: datadog-secret
    namespace: datadog
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:35JW5OHr0rZ1uizIiy0+k5R90YC0XsRDjAaMWG0yFbGhXI1Cs3BIItHp1bU=,iv:N63dj4BTzn9eE+8ifF9eD1c76A/uDhepHWkog66tg6U=,tag:YZ9+IpgbJJKc5lWoTX6HLQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUQlk4d1lHRjZFMU92a2Uw
            dGd2NnMvWjlnSnFlMk1vNE0rU0ROcllpaUZBCkFhNlRzbWJoVTBoMGFTV3RWZ25t
            Ly9QWURtT0RwWEVJZjVFUDVxdG5WS2MKLS0tIGt4V2VtMnBWd1JxakNaN2w3OXFN
            a1V6cHNMTFY0aHVJeXZtNjl0MzNDa2MKLWkGbKTcDFChjWBzcqBng8T7EkyGdFqX
            eYLjVuASfRqHAYtLcFlIo8y9DYid0diIE7j9k5+ur3QTp7Y7H+a8+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-10T23:01:35Z"
    mac: ENC[AES256_GCM,data:QR9chyb32ymBQ/10W42zBarcjtHhVDvK2p3mUSwrjh+9hbPAd5LULZmMn4VgPZbgieWeToXRVGm4FrtOlQsdmd6hS5OcqCb7rdA62KL31nPrg6QRiihtZOAvwNzvRvxqB1AGnzF7FhOidQynq+Vd3zz0keaNBBV862po01czOTk=,iv:zbbI2og0IZXucBzEa24J1WKN9oa5SdBwBx0kr8zCNo8=,tag:VLnP2zwS1tjfUYICu6YHDw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
