apiVersion: v1
kind: Secret
metadata:
    name: datadog-secret
    namespace: datadog
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:Np8d9W9Dmf6NufM/m0Q+DP9sc5Hm4/IcqwVzeZU3ykXvMLWJDs7bc84rjLY=,iv:5D2VXVbqbnNYLyqZzGDumvERGYIb5ic9AG0QUzIsXDQ=,tag:3Myths2ITny+zmxfnyDt5A==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBdE40dUFMTE5MaHpvckFJ
            OTVzeG5MWWxweXN5UjdxRXdGTERQOU9PdlNJCitYT0ZsbUtwWXJqeFlKQmdUeXNq
            cHNaZXdkVklhN1NLa0lPeHpNUGhiQ1kKLS0tIHBQdXc2OEI4a2d6S1BCdHpJRE5M
            Q1Y2TjRMdXl1VnU4ejErakRYeFBzS00Knko2vXloNBl69GqURL1SDEfcmLY56Zv7
            cVGZUPcajVz5+OZ8YQ3c/1Z0rHHpI9ism3KLt8cedgeQx5hvThixCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-01T12:49:53Z"
    mac: ENC[AES256_GCM,data:Z8GsFNN+BS+d06oxFTewkvrec1Z3AAKO7zFjhXa/UFiBO4G1RX5iPAu7eXN8+alqIiBBElEK/qtSmMwz4pbARLOv6PPZOzO80WT+hNLfDg2Fj+T5Ld9Vo2ZV3Xr91q5RQ+XyWb5jdOax03ayd6bN2ZelIyanEgcJNvWe1ewjars=,iv:JrQIrx85E09KAJGSQteEqHjO5hcliZ20c6u8Jzx833g=,tag:i0ckHWUZHNhia2QAwPPqeA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
