apiVersion: v1
kind: Secret
metadata:
    name: datadog-secret
    namespace: datadog
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:5RZwqB6Wr/oyb8KlMkWJCuV0S2IL6A7yhvWhNwXFBcLSl1vSgpXCHdOYM9w=,iv:WAqyxhKeliOc4bfdBXQjT0vUTuV4N2IQUcJUKVcEkWs=,tag:tiMh7SilOC5aDDTy3CFqtQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrRlZ3TlRpSk1kNUlIMkxE
            eWFWMjN5eno2U2VLS3p1STFjVkJtVHUvcWk0CmVzN0FZeExZVTR5RHpQWi9iUEVL
            Yms2bVUwL2dtUzU2cFB1YTh3dDhzUGMKLS0tIDVWL0p2dUtsYi9KcTNCZGxoQTZU
            d0daSHk2cXJzWnd2SjdHU1BRcnFLNTAKtNCgF73kSs30SidWbbobNIR58OTyXQK6
            iIxdqM/qI5sJKzTQkcBb6hhEl0I30Mpxl8RCnRnUjXTasmzOgAmSQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-14T10:54:46Z"
    mac: ENC[AES256_GCM,data:nP6PU418rxqb1zyPzzHu+JIHkmE/GSjxBlgiHhLK9eBMjVVEJuBi/QOwgW325+CA+fGyU9bJvA34oGFZiUEgLOGZ2mLM7NS1ZiMPdbMcrbl7Eh36N9LOirzM0Iby5DJ0MW6moyDCyYXpyUVBRJWh/eNRi1RgZJWf2KeWaezxykU=,iv:+zkEP5eDfzd2qh3UwzaxIrU0h5ZrknrcGJXrAYIFat8=,tag:EBuc4z1IhUzscMeAnNKJ5w==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
