apiVersion: v1
kind: Secret
metadata:
    name: datadog-secret
    namespace: datadog
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:YKNvynRQrgqeqrao4Ec6qF7oAErFycaVXfhstp6ub4FUjlgiIEokUqhVbaw=,iv:FyOCbvMPCQ5r7Ak2ykTgZo9p6i2HK7j0feaX3t/GI1o=,tag:h+pL0776fE4vFuup905AiA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFdHcrQkd5TGtLMXlyNTFP
            eWZBYnM0S2tpL0dDMk5zRkRoUWJsVkRsZmxZCm9VQ2NGanlMWERDR25CbGhIVjZk
            NlV6MFNGVElzejBLL01XY3VUbE5XSUUKLS0tIGxtamEzODVGSU1IMXBDZ2FFcFFC
            QkNzOHFyWDk3d0FvZlhYOElkdE9DN3cKhPVeR31X+du3ReA0W7xb0ghkaNQHmizf
            mwwMN5ozlParQt7XaAkRuZ4tcQY2l4bEh6XU6EhUyyikeddJ54F1YQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-28T16:14:52Z"
    mac: ENC[AES256_GCM,data:h+6S4buF0YIq5+6gYjxW+Bb4zryLRkWg3Hgmy8MakwPagiU+6VBwx677bf+5pwzT8pbuG4j+e9fx9RymrcYsdg0kHkro87w5/8L30uL36pfhxqomhnB6W/puFZH2v7iYIWUXCzb2n3hjW+FI9YUl7NnIdnofotd2oRI6QHgBZqM=,iv:knCtJBfpKKA9A3bSesIwfTRYeCmque/kZwXlUDmH4PI=,tag:WLS7z4MRNS0uhNgLb/Xndg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
