apiVersion: v1
kind: Secret
metadata:
    name: datadog-secret
    namespace: datadog
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:/MSIKlmMpWqoZIW6q4rOLGjwP0VT6NglZpV/VVZs8nVOIfarFWSmvO3stY4=,iv:7F2a1JbtwUhEO4fKvwV+x4z31a8bT7dygQf6wdHQrt8=,tag:mdSY3NIlEBIVyQ3BsHdnKQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0TGlJQUZlekszTkhXWllX
            dDhNQjM1Nmk5NUszOGhDWjRzR1FDS3I4UlFZCmRVYW1FSTlmdTRiQ2FIeEZvYnpq
            TWVLVHRLWnRNd1BQYmJjZnliUHZ2dTAKLS0tIFNVdHQxWVNwTThoZExZUkpwd0dQ
            TWM4MlB2aEtHRkZqSmlEeWorOXMwR1EKfR/TrmiVDXzEidFjLlY8lVK4miKOHvnO
            UCdNHeo1besz2yeV3IRbNjNU9bsIzxUkAo9+hAM936wtZGQK2rj4sA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-03T23:25:47Z"
    mac: ENC[AES256_GCM,data:K9gAEAmazCuKZmzw7r3Y8rA5Swm61Ek4aTXtLiQPGeW6RsGqcafg7xzXl8thneIG3q36GJl+ummPZD0ZBm62g35hylq0+EBRsWMmfotmdkCuG7liCO86rIjCGGr9mHdcVxXKzNCby0a9HwCBXJwGT5+Q8NxVVxWxEves1tOFYVU=,iv:FGHyru9GVpk1K9XXHIiftjzsmyK4POs93KQUOEIvIYY=,tag:cxeJxDxzD351SzFjA0T6ZA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
