apiVersion: v1
kind: Secret
metadata:
    name: datadog-secret
    namespace: datadog
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:8wUraormo1LDBJ27nSZa66aatugASdl3OCdJJVtggmRK2/6EvTPwD/W2KwQ=,iv:eIAYW+oz2srF0KwnvqW6GByRCudsb6guv6C9wFPNMfw=,tag:bWBoUjgXtjGw2Me5LU5GJQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRa0FabnhyNTJsQXZIZUY1
            OGsyU3R6bHA3d0ZUTktLdFlIUWFxN1BZTWlzCnhDNWpUU3Z6STdlckd0MHFOMjFU
            S0dKMUNBZFZidi9KWm9FWWZuZVo3QkkKLS0tIGovZUtKZjBFQXQycWtDeUszcGpi
            eTJ4dThabmt6VTBTQ0pqa09zcXlkdk0KB9imOq1cVxw3cHj8heFENkXZzksBt6rc
            BdCyzCzyDCo1f/VOUdzsUwRHQ2VKH4dxJMKiJEWgAzKdAe3Juc/duw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-14T10:42:56Z"
    mac: ENC[AES256_GCM,data:mdPf1wcX3Q6FhJCC6Aaec16oNmlAFZNxnQqmeXH25GOvvc4dt63xrhd0TTfnZ+Wdnmv3NuT4Blm+ca3gwZKlwk32OX1W3bdWyH3JyUuBP98IEOcShZ1NGStrEHPQCTfGNKc+DZErvn6F0fhrW9xTmnWFTqRQm1yeH208tDZwJ3M=,iv:fLSjwqwHCrkUeEotcfJ6XcGEHHq2VK6WFwcG+jlbp+w=,tag:IgGFjIgG3NHjkV5OQC7HQA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
