apiVersion: v1
kind: Secret
metadata:
    name: datadog-secret
    namespace: datadog
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:hM/o2VXXcYmmjubsGEObocHcZ6JN/GjgUNmd4a+Wnpa6QoyxlhwmuIChAzY=,iv:IZWucRcXPRNp1xYkXevd+u1fitkMjCINNkcR0ovBxc8=,tag:ZlTaAJ31hUh0Mf/XexeUCg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTbWdObENLV0V1STl4bVZZ
            N0IzU0xPbmdGKy9uc3B3ZnZTajBHMnlxcjJVCm11RTVGOUJkWVk1S2xYUXUwVFR6
            R0ZBeWV3QnlVSG5WblhHK0FPM2tyUFUKLS0tIDlEdFIxbnIraUlZUTV4WEZiOVFK
            RVIyUy9oa1Q3TDd3Q1pqUmdjOERjdFUKm6TG//R4K/LOEIcOpFpTCaP3j0/fApM6
            viu7zsekGS1JM94CDDJyK6gYZucPu3T9s1pFDEptVsVCwgxI73220A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-28T16:24:44Z"
    mac: ENC[AES256_GCM,data:GJvv+YHqFxj5qlQLGTMwjFEA2Tz0OMJHtjzpq+fQRRhjgkvp5fOVelwa8/I2s2EQB7/vS2oNxA1AD/K7aPkgl1ApjD1xFWsjJiqVcqLm6h9lXhADnTdqtqQzDO4vK6OUcJNYGyyZuTHp4YSLidmlxIUTOnpXEWYh4S4YW4NPjAg=,iv:nl7JTt1WfJ76t/6rPuh0UhM6QflCt309WshoOtCowOI=,tag:dbt4fgRRXEcJwGQMwakrBw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
