apiVersion: v1
kind: Secret
metadata:
    name: datadog-secret
    namespace: datadog
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:zwjUvQaQjkihzfwJyEC/BXTlmcFgtQIVM9OylB0x0WfAxhf/l2T86OZ3p1M=,iv:gm4MN5ArpXUqk/c7qxdX9DnLDTKxwbPMCO5O2gjhM7U=,tag:pC3gXogVdNY43q3PR2EQew==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPWUVEMmVER2Q3bXFKbWMw
            VzVrZytZOTkzVEFqQnNybGQwM2JsZWU2bDJjCnFFdVg0bzZ6TWRuSE5kSFhCejR5
            NTFPdXpXS2JTNFFwZTJ5Y0ZBWW1ScncKLS0tIEJHK01KaXpYMVZQaThxSTZOVmNz
            enNsajRmODZWa2JQT3VtdEh2NEp5MlkKsQXsBUtNolG1IoqwaCE1RDrX5SMrxbQ6
            hUFwhWvFydjkCEJ6O+1RXjnnLQBP3im3KO5xnbVa4VrrrE33c7Kg2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-12T20:54:54Z"
    mac: ENC[AES256_GCM,data:/2Xaj+7aEeQUJuZgA6f+sNTGF7TrfVdXV6vEOAi35jMdx9tI0O9cr49Him3UY4PEvhdHtgX6rKqMvVY3B+4UUSOPljaIvaaVl2UQGq9d3cLd0j+eMtzqhMC+a0TweD7ltiNN2lqdjbz3UgqF/Eyv80gt35qnoVzPe5ybtjLkeoA=,iv:vTjxNV/T6yTHAg/8CsWV0qeU5N1VyQ81ID7FF5AZbUs=,tag:RAe/cMUSg7Kbk0R4ayKDkg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
