apiVersion: v1
kind: Secret
metadata:
    name: datadog-secret
    namespace: datadog
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:mgDFdOHOROimzP0nfvZC0GaDzgOocf+Oj+Al+XDd/6UnjXg5jN1A6n+bFdA=,iv:NdAsltI8pL7boBAiBSFsbyvkgv9iDnOXw9yeO1mXEbE=,tag:7SHyff11U6kfhR7yqMujwQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhd28xbTRyWE8zMGtGL3JO
            eGowRDJDcGs2UUtkM09JNURQZ1RwenZPK0Q0CktzTERKWm1ReWFBNit3Rm51VWFx
            Tk8zUmpMdUNQaWhBUVNqY3NlSlFIamMKLS0tIERPclJwd0ZxMjFHZ0hpUytXWndZ
            VEF6bTZZaW1FOHZmT3puZktDVC9YL1UKTAdWUEm8WSh2gNsgn6fRHrpLGQA+h8Dv
            UYk0En5VdrjpPyh2NwNT20jePNltwtf/owoUtb8DK4WQ+OaAJ04qoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-24T13:20:40Z"
    mac: ENC[AES256_GCM,data:9Mwzm/sK0qVbBbFsE0JRxFUHmAxOF0QhHyMptd9CYOuViKo1dbGMkaICU0FdJrZx+ydRtFAyxq6bsjyJ4Zb065qKc86m9/NfRZnlaWFnSkD4mPVtzv3PSYI60nkErUbP9JnakJ/hMIENHmt8yvg0PL34HlNjZ+XNQqx9bSiJS3w=,iv:AcFEad+xAoxA+6LT4o12O3Q0+gsaTETD6OUqIE0zzv8=,tag:uEVbC6O2upcNa/DSnwraSA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
