apiVersion: v1
kind: Secret
metadata:
    name: datadog-secret
    namespace: datadog
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:DSv90NPRlteeyTNytWA/Dg69iqVSWUA7u27D4QZ1JxO+Ycdj++Q8QFwf590=,iv:fee4eTodnXtxjEc9b8jEqN7duFDhEcANSJjhS3w0j7I=,tag:eE2UJZuCizE4fnwpTVmXWQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyNzlqaGVUaHNpZk5VdnZJ
            ZFhwcmJ2NDhIbUMvOHlSSS9NWWZiMmVQcTM4Cll0MVhGSm1sTUtNeWlQOW1nc1Yr
            aFFDY2ZKcnpVc2w0aTVMT2Rzd2k1K2cKLS0tIGMwamw5L2UrcTBUK0lrY0ZxVTVV
            Zy95bTQ2V0pKSTdjckhqdkdUcUYzOHMKjyOkB7jkJVewMe8CXW8kGwJ+7O9XyELP
            WTubpvzd9Q8DtMlLKahWtCrEIEtpLLeTiJSeonosKWmBVOfnhF1DJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-19T15:20:23Z"
    mac: ENC[AES256_GCM,data:ROT/dvJ3XXpsvwjsjaDhJkfB64POR+XB3lj15HToSOj9LzX4DMSt5kMtlGufnPhpdxKUVkpx1JT5RNKaIkeKrYo2LBQsIpX+axHtC0yaEQYbrkXLRkaosvmGFEdcrGfS6QeJQRXpS8ZrwCeD1zyGMOxgwyl1m6qanZwR5NqyQls=,iv:Jp9QTS3K5zPriGu2pqZ4kIcQpbrqwjwNemBEDKfu5Wo=,tag:JfcgGsPOHZaHIiT6cYLu9g==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
