apiVersion: v1
kind: Secret
metadata:
    name: datadog-secret
    namespace: datadog
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:kURLqhJyuiUpCEseydCuZ/cH+17Eij6nMStNVccGlOl3XHa3ZFOKVMAqFL0=,iv:gW7oG3CUleOPtlaOzL9RT7hVIm+2EUBugeesHjqh/wE=,tag:jTrBTf5erMaXBEKYmOFDyg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoTU5mZlpiaU0rVU12WEp4
            ZWVKUG44L3BIT2syUjYzRkFmRnlCOCtDb2lrCkpqMUoxelJsV3cvaE9MM08xL285
            NTE2Z05FQ3JXRFZtcEdkSE1TQ09Pd1kKLS0tIGpXWDVQUVRkQ21ocFhlZWt4UmJy
            SE1xekhxWHM3SFI4SkVNRldYU29rVVEKVF7YjfZ9CGBa4ZNR4Yt4OiD3RoXGcwWu
            jjhfeiyfgb2OxXP1ywZd2/+Q1Vn0CG+ZBcA7JZY6KCHlmtUgw7uV6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-14T11:49:10Z"
    mac: ENC[AES256_GCM,data:8oV0uDdYMCovTq7bvgVmixPvWGGbUC/mitfKn/anlXb9QX2x7mmlOlbWy/23mdcahoP2boZYxpu924W7AinLHog6M+rXiDUJuZLo3CCvZMFCvnEqEDsnZGb/gBm51SKR/Y8VLmyovGA/5cdbg1lE0iXIzaXSV/5eG/xkAZWppb8=,iv:ZYrm6viBJGDjKowaEBfxxOqBsWFYHLKF/wdeb1jsx20=,tag:U/yqUeiesvmTt8ikiCHVjQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
