apiVersion: v1
kind: Secret
metadata:
    name: datadog-secret
    namespace: datadog
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:rKGo5/hFv5h9LAIdiaJdsmdRgpJV/8uyZ5tx+7IySSKzGM+7KL07I6Ii6ic=,iv:JBu23CABKxYJ0rAotLLq0GQzQGTTdkEBRmHXMv5I16U=,tag:K+kRCmAioIeDpOt/Lg7JGA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqTkoydkxFZGRZN0VwQlFn
            UldJTWhwQU1JQmV0TmVzRXhidTVtTGxkUndNCnpTUkNiNElVekJ5V0JSZzc5ZzRs
            SCtPVnVyYWk0dFhlYXZKNXFBcGpWeU0KLS0tIHFoSTdMSlBwTy9rZFRVaHF6VGM4
            U2RBY0p6QkQ2ZVFIY0dEMFhzRWsvMzQKUY5K3brbgjxoTQqWWzfugZpa1JEEIMbg
            VKgou5Y3YMNZp0tndbhPNcG2PYF4kFhRsxfD+bCiV2eq3L/C/zhhdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-14T20:18:23Z"
    mac: ENC[AES256_GCM,data:1IwZGqz+I8EsuClf4erPcW2k0K8B/TqK6bUsspGkFtuIg8PI+jzlPpC3WYp0Ep/68+0Mtw0nK+ydpiO3GBS2/yRqe7rHnN74AuZ9LqXQQNbF6Bt5XJTNH0OitI0gHcQNNm7/8qk0FOhtS/ahL1eWJPp+X0xGw+zThlyU0hLfv4A=,iv:nr7tUI1QwP8rpiZkfKara/RGKxxlXGuUYepbrGL9OKY=,tag:aTEoj1RyrqMuvlU0LCEPZQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
