apiVersion: v1
kind: Secret
metadata:
    name: datadog-secret
    namespace: datadog
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:Y++mkF2RE1HauqjDshV8f8Siep3Lf+oVMnOSKclLHl97Kioq9ymbrRIB45w=,iv:MA0zzIVdICcY/l/XCzpTESnwBNpHSiQGw4O9TmIdw1I=,tag:YVEA7+E9213d7sg/jkLPjA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0dDBxd2FYNzBUeGYvTkRP
            NElMUnFUS09XUnhzd1VMeEYwU1BOL2xnV2dFCnNtZmd1SnhFdDkyNDR6NCtGbXQw
            R3BMZzNqK05tZ1dkUjlmdVRLVWtBYTQKLS0tIGJEbHFFVTg4SXRDR1hyWGRXd0Fq
            RlFxMTdHQXhKZGJzSlNEUlJ3eTlrQjAKaG53Z4T8MiZqN3FH9FmBTTuJkxpAohxY
            al9yMbnl/Eh0wt9PDMyFGGfq32aR3x5hnzKcENusCHi7ZRDWwdv7+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-05T19:04:07Z"
    mac: ENC[AES256_GCM,data:dwXC2hY7VQNfedk7U6xRH568TmA3CcCwaogUJQ6GGq4l4gnxkhYAIw/sP2+Uz2gdNIH0jdsCTaeAbGvAFKuae1RyirUrtUXYS5YVjznftIBrVNEEBBh1IvOjMwbavZ8HM+0I/pADfPOQs77TMaH23sn6aWs9AUxwuT7R5XhtrfE=,iv:gzYE8ZrBQoXy1mNtYCpQY8VVVox10oocMNnmXZ0588Q=,tag:vV4AODcJkBnrQYB8gv9LjQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
