apiVersion: v1
kind: Secret
metadata:
    name: datadog-secret
    namespace: datadog
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:cSGgRG0StGoFy+8XZWXrhe/kRGDMBlZdR3ETCvSpYZLr2lkJjNi29ctTdz0=,iv:+fr68QwKXtHlhZzDTlmjKDHTGWy1H09LX80PwBQSosg=,tag:DAUq5vTXisC9gixwGcPk9w==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYc2NTOE42bkNCaGJIY0Ux
            Ykd2N3RoK1dMUlMrbTBnZ29sMXdKdUdrU0JzCjNsT1FNZzczYUpJZEpxSDBVSm91
            S0VwQmpGSlAwdGJDU2ZVZUlZVW0zUE0KLS0tIGJpUXA5Q0YyNi9TS1hsUjlWbGVO
            aGpCaTVBdm54eHMrMSsrUTZZcEZWZzQKoSHFswcrfHaP2n7wB9DDo7HfC+/r9sIy
            7v8+tMhKc7mYxN0NQNOE9GfxbSDRk9qRHzGeLaemeR1sL/K9JiEqbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-30T22:02:08Z"
    mac: ENC[AES256_GCM,data:T8+/85MW0Ch0KV49yCjtt8o1F7d8HgRJlQ2anS/pd8l9WxIKCJsijXIiZMA6y7jOJ2FqyiMV4nWlApbKK5EzDb29tLpuvH1ZwraGKQDGVWlp89gGdU1K0NUDNZeWuZIKQnhQOwctAW4gMh5MzlTorY30rtcCkmk1z9c7tq6JC1s=,iv:ccuELph4i28RZqPZTpeo3na704rO0HgdcIdm8NYULwc=,tag:mXbbuIzbVTBgNczAZqllZw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
