apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - datadog-secret.secret.yaml
  - datadog-agent.yaml
patches:
  - path: patch.json
    target:
      group: apps
      version: v1
      kind: DaemonSet
      name: datadog
      namespace: datadog
patchesStrategicMerge:
  - patch.yaml