apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: datadog-agent
  namespace: datadog
spec:
  template:
    spec:
      volumes:
        - $patch: delete
          name: passwd
      containers:
        - name: process-agent
          volumeMounts:
            - $patch: delete
              mountPath: /etc/passwd
        - $patch: delete
          name: system-probe