apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale
  namespace: tailscale
spec:
  interval: 15m
  chart:
    spec:
      chart: tailscale
      version: 10.7.3
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  releaseName: tailscale
  values:
    resources: { }
    tailscale:
      hostname: talos-noitlbase
      authkey: "${TAILSCALE_AUTH_KEY}"
      auth_once: false
      accept_dns: true
      routes: "192.168.188.0/24"
    hostNetwork: false
