---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: auto-yt-dl
  namespace: app-auto-yt-dl
spec:
  interval: 15m
  chart:
    spec:
      chart: auto-yt-dl
      version: 7.2.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    persistence:
      hostpath1:
        enabled: false
      nfs:
        enabled: true
        type: pvc
        mountPath: /app/Downloads
        targetSelectAll: true
        static:
          mode: nfs
          server: "192.168.188.58"
          share: "/mnt/pool1/config"
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: 192.168.188.203
        ports:
          main:
            port: 80
