apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:0zH8eTeyyoWm1UZ8FnMjtfLUaGXk5m4MGsVHqJ5exhJ8sIYIuKSTaTAKe+02LcLK6kzN5Lazfhgy/D2U6nJ1NsQ=,iv:rte8xSp2ecZL64XwEkrbo0en8BL1rDK0+0EOCEVICM8=,tag:HUgvSI5ckhN73y2CRTt/OQ==,type:comment]
    #ENC[AES256_GCM,data:kacYoicDh8HKb/ZGYbozyxe0jk4qf5UQkuTlcLde3pHmSSU+VQe8HScTC88=,iv:dbKyMccIehXMI13MU0cGV1Fsh5OmrA9zz10q6qdRCL4=,tag:2WAjnQvtQvJz6ikLDBIKbA==,type:comment]
    VIP: ENC[AES256_GCM,data:1tm5Yu/wB99vMkdeDrU=,iv:tGYEp8lg010ntBMN1iC7nxtaTb9e4W0D8S/I4zWp5zY=,tag:OpY6vzPAX9QR6r8C0649+A==,type:str]
    #ENC[AES256_GCM,data:ObnDfdUAnMyIMpHvvPPeMoGpDcUKykD+40I=,iv:4vxzSKlSWHegDBKIKxRG6UWeIYR8VGsmji5L8X+AI9w=,tag:eKkGkMCrmc5JZiWu7+S+7Q==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:b3W0CvOmzZqLVCeNh3o=,iv:dddGKW7ArpfRYpLnxdyq6nvcHV+YxGYscZEhJujGsDo=,tag:9Ct5XFZzJORXWr8zPkCuSA==,type:str]
    #ENC[AES256_GCM,data:2Gh/zkQDAm75kSLyPm5ERyrVfCCMhgrelPdU1oxW3JRPnw==,iv:ju1sad6pfbxWaQS89mScVJWGgHJWvMbikEkZpBT7H5g=,tag:Yatx1eNRzpApUNpnqVfnlA==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:Z07Nxg92wg0oBuzz9A==,iv:bfJObiJytQsFh7qmNUnLcf6dNV1BdKZXxwjVfAuGG9M=,tag:irjdnTwrdIffETseGDSAqg==,type:str]
    #ENC[AES256_GCM,data:8G6FDEv9o14sPxF76WEpsKumoPhVpbpBA8NytT2DxNYU0bmz+YsIlhXZW+9F0e0=,iv:UODGBwXHI/Oxr4fQh/owF4xxvhxg1OBDp7/JpoGIEAk=,tag:9ds2oUO67M7cOjjbQi7usA==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:NDXYDoWQdwMose5INAk5ypgID7/wZCc5LrRcBPbOkg==,iv:5qJxIP6xxinPcJ2Zr3IQFDt3oyut0bpe1p+wJ3iMNcQ=,tag:wcAXJ0VoeHrEh9EdkVXTvw==,type:str]
    #ENC[AES256_GCM,data:MtIkAbLJboALy5ph6mSHONyawiPKEUyXCNAccVlE9BF3Il11Opxy0FSI4fY4ginQBZ2a/VaHW3exi2ZUB9ssmpFXTBtJKCtpSJUdBylWidE=,iv:pgGwmsZ+eN20tnDpylnnTpEoPJNrSrYeGd4rR8uAhZQ=,tag:SGivkbhnv0yrHiWQEpwXGg==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:awArVdXd6R5K5xH+zfi4,iv:9ksEwJmepn6NikaWNrd+EDTG28ABDjDmUY35rgCwYZ4=,tag:KI+J4E052pYMH3EkhB+7xg==,type:str]
    #ENC[AES256_GCM,data:bhKydmYFi8E9Z1SqgnI6D4tvhEGJwm4mp3tIYy9AXx3Y/nSDpa1xtgNj9Q5kwSPTgfq7y0J+DwM=,iv:WSguH7NaPlcV/Lk8UC/7ygb+w+XMNfY13W9O6//VarM=,tag:VhmiA+xGDz/kSh59T8gZuQ==,type:comment]
    #ENC[AES256_GCM,data:3gogzz53OtvSR9lthBhpaottQFhRH2DuvQ==,iv:Cy6d73CEVFW9Hp0vy3QEWGzICFixpHFBO4Fl2+yfCFM=,tag:0Opz5h3Vai+2c6HsCjuWdA==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:QjWWhg47zI0gUjqTh8GpCKFyzElAlgq11J0Cs1xqyRti5f02NOne,iv:vYyAqx7U3Z0nO2q80E17+9kwp7dXifeb9M8nyDxpUG8=,tag:h3xdykNxRgE1psMqRSHAxw==,type:str]
    #ENC[AES256_GCM,data:SY/hrXVa5p4dMIcMQjn/6ZJWzhwBjlDpSxW5VOzlT8/Af4TyDEaBQHMRkcwBopAbHg2n6vbrEf36hqg2wh55g0N+aCIJJfI=,iv:e03cR3tPAUUAFXQqOv5cNEDC8shz2OqcWJrNJivtKQ4=,tag:xZ7BRTEaleCHNTvUD+rbpA==,type:comment]
    #ENC[AES256_GCM,data:VZpbKyl//jCQXBRZqEn9VRB4MToFbPbAVmnj1DpNws4pet2Z6NaR6D0MxBoFFPFeRYpnH9rD,iv:IsnLIfMJDohxf2+Q3aiUBp++ypy9rmW/5Yh3NDXSib0=,tag:CqOZ5vgINIOp4WTVgLq0og==,type:comment]
    DOCKERHUB_USER: ENC[AES256_GCM,data:5ZVcm2eE3nI=,iv:aoZsRJSwwzsTTRHlCNiLNnuvsIRSp1FcMwHUOP8GXSY=,tag:DzLIcakt8jg1ZQbPO1LtzA==,type:str]
    DOCKERHUB_PASSWORD: ENC[AES256_GCM,data:mYwUOeX0krC7LXCUIx18f30BOmgRptUUmyjUhsiwKEUHozvG,iv:D7SYRGRx4LLSWFwXW7MxajQlnx9LBumAVkep5kb4cSo=,tag:hSr+yada2iArMq38a8/edw==,type:str]
    #ENC[AES256_GCM,data:ciPE4+8oMKyEpB1BCRo=,iv:ZhvUfomgvrFyURf2mGPNauXVTczxlwUujGMPywo/4lA=,tag:atUStoBuKWBmnx2aotHAzQ==,type:comment]
    PODNET: ENC[AES256_GCM,data:BUOjwQbrAuYctzft0A==,iv:ugG1LhN8D9Or2fdiAN8qyI4dvjcLWeCFTRX0JUvryZ8=,tag:vO1iz1sOQsX9vZZMiF03dA==,type:str]
    SVCNET: ENC[AES256_GCM,data:Lco4aVARcBX0F8bKhw==,iv:KE9nPHdQ9h5RTZ0hZVAAiepw0UR6pbUrMTK6L4beO9Y=,tag:38vWPaxU9UR4G3uYs9Zorw==,type:str]
    #ENC[AES256_GCM,data:EdPfWeDh6lph+oRvAwUXLAI7FARJGGbYINo=,iv:+hrphejTYN7PFZNRK0UsfD2Mf2NbiXuf3lyTz1/+lfo=,tag:mM8YYQN9CbvAJ7eEAwpflA==,type:comment]
    BASE_DOMAIN: ENC[AES256_GCM,data:4sZQ0BR3Z6d74qyr8M41Rg==,iv:qnGQclBqpbdAV4BwKpybczavGdRsb0W/3rg61r2E7cg=,tag:qpxvGsJIUyHdEA863mp8JQ==,type:str]
    #ENC[AES256_GCM,data:X8EQ7mDU8bw=,iv:bW4IHufI8aB5dqwbTzshpLku65l4quke2PHIzXXIAAQ=,tag:lrJcFdj1+Bk9EG2z9aB3UQ==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:ofyGihHpSwq6J0ShjU5l,iv:n05UkbNmFyJK/vh70gWRazd3Rr3Fs0Xh/0ZA9typnKo=,tag:C8s3jrxEXJNaE1Cw8sUZ8g==,type:str]
    #ENC[AES256_GCM,data:i/DvkJn4PUwWWo9G,iv:BeV5WH9WB02NWx4SyFypQE2Mb/nkgAYDCcpvuCRdA6U=,tag:xLTSGa4ruxNt6T21ni77Gw==,type:comment]
    CERTMANAGER_ISSUER: ENC[AES256_GCM,data:3JX2+0qttt2GKYQkAStfQ5mDM+mn3/ox,iv:BTfk0N0plZTFkf5IEuuCvy73t3rNkKjQ3rTkd8aXS+U=,tag:vtCHkk3wgTZDoeytxXkVUw==,type:str]
    #ENC[AES256_GCM,data:s6MTJxqwWvFRpPloRqAxf9wCwIA=,iv:bTSb6B2/7pCKOeSzjI38OKTUk0L8/oYsgqQuNvs4tb0=,tag:S1ENnjfA4QAGqNvvWh8hVQ==,type:comment]
    STORJ_ACCESS_KEY: ENC[AES256_GCM,data:SxgTrNJlqiWKZagJY8j+8HyNE4gCPOdzuHMWTw==,iv:mL1/ZYhAmLRMcHKUk+zRlyRtnuw8RaVw1nV9/SKPryg=,tag:A2rMxWl3MzYy6mzqaarkzg==,type:str]
    STORJ_SECRET_KEY: ENC[AES256_GCM,data:aFheQJQdfTgidErXmKtQkTMtdve1t6UMojSJ6su81Oyw9cSYIlzmJ8gjQlJ2srPHEYNUlKU=,iv:hUOUG2WMUXS/UCkxaqs7yOsT75eXDJO2+OPHrKOOxdU=,tag:xP+UGRHl5v9rxTdZUOm5nQ==,type:str]
    STORJ_URL: ENC[AES256_GCM,data:trdpcM2vxD7ikBgj1qYZ7HyovQ+xJvC4RThX1v4=,iv:1XQ3isP4JrRRKwTDCW6me9cG5m62383KUVSXuySUK7w=,tag:LaITMwKHXIxnEtOyhH+6HA==,type:str]
    STORJ_BUCKET: ENC[AES256_GCM,data:v+J7FR1OVV2gUCiH,iv:JKwFZI0NxvUhxOYaXKhh3NdojPyuYoYiVEx2g7QIXU4=,tag:GtPMmSR1PV+6UrOUqfQ7Ew==,type:str]
    STORJ_VOLSYNC_ENCRYPTION_KEY: ENC[AES256_GCM,data:a4+F80O1v3S4gD08M/zmbt3Jf7F0HwlmR3RxtnVg,iv:4CN2ZqOT9xaHu6uvY3FDQ1JBfzk6KN0/zuEw5Fn4iLA=,tag:hT6Bj5amKQ2yt/oX6TxUrQ==,type:str]
    #ENC[AES256_GCM,data:wa8j9zZiAiZnCdCdD00+Md5Sb4r6EAmeyJeOnxLlPh76,iv:D5DyOmXfWIccef/3ZU4QWWwwrpz1M3XZkN2rrlrmOeA=,tag:6k/MwAozUk7mau+Y48xUuA==,type:comment]
    NFS_HOST: ENC[AES256_GCM,data:sW3ilYB7VR8yRUPFOpo=,iv:1/gdy6hV5vlKim+zfYXtntO5YncJ8UdEJAWGpQPGsuk=,tag:OUJE18fxqkjPEotKikkvvg==,type:str]
    #ENC[AES256_GCM,data:qublbqAcrlsvdbtis1SuLu7s,iv:aJm4IsrVhTArF5JJ08XAGzAmhSjvPtS6jwzCJXSPmCQ=,tag:R+xeO1BSBcfzV8xRvOC93A==,type:comment]
    BAHUMA_ABRECHNUNG_PAPERLESS_PASSWORD: ENC[AES256_GCM,data:7oUrWH7+SoTns3MF73EBIgp9Tq7k25RRyIgrRBFmf4lqfrHo+yY=,iv:xb8WCFbPx75NNpID+Jp7q/Ij2KShOtAWZvIDekO++M4=,tag:U+EGBHpVcJntWuQozoNpzA==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:IncyGA==,iv:hoW8DT57oVPR6XRC/wWfEkoot9Mir5vFhNVO+0Rd7B4=,tag:DVVtm/HH5g3xTnPbkUn84w==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnVGhWYkQ1OGQ4UG81SExQ
            ajRGMFkzY2xCSzlid0EycnI3c0lXNTNlZDA4CndQZkRzRVZ3aENqeldvRlQ1b2VL
            aERuaFkvUmE3cnJYYkpvdHBNSmNTSDgKLS0tIE5RY3NGNDlNbGFlRVJZNURsVzZu
            ZSs2L08zd2RDZ21KaUhqZ25MNTdpVncKaNe9aPfm5idbJJbl9gvXOsT69SlZcCal
            3nCb/io4IfrfVBECjCU31wRibEpQ/j/fT9g/SAgCa5CMpY68MN1Ofw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-05T20:39:06Z"
    mac: ENC[AES256_GCM,data:z1Dpf5Xd/2Z2KfonQcO3BDeU64Nz9IdUH6jFvhDuKEsKgquDI4Q2mNMnJaQQxtRgBHlN7HORzQh9GeKLnVO8PepZ8b+SQxYUK8DmnjkjioCimT5kU2c25/f6icLaEXstK1L/l9IuZd+ilfsdaXhxtWRhKKv4B2Quu4TEcKiOLvo=,iv:JjMHl7E9/dZ6etJXRRlgyypcPij5jPp6F3A7oU+lvU0=,tag:IrXG7s+27Eau0VO0t9p7Kw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
