apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:r7oo4agj7QGFIdX6nsa/HQY7eEg89zflG70CQ1yEPAsbtBlvJpWbmelmBVmrzf4pFjemxX9WIG9ji7QxwejbARg=,iv:NDWKOyuzr+9R/Emu7a6mxZNUpmNJAJl8EuPdrSmSfFk=,tag:Jeti+Wuj6GNBhFyhUGPAbA==,type:comment]
    #ENC[AES256_GCM,data:j0cM6gpSPgnd0Xws7pkOJ7YgzuJ430km981jm14Z9yufk3kRdZjDNtgvz1k=,iv:zer9fJHaQWx1cF06WsfsIz5JuRLR5r2qXx1i3KfxMBY=,tag:o52L0TvOBNLt5+Z97SQCcg==,type:comment]
    VIP: ENC[AES256_GCM,data:KOSGYj98WNdiRLFlloM=,iv:7owZsP6dgQGKT9LupKK7jAu17cwI+hMHE/YjWk0Zk5k=,tag:aQzyRzTxYiIAxbW7kt8uQw==,type:str]
    #ENC[AES256_GCM,data:K+hzpRfgUiLMKsWnPFtbVwfwP4Sco8XuqYc=,iv:FU8BcwpzOxptPm7/88XFLRzffLw35AzOqdJPdEAYHpc=,tag:J8IkxTPYImtYsH/yeS0juQ==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:RIPGg7dUWI88Ufzi7Kc=,iv:i919htnI81MF6yG3nOwSN9KjZGUGBm5jEqeeFJrHFro=,tag:fNpFGcpofEP6fDDmyUfTTg==,type:str]
    #ENC[AES256_GCM,data:L7rbYjv6zMuieh6xURqndXRVamMrNWwrAyLA1JuMkayZyQ==,iv:YhEGbKYRYv2KItD02bMsoXEBN6UMODJfE3uM/F/gRRo=,tag:K2qK5ep1gfniuXcVXMGnXw==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:ZhSX1+cBbTES4obHaw==,iv:VccMuJBDjXz4etfFYmmqsZD7uoD3SjgIz0TUc9hv5pE=,tag:vrfNFo5WZsO5Pz7U3NBN6g==,type:str]
    #ENC[AES256_GCM,data:IGzrb+JJi8+d3kHVheph0aBH7HYv1xO2ExJT+tDhS0RhJjapOIiyV2Pca5QX1Q8=,iv:pMq/vs56nTSg6kTxdNnydeeDBoLHQWbzL23IT1BP5FU=,tag:hacpkkh9mZx5NvPuRkJwYA==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:RktvQeeCFg9pRkKjgDyIZWAlix2v8AIE4UqLT5ummw==,iv:VVCCXSNO4nChx4hDeYn7nN+p0rxM8ibwqRVNnn2QTLE=,tag:/jnY2IX+bvNrd4gwmikMDw==,type:str]
    #ENC[AES256_GCM,data:uLsdogNONnCZI/YYptWHCWmEjz8wyjyMOWyWR3PIe3udAm9rHiEhYr0rLdXXjGmMgbz2gTAWa/Roc4t3/X4jhmVkWHEDGNmn3tLCaDDUAyQ=,iv:2ZLIgPuKBn9RzlHZK9ua5swIXfa2jS5l9uVkYyWTOAY=,tag:IV1z7UNwey6kID6+LnimVg==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:s+zWIaIwLz2kiSwzr9Lo,iv:wBtgVDRjWgbVuypQsuG1rzsr4FACxKZKMa8o6qC4xC4=,tag:R9PTbpDmsBbtRi3JUK4mzA==,type:str]
    #ENC[AES256_GCM,data:WN6CySpg8XOJE8JEyIw/Cj1Wm3jP27kC9Pri1TvyuaE/tsuS6SkMQeqs779RnT6x+PXF1cDiT64=,iv:yCVhFIqduTAN6CJObdOLChSpU4mTmhBEGp2hNfLlo7w=,tag:BVixFflUAoQv1yBk16bPHg==,type:comment]
    #ENC[AES256_GCM,data:viNs3F/mR8JKTVy1mGZqZncYGNBGyGo8fQ==,iv:QwuiCCLuSC7ngMcrdOhl9xey/6ndyadttp6Q8ziEQKQ=,tag:0fw6EOkcPSV0OR0A7vg8uA==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:Hjqkp0CwwNe6OP2hRtYo3NxL0B2b7VJaylqKuKlPKGE83P3Vyhn4,iv:jMF9hwx5OnRhsVXQCZF73sTJ2Zjlz+cxyUo+Zr8JELw=,tag:tJvB6/Jf1QHjMAanuWRSDw==,type:str]
    #ENC[AES256_GCM,data:D06zFI8sh29g0HaY55yATKtMR1i12NC03B+V+k2JNzqKa4eUSV6azXLi6q7IjYxYTLWA82Hpn8rxl/tbpHrgXY/jVv6PSuM=,iv:94Ok04Nx0VQES4PWOxrS/ljZQ1A+hSc6XG/BgIjCLEQ=,tag:jBeJa2Yg0+rJ7MJgHhKxBA==,type:comment]
    #ENC[AES256_GCM,data:GBQ54tqPapTjfgBvzxRohawl5c7zY9pqAQrsIuY6DeJPttt3gkise+0RMMCPWRN/CsrHNy3R,iv:ctA1Adzz4/0YnKPWBWf3qRV+WnjbZYpqpFbk6trZnwQ=,tag:l8Au1d/ihDvutznPx3mvQw==,type:comment]
    DOCKERHUB_USER: ENC[AES256_GCM,data:F8fsueLH3ag=,iv:w7hw4WEX//h9WzFZH2QC+K8ejFBjIlLY3z44/a6sG1E=,tag:8OOLgiXPUk0cQo5DXDyCOA==,type:str]
    DOCKERHUB_PASSWORD: ENC[AES256_GCM,data:trhesctsDbW+BOO9KVpME9B3kE6hS3OGtarsPRQ1c4kJ0Ife,iv:37wfn6B776G4FFzs1m+hqrACMtU558oVxphQkrR+7yw=,tag:4r6+yruK6p4YTux+VR6EZQ==,type:str]
    #ENC[AES256_GCM,data:EmxPgQAsMJzzTbrxDH8=,iv:m9BZVviJVKCVfoA3QgDvpXcFcKKoPwmbBT7i5XBGdcQ=,tag:h6J2rPzZ9bNqj0h3DbxI1Q==,type:comment]
    PODNET: ENC[AES256_GCM,data:Y1Zg24jbwXb/5qfjjg==,iv:3UloTA2JisJRsKe11IDkHpu/7uhiFITjcrYEZMRV8lQ=,tag:ftXL8TgUQoD7nq2rYCMgRQ==,type:str]
    SVCNET: ENC[AES256_GCM,data:wNCNM9GITW/u59/kQA==,iv:Jth8ETABXnFzPoQQnlkJjhINeKLbTXoLlyuq9JytF2I=,tag:XLVrJJ6sMw+NQlyby9dIlA==,type:str]
    #ENC[AES256_GCM,data:Hq8LBsL/qeTn0muVEC6wBfowbyDtq66iJ0o=,iv:fRR88AAksu8PCnMV9StBI5VtupLcqf+OkmSIGbN6okg=,tag:x2AbgGdajh9iyuGkGBdugA==,type:comment]
    BASE_DOMAIN: ENC[AES256_GCM,data:ilpXc27+XArO77ZPz826ew==,iv:iOxLaswjzUbCPlj5PHSxXGERtYAkcKAalfYymxZncPw=,tag:O4WJgl/HSGXedwm/eIIWEQ==,type:str]
    #ENC[AES256_GCM,data:PvbyEAXGjtQ=,iv:UKXuirSw9dhtWtE7nxvl5wtMKYHfCKu37A1HRMP9ju4=,tag:+D407vfQxj6HsQXusPdgFw==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:tO3TdMtF9gPvzWoy+TzV,iv:7U0nuE7fvoyRv+voT8F9afdHyevEkHNd17sj2FEWnzs=,tag:CyIp1Rf/ZAv6ZEWHNHBTTw==,type:str]
    #ENC[AES256_GCM,data:0Xo+D+ruJ4tw1Bkf,iv:ITrV1RGLrd7DyDVdh2eB15YPLdtJD8+peVG0ncgE2fg=,tag:+8zuJYnldbUrQIa34a7tZA==,type:comment]
    CERTMANAGER_ISSUER: ENC[AES256_GCM,data:BTg4XjJT5wQkzE6g9lpIihEBIlCAEmu9,iv:uJmenKm2pblOr402TFZl4IV3d34Sc20DH7Y05BFIVZk=,tag:LzM1mBtmPzKn8EaHQXYXZw==,type:str]
    #ENC[AES256_GCM,data:I5hum8WiwGSUCU/zrYpPMJnCVK8=,iv:op+PHjBWBNg0DVK64W0scoSSPaSelp21CZOSMtXogXE=,tag:l36txDyAFJ0HWw15eurcJA==,type:comment]
    STORJ_ACCESS_KEY: ENC[AES256_GCM,data:Nb+f3SS/za8Oa1iL1sAb9Jr8FA9P/ktz54Al2w==,iv:m9jS3gutZ1aOHviO5z574a91ItxqyxSjEjHWwzJXnKI=,tag:ks6wFS0tfBAT5RexgMItaw==,type:str]
    STORJ_SECRET_KEY: ENC[AES256_GCM,data:xQqruOVW1gLbMBlUI0vb8I99DETAFZlNSm/EvvwOSya/G52UvveuTZ3/jAiFnenz6VtzHHg=,iv:zDrdzSBQpX9OklKjf+o1pVWn7ikrGMk1CYtXCcnznYg=,tag:4Qb7rKmVr9oldiUJ3HN2LA==,type:str]
    STORJ_URL: ENC[AES256_GCM,data:ajwX5ykIm17nKaMRPv6n4e+CIZsMgEaooQKxI5I=,iv:TrgloyBHCEDIEWSXeWL8hwVYDh5GtOJQKrEN67vUlWk=,tag:bVt3dvLMSjYqvA/HkKqDOQ==,type:str]
    STORJ_BUCKET: ENC[AES256_GCM,data:1VOp28ffFWde+y8l,iv:iO5ad09xJ3e3FBK9V/QkjOBiP/r1WChjMeLZR4zMyqo=,tag:CbkXrFRyK36jHMHx2dsT0g==,type:str]
    STORJ_VOLSYNC_ENCRYPTION_KEY: ENC[AES256_GCM,data:7hMwVc9i9jNXBQSVlggQccv9jblxZY0sluPx6fOG,iv:CQXI9uSH82XVlTWLd66Peuxsz56e6/0WnFq5/YGv6U0=,tag:ALPnrQCOBlTuwgRefEs0Vw==,type:str]
    #ENC[AES256_GCM,data:YvqEf5hGQshwFhnw29bwyMfEI0e4/3LW5A/9HWsoTgjK,iv:tNoNLR/JMaf3fB9NQdDYMehX+0AkJqvuBbtXOA8xf7Q=,tag:H8qe6SALb5ai7MV+kpdiOQ==,type:comment]
    NFS_HOST: ENC[AES256_GCM,data:SuSjZeVrzcJ8qb1dCFg=,iv:OTMY3D6aTr1Fv+5bx84g1YP/8mQQa5jpx2JnKVI2FHU=,tag:3sUMov2thAqJvSLPMPAKmA==,type:str]
    #ENC[AES256_GCM,data:6l2u0TIltALFHksmBhwt/DHp,iv:hsmWfyORAnpwa+O/WewlFJjyF9HIRfgusfG8ohOuA14=,tag:A7+elJWlBVMCqAkw5kF0vQ==,type:comment]
    BAHUMA_ABRECHNUNG_PAPERLESS_PASSWORD: ENC[AES256_GCM,data:b3ficj5z6alSGL+f7QqoxC85BGcqzXW4KDk6WgMV+0Y/W0wjVNY=,iv:hP6kTaUmbzWsomgy6r1jG3xjyVTNDa5CIl44TQytnQQ=,tag:xTM6PuOW3Zt9YCOXLqI5uA==,type:str]
    #ENC[AES256_GCM,data:Uy92vZk/wgSMsA==,iv:xJjGsdE9EYj82Qap3Mwq9vmz8vbd3KXF+2bgkwznXlY=,tag:Xg8yqhgsJ4jABzKXUvcjGw==,type:comment]
    NEXTCLOUD_COLLABORA_PASSWORD: ENC[AES256_GCM,data:dA+MhZXRXIhOlRnjG56VZbkO4uXF1L2o6/oDEhiNSf1bR9MHD8+GBw==,iv:fUfP/wE1t2KO0ASYty+wWnhnsUGiA6+xPkL2b6cWwRw=,tag:fk3kK9lJQvSthjDk0G+g9w==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:DxNIaw==,iv:kUK8je3/WwMKzDcfFsUc2ayNxR/WGa/rkk838Q5028Q=,tag:alLmdJ0L3nQftP1yx5N5jQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzeU9lTDZMVDQvZ2hUcThz
            WEphdGp5cUdKdmFabFcyQ0lBaldic25IbUJvCjhJeGRtV2dONzF5NHVwMVVRTDJU
            NXg1QTdNRXlTdkZFUlAwbEZVLzRwKzAKLS0tIDVmeUhNYWlyb1kweE1KUFFJTTJw
            dFpnT0dBZjRjaXdEcXludHBNRzM1RncK5sGT6D8iRKqAu+3sljnPgpB8lAm7wy2m
            EGwnTDumSimJos9NzpBvU7Ybpi1okPai8XgEb5QgS62FAagF1m99Lg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-05T20:41:10Z"
    mac: ENC[AES256_GCM,data:JJJRACBc4EseKncLgu3VmIrfDnInGWml67teWPoZW5/20JfQpxZt7Po9m9UIRQr+Z5+X5kFkqGkemNr73SdEoI948GwASVzDOSo4Z3VGwl/whB7NrEs95buVNjIJOitlOFePAv34WbjckS2Hk16qIYjX53ifs43n1I0VA5D2r/M=,iv:PF+53ROIIOttUOOtfCoewCfMgOnnUMsUZAC/bup/Gcc=,tag:XnJHy//ZpHOgmfWBw9Zm3Q==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
