apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:3b54tV4BDrfQgwqJfHzDvYIlWTsN81KjvMeKZDaqVQmRI7M+mH1X5I3WhVy+HN0R+xgRZFjTvpQWQW14OMRsGO0=,iv:qEizA1irTpxRFVFj0tAKQkr1WtaTGJaKWQl/U6i0KsM=,tag:O2BINdJPtCXLbCr+i2sLoA==,type:comment]
    #ENC[AES256_GCM,data:4u/piCE3yCerDIoiDfXdMrzJn6Oj8nwxu/YZJa+dKjAlVMW+tBxzl9pcXrw=,iv:Nu5tHELTF+j4McP2Gcg7fYErNfkrzOck+cxEDGdecRQ=,tag:wowyL7uKJ06+2TyzdKvxMA==,type:comment]
    VIP: ENC[AES256_GCM,data:iAB5fkXDNW61AXUknnU=,iv:493XzePg3GFici+WqSYvZKtHhyjBqhVPBbwKM73eYkY=,tag:CUqWR0T3qZmMVHfhFimbWA==,type:str]
    #ENC[AES256_GCM,data:UqDU/U35mbGcmazik9FmRHdAlLt2bOhBF+Y=,iv:wg19dSOmTgEfM5r0zPgtDVucWl5Ue5W2XyXr2XfN3z0=,tag:xwb4yXJPTjqRJXKjJQoz+Q==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:z5+y+G+ejtqSgv5Q+yw=,iv:FsiZzj9x/Q62E+CZBpr2BO3MPnOsEtLz8XZIGWmhTh0=,tag:3ZrWY1fpu1SWdakG7yTFtw==,type:str]
    #ENC[AES256_GCM,data:VEfq/bYAGOBR+dFUud5GpZU38OogFNbTB6GJmyfZejMKkQ==,iv:ehvyvUlZFj6GaKyxzeAK92QIH0iA75R2p0xhQNw9UQk=,tag:lza70GjIAYaq0NHP5VSw7g==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:gJQrD4vjXp2PjcIfSQ==,iv:I1eUYdOTUT1RbWZmIMxbF4e6PWkfJZIBbfhDj62+MsI=,tag:PV5yL2+Lcovpu2iOAA5Y0A==,type:str]
    #ENC[AES256_GCM,data:qPHOkaeThe2eJoSuPSUideNDxKxTTSEERxv+2M0DA1IXTUt4qyXKWHfl9Q+fj1I=,iv:5tMLQNJPiRJUAx/FfsW0waKrbNSzqL0GpAz87OA8Q4Y=,tag:QyPiVPY2m3NAoCo2MS2EWQ==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:iBeJn+/LBFsRUeyBZ1EoJlxZHJ3K2NYNTvS2eTy1lw==,iv:i3DrdijF3gFkFLNzzb9RSSaouE/cWFoamn09wMiH6Xo=,tag:femw5/u+ZHzvhmCF8xVZZA==,type:str]
    #ENC[AES256_GCM,data:vYVrY4CEmINSHN6FGAGK9yQQpM8Lg8zuvYn0+/b1gPVLElCPThUgC/sjk699mj57QPbuQAb0tKsvUZtsxU6Plr/5XGohMUtAAYxRf4MxYuw=,iv:EIUfew0e5VrKpW/GAxUFE4Z3Y2SxI8RFcgf6hiQRxpQ=,tag:2To3vkS5tTHS7jMCEw1cJg==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:VdmGDDQBp2FArgyy+t3r,iv:YNIKiBOXnJqYqrCVJbx8pyA/dD+ZyJEUp1CfMKBW0Lk=,tag:JvlBueU/hqZsET9MT+Xbxw==,type:str]
    #ENC[AES256_GCM,data:hZePgSrderKi+f0JEvHtBfQB3fjJ+0Qnmn+uLKWgJhfL1UQMlTr8qlj2KIAonrwgdAvU8io1q0Q=,iv:56bhl+8zv8nyYope8clbpCYdfpDsW+/CmTAlnhwrruE=,tag:Sim3rcnLpa9I0hateV0aZw==,type:comment]
    #ENC[AES256_GCM,data:QnHk2/OkJIdZ7IKKKnidUUiGQ5UnozbPEw==,iv:Eo2KedmtzdoaQWfZgfFMiXB8a+Lfw3OYVOCV7y8sKp4=,tag:krW+umXhwGdH1r0TYYTV8w==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:2bu6UMpmEYbM7cAHti3hmSokFJwr+FvsZ5JJBCeIJlAC2Phm7R6P,iv:+aiIPxZJzc4Niais1yZNOE5JKG2fcoLA5sxYEejFxp8=,tag:VZ1M1Quno/S9dkMcbAoxFw==,type:str]
    #ENC[AES256_GCM,data:zMPJ8uZgpY4WSuGgXV0tK13IpLTx50XTemrsge78PD8zf2uDAUV5lIxOY0EnwdbHWYDK1lM4TvnQ6NOiSqgbwJ5aRICw4H8=,iv:3Cvmz/pEbBq8UlOUtyx15mgG4UHQAiTcbIemIa9edkc=,tag:EYJr8V3AiTMAssLGsiC2dQ==,type:comment]
    #ENC[AES256_GCM,data:ubk88HR86RbjNH4aRFl4wegKu0FksyrLIiWpp9mJltTcSKcNspfxRxVjcjVCRI8IiiTqOU+F,iv:xetGgUTP91Pm1BGw5+qMGQ27r0R/t7DCFyvU3+aItcc=,tag:oDwvhMSphh8gY8U3GyB9Qw==,type:comment]
    DOCKERHUB_USER: ENC[AES256_GCM,data:+V0u15hhoGc=,iv:lTPRTHKjD2vw+SMfXqj0N/xn46Sqoj8KfcgElJlF2dE=,tag:pWun0NuCrE9zg6ce8SzjwA==,type:str]
    DOCKERHUB_PASSWORD: ENC[AES256_GCM,data:2L7xEbjoE0IxLvsfcllJPHXN1tt3LYahUiI4NdYToyCB1nIw,iv:wcIP8Tonia6vtASocSelVTqWt2wx9afDZTxEVd51vws=,tag:TNPqrKD0lxsNo0JorSzpcg==,type:str]
    #ENC[AES256_GCM,data:bNmMH7cYR0jUsLYWJZM=,iv:3O2oc/tIcm+viJEin1UEbdA3cncVrxU4wbC1mIFmG78=,tag:EGWc77DuT6ht74RBhhsbiA==,type:comment]
    PODNET: ENC[AES256_GCM,data:vvOBD3exBeien/+xfQ==,iv:etwyeZj4a119HmNARQ4DMTO5feVDv0CMx3yu4i/EQsA=,tag:QR8jmn5IOPbhgruZipaBJA==,type:str]
    SVCNET: ENC[AES256_GCM,data:vuKEb3oUGo1jj/9wcA==,iv:pkpVz4JWRlyy04FnMuUVuuRzJqRvmIUd9SMlRUUnFGU=,tag:nMZbpOOw9tq9NczyPU7wSg==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:7yEvqA==,iv:ceuNR3nVSnj/aIV+IMn3T6qvBXZdNgMEkGFb3mMbL54=,tag:eH0zVkoBJezcuz7BRhTHfw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNYi9VM2xHbStKTkpHaEVa
            OGkzRmF1TnA5dHNTSGphL25wY2ZKK05jdDFRCkhwbmJUZ2lTeTAwNnhGcmlRV3Ar
            bjMxMytJTTArSEhRY1E4NDdiTUllSXcKLS0tIEcycWVnOFAzRDd3R2tMOXU0cTlP
            bXNOenVkZDN3azhZSTBjVlhUL3pGRlUK4jJjeu7qCxkI0prOvCLc4G7cXxk6iGxq
            Uh//TOipcBS8EgP0bglXbk3CXd82bwttAQ5/EZAC9IoduQQpywUgpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-27T21:20:56Z"
    mac: ENC[AES256_GCM,data:ArlJSUathBcf/LSXX1CswJSM+b+hcIyWgOEeVttW1w32AfWIsTCx9GGLHVfqXTTy5ZV7onMcWPUWAACJd3BZNrAozLNFEo6PilHs8kRmBLz/xHLyzbwyE5LiP0sfxVyUtZZfrdpdzFLLsC9qT16z5AJk1HMfUm5K4KQmX8E5xvg=,iv:NSH1BRaO9OC4rcK9dMm+xYS0vvwxseu+2QLinyVpt1I=,tag:JxU9xvF90GtrGDtivpO72w==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
