apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:O57ChA9BJBVAz0wBa1FR+bEN/bLmxl+VQYOdpebtvkEweMOTOzpTD2ompGcBaZah1NavMS9/7zYjghEvCBvKmpQ=,iv:zDyt1aceFNUSnC7sCaVBVOG1r90omJIc53QW1h221e4=,tag:pK3rEgvSF4pGii5SkFZhIQ==,type:comment]
    #ENC[AES256_GCM,data:iXJ7Enelnk7sBclVDB9avp6cZMRZNGutezk4g/T0PEfv5aUo7Bn19nECQYw=,iv:hasMEFl6qd3FxV+Xo0NnC3r4KGMpZRS1kLK+cn6R66c=,tag:CQ8uatdbUVBs77hfRkeE2w==,type:comment]
    VIP: ENC[AES256_GCM,data:gUk2skIhg5aYX9venLQ=,iv:MLo9/6FF370DVxeE7MI3gy2LnRR9+1hC/bJGIU6jMho=,tag:+YHyco2Ok+dA7Q9F+2Vvqw==,type:str]
    #ENC[AES256_GCM,data:Ewfqqf0asE0I2OD6EJpxoF5eLPGUZrPxv7g=,iv:K3ha+KKxEbw2T/5aF0HPtN0pVsddTIg7da4szYXsklY=,tag:Czs8nWXiSYkwEfHh7uZnLw==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:UnBhJHmB+oIeo+o2uTU=,iv:RPEgpAQD+AdUZTSX8dHbZi1VuPSl20g8KmPGWA6VsQo=,tag:KDBV6nT1+vqpEUBZfTJqnQ==,type:str]
    #ENC[AES256_GCM,data:8iWvMTNgN7Hvd3SI8XUI+8NjaNUt8SXof0S/OfOyV/fzVw==,iv:q8boAwq/Z+vFauf/TvSHe9vlvQ4V2vXcn1xsYCjm1YU=,tag:VrXnyv1uELr7cQanNsnNUg==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:kFmOmcsSbORdENmMxw==,iv:Zlbah8N5+gT3tdTCZjIUuSh35E6sEtM10z7gQfn5aS0=,tag:LZ7aFUVLFSegrAFDDz5tKw==,type:str]
    #ENC[AES256_GCM,data:R0SmK/tRtOQ9IRUAVZcYcOCWlxt+3ZuwFDMKc6vgsI7POoWmKSx3Dj+8MPVQoMI=,iv:ZRGu9+CjWEtWYMDnvJ6+PNTiQ37pUXqqIIPoFt/6rqk=,tag:cv6QcdJV6I75dnoBvIZTXg==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:60wdcuwa2hdHf1bCahx4dc8dmf6BoUCaNRgvOut2Kw==,iv:Xh6gYtFOucoDcCyJ6FBCEW2ktBs/bh8e1TmU4J6vY9w=,tag:8BYozHJ66R4IMClHaN9KHA==,type:str]
    #ENC[AES256_GCM,data:ALHXtAvk4Z4Nuo/Ekjs7Ga6i08CWJozzR1V5FWA+Hu9LWB4cUtGSPXVZMdr28n32K2anN5Qqv0VO8I25IJssRGm1E/lqpAhcoCiDpz4Y1kw=,iv:21J4LcgRVzaibiV72Y+DxagvxoyKbOeq01R5tHunHTU=,tag:wms3l+fVH/nRVvTxs3iPlg==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:/+/BnLsxryg0gGDo6Bfx,iv:7sFzuCLR77SPSeLucfUdRQX7hSgQWc4NQ2jHTnZRgk4=,tag:imKroMmTuGbG+oMvF1/uGg==,type:str]
    #ENC[AES256_GCM,data:nHBlyzCBNTTTp7pawX9/4Xsoesv61SnpS/m61LB42GVefOPzjf2jaah8YYS09He10JK2V+/sC/o=,iv:3wFIYyQiqydS6CVOHts1h3B7Gp6yXxnOTWFguJYGRsM=,tag:YP+eCbWt94EQ8B2CcvUEUw==,type:comment]
    #ENC[AES256_GCM,data:rz/94aXjsk8T9sby4R9x/MckyKWnHQ5AYw==,iv:7d+51s+J6HooxIIfPnTUxX4VGzqySqtF2zbkreG4nIE=,tag:P0jcP0BMVdjixC6RyIXiOQ==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:2ahrseUUi4/b3bzwx5hyxZU2hjE06RjTmryizaNX61Az2MCx664k,iv:nnOwYu+tHWDUusk6TqmYbFZlvJZV3eFvFg6M+BCPqHc=,tag:V8z4wCkhU6V2xigs6GBHwA==,type:str]
    #ENC[AES256_GCM,data:2qtk8rKu14C7SnHBLyJzm9XGKz1EgXYzZFKaskntyu1WzdG4dfXwD7gEhWlDuAlbWJKY3dZ5WsQE/pnJZbb3rJBONYlipqA=,iv:G6tX/JKHmol1rGdOyil2AMva3j424cheFlzzdzHIwp0=,tag:9yys5wNxzq6y7dR1SIe5VQ==,type:comment]
    #ENC[AES256_GCM,data:MShWqdUG8HT2qBD6t7KRzXTjlYzrFYKFVaK8pYxB3LRk7nwvIn5wG+s12x1JLrGRYJdmaPhB,iv:l6NxICreyFiCq4IfNWTj456EVJ2ngZYTuur8j/0gcZs=,tag:NcJs+b3oa4EwtXlcvtI0mQ==,type:comment]
    DOCKERHUB_USER: ENC[AES256_GCM,data:XmGw6shkCYE=,iv:eU7/WnAOq2Me361V7VG9WXsDDkXhNYlWhzr2SkQjRgk=,tag:4OeZcvL2t7ZmKztgUJ5NVQ==,type:str]
    DOCKERHUB_PASSWORD: ENC[AES256_GCM,data:peJoyIG+Jw5/kAHX888nyvn42U9S8du7Scaz0SPhhFOy3+u2,iv:76j5AC8wrHEd0nJ1TaSpeuVE9Q+5KjO6LJGT67RNWgo=,tag:ubSmqZD/0/mloyzS+j8moA==,type:str]
    #ENC[AES256_GCM,data:fiVBGZg6RUrmXxKMauE=,iv:DT2y847OzZXOCX0cNCwvya6RF+JBUJnCJygwbhhBF7w=,tag:Av8qIEucGEW5rxDUU2jzjg==,type:comment]
    PODNET: ENC[AES256_GCM,data:qDQOOROk6D3NAqqpkw==,iv:jCAwd6JzzZtubPq6IZ8WheqIM9lS28Gw0YPeqggUjBU=,tag:EBwgZJoIL3UxGoYdsvdAFQ==,type:str]
    SVCNET: ENC[AES256_GCM,data:9ZaBOdkRlyB78Y/HaA==,iv:+dYqNuk3YdlUZ49aq6PTUbHZhxu1Jbn/TFv5Dl0gYsI=,tag:HrzN/vFYPveHhIPwusI3ww==,type:str]
    #ENC[AES256_GCM,data:srAHq9hV65oszjvEbIv5wpafYwBdD0IvCyM=,iv:0CBSFSrBs2DuaflK48LYpJmkfFGl8ggjrdbTy460DN0=,tag:7l2XOWpkPlMNEQztFNAA2Q==,type:comment]
    BASE_DOMAIN: ENC[AES256_GCM,data:sX853HshYliwgFxwwvx/ZQ==,iv:YSsSnHolRxjOQDI9/OiloUln4uYtpoZNczhCgOQ/Qeg=,tag:PEqtykdD5RN4vwDfbvaDWw==,type:str]
    #ENC[AES256_GCM,data:Q+bPjrQpJhA=,iv:frFBLbiNve+KihIx7dZOxc6Lm49ho2bAnnTELMFY7e0=,tag:dtYwdcDFMzFH3NrbbLQ9Ww==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:wimLM4ofVI8l7RP8l/MB,iv:JgmIQPIIHXL3aQvn4S7+QeMHicl8Q+NznHurEHLPOUc=,tag:HnZpvMNBlK9EyxMsF+4OLQ==,type:str]
    #ENC[AES256_GCM,data:Q9y3yM67JKHBViWs,iv:N0Ioz1x8yRnVVkeYJjQDzkM2CUekp9aKr9fhdJWS68Y=,tag:DU9U2hxg3ROl8BcjOxiQIw==,type:comment]
    CERTMANAGER_ISSUER: ENC[AES256_GCM,data:sTGyQfo9rRnPkjkvgL98wczYepjVu3h3,iv:7+zX8X2T0Q6DJlxRG7XehLb9dUrAluSRE3GA2uymuN4=,tag:JS4t7DakIyGj8MKRQIBndw==,type:str]
    #ENC[AES256_GCM,data:B/B9duBjjIJiv5sjrkkB0gcWeB4=,iv:tBvrgmsQrZ2VjiObuQ9vzeaAg20J6IBT+oYX8EeQmlg=,tag:McyY0AeXtfWz3L0KNeoFkg==,type:comment]
    STORJ_ACCESS_KEY: ENC[AES256_GCM,data:muSW2lhKY0oRv3RRqd4G1KCuCYe9P99vf8ePlg==,iv:eONMg9PiJ9VpEIbc5pgS+KrHJpMQRvqpQcc2cDdZbQ4=,tag:tRm2CIA2di9eN47mbvv3JA==,type:str]
    STORJ_SECRET_KEY: ENC[AES256_GCM,data:auE5HyFfEEelbl8mVyERFws4/A6ku9Ko834IFBISN73QJq28vNP//QPsKVsY6huWw9dDeZ4=,iv:/lfjFwXkqJqIaOFfc3BCmkpdY+cn3ul+MsOhKVWxMao=,tag:3YJeZ1Rggwfh20Y3DQbKfA==,type:str]
    STORJ_URL: ENC[AES256_GCM,data:AW6oFJgfHYg8w7cQNUtqbsRwjzq+o/8apbol/+Q=,iv:83hMhwiQtxL84KCyTvTnfvVavj/00siQ04G3KT0frxg=,tag:RM89rbqMEaFPXF/lTlxA6w==,type:str]
    STORJ_BUCKET: ENC[AES256_GCM,data:LI9z9ZIZFzQMiDH+,iv:6wnH7x+V03Fh1cjuatFtBRDLNzrTZ6nP9KH2T13nJkM=,tag:9ljNtEFEORdfpdQpZvAfMw==,type:str]
    STORJ_VOLSYNC_ENCRYPTION_KEY: ENC[AES256_GCM,data:kol3B/FkTImHyWT4mU89O/0JnV+xiszH7uX9Stcb,iv:xyQP8AIoyjIvB1ug7X1b0dl26GcAmWbDJCWcTdspT9I=,tag:FoG/MsHDHCRyiC0JFqg0LQ==,type:str]
    #ENC[AES256_GCM,data:Hix4ul/2Z3AwOhVtQdnIhCGyS4/wGU8saX3QSCUoykW3,iv:mr6ELLNNcSOKMw4inbKt5hh8POQ1o4uFGVaEBW3npPc=,tag:1lGNzUCJU7ZjNBYntR8dXg==,type:comment]
    NFS_HOST: ENC[AES256_GCM,data:uf40LIxdXS5xgRlMvyM=,iv:tRDng/7CZlGTkz45SC7O+yURVrYXK9GywQVkbGYqVSU=,tag:3wvBXjHiiBCMIWA7uwYh7g==,type:str]
    #ENC[AES256_GCM,data:IlvMa82QrMXp79vcI/UHveEf,iv:E0ygN1Lkxh0OP+t7+nb16tdbhHUpSY+jBqdjlfMZ9ww=,tag:UZ0W/Z4JnZ1ZdLLsUmz1lA==,type:comment]
    BAHUMA_ABRECHNUNG_PAPERLESS_PASSWORD: ENC[AES256_GCM,data:qsniY5m3i6gj1EE1+SVrH/G/IYXGLBXUKpAGZ7w+gOp05i2lQw4=,iv:0/xrZ5Ug64vsFZkde0u/RFSvp23WuQkXx1D1rhXZ7LE=,tag:DOQzKjTu6x2T2/DPY71TlQ==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:Avc5+A==,iv:dbUkk2bSP0g/vMjAMg/tB5g/dRJLWGK6j9QIWoQXXcU=,tag:n0vq2VCV9xjjo91Ia6O4WQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFOUdXMHQ0Sm92dGV0Rzh5
            RW5ZTEg2ckZ3dmhaS0xJRVJPTHhlV0h0YUFNCkg2cEFrdEV0RUdWYVpuc2tXdith
            TkpzK2RCbDM4NTh3MzNtTUthNW14OVUKLS0tIEgzbEVWb3FWMnQwU1FjTldjUG4r
            TDNWaFBIZFdvbDZmQWRybFZMbzRRVW8KyprTBUtRKlHXCj+Y8sj3H1Eezv41Axkp
            7ItMBpObbqhjO4OLw3xZKEvob9NxPxbwNfXO1ZNePpchpauVi6CbLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-04T09:24:43Z"
    mac: ENC[AES256_GCM,data:SwYURU3nN8qhl/75GYsEbppwmiM5tr3jBicX9jLtsKcF+ATfmdZqiZEoHbI5ibH5T2WuOeIVCUet7bU+Fg7bmhXZ6ZXdMOL9XD/NQx5WsazpStHvTAC6x3eKp40gxRmdG+mvcDLZaVxrD+uldIOYBuk7toxz5eFsREW9TO5/It0=,iv:GUKvVJ4BehFvxeD97rP3joIMrDMUy/F78uP8CpTCGW8=,tag:5/YnQM7/qgqeK52nJ4x65Q==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
