apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:9GO5O6cfQnp9HEDwOExPS1W6FPFV2D897rbPYO9iOQKOLgjkESA/Te3+Z2PDGT5Z3GniALTkWXrb5/OM9+9iCss=,iv:tVEcDR6/nnuEGWibsApo8mmn8oGrLQ1F07zXxLkzLIE=,tag:T1tzVU284fu0Z/HgWw1l5g==,type:comment]
    #ENC[AES256_GCM,data:kDNNy4XaIErMDFVkkBMuVXsMf7WJRYfbCo6Z+AZWRuVnxEl1Pdae9BMZj/A=,iv:i6fHpv5gFVCj727OM7uX2md+4puKR4GdyH9bxS8v7/Y=,tag:tjeculzHOQwZu8DQzEpEWg==,type:comment]
    VIP: ENC[AES256_GCM,data:+tbmLK2yfsUpzVLw6uw=,iv:B6Znm90Sc686QP5MzBxU7vYpaiv15bBotiRNqzYQ3NM=,tag:AFHQIR+VZRuDtT2rEJUeDg==,type:str]
    #ENC[AES256_GCM,data:LmJwfjmTIdKWVMIWvjqdaMKUbQNxzeBmtbY=,iv:ujOZQ4EeVrYOy51VaOJQUdWM+SDFZVdRQ4YO3X96w0M=,tag:bxq1sVY7spIaNmaMChtlkw==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:9BLQCV+C8x0Citmp/c4=,iv:QtZp/FrBVCWIiTRodrpvJzI8UKjCBGSJropxr/j463Q=,tag:EN4l6wLdMwRvqv72KQ0BvA==,type:str]
    #ENC[AES256_GCM,data:FLY3F7s86pAyrhaIUjYbFv8sbBEsQ3F+kOMK6cTTLxrnfw==,iv:IgB2/FYOteOz72q1br6/D6k2bIFbRp50IfGDjpW6voE=,tag:Us1GdL0Um8BhBOEkudvgyw==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:lJjth4szWBAG74awfA==,iv:+gvPNeTjCXqGfZnFo8yl28iB0x2CEXYBye5+i9zjh5Y=,tag:NfqeWyGoU+dmGlLfHNzKRA==,type:str]
    #ENC[AES256_GCM,data:KuYUZZ0AkagcMAr9uv/KI34AkKmCYt5NdUAGiHaHSdEEw3h95FxTBYEc1MmjtpU=,iv:EHSoKBwbqQ0sxFv4rfZjFe4loKxg1i+nlC++tpBpdDw=,tag:y1mqjSS6/GLMdZDpZoFGfQ==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:sHDluIkZpewh2Mj9GCFKVjbjfLjvd+8HTyJyALAwDA==,iv:9loE8aiBANmSyyQ+vBizVchZ0rnEEhfBZ5rThg67IhI=,tag:eo5UnVsEMHUUeCmMKkd3NA==,type:str]
    #ENC[AES256_GCM,data:rzyIq4CEJsiwWrSCa8+BPFUDVbIkdjf0rlg/rVby0r1vb5DKDT7Aln2XEhBLjPWsT+vC0CxQHooKBzgD3d2kZiA4Il6IBE5DB5v3Cd+v5lY=,iv:Lt4tgwy6juuq4gMsL7w2uHjqqlNsU6AW2SEyrkVL1TY=,tag:ln2Nc6s8WfcYXVOjE4P93A==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:vYJ7MEcmZF1moc4emJpw,iv:0Xrnnxd2hQeYLBhlyqRt11Sd37aX7ve6dYcFs6mHXqQ=,tag:mNQbUjOXYUC/ZJtkFGj3tA==,type:str]
    #ENC[AES256_GCM,data:epUagPuLOOXb5MGqw7Nqr5/zjSjOhZShcLi17hOQ3c5UaTJqmejKK8Wg/WBZUfWdUme93ar5tCc=,iv:kFIqMWshAxylGdMQda9ck4I/QiDznDXw0Hr2c5FPdCE=,tag:jDHv6UshR1abhnNLzg0qhA==,type:comment]
    #ENC[AES256_GCM,data:KxEkFnFvI0QtJlhDXe6ebCR8mjZgA0ONpA==,iv:IwfZt/9RDsd3TlwbmG7PAotMYUN9ulg11zpWvbXTWQw=,tag:a9YcXcNhTizYTZfo2Xg4Dw==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:93kjQYICyxWgXIXM7ZT0S7EbCatUuPrIFZVG5zmAIxwps4rOp+/4,iv:wOU4KWieFSWOBdlhUJBACAS6KTAP0+/n0HbPFIEf7fo=,tag:S4kBiYCtnYs2NbkMADr1aQ==,type:str]
    #ENC[AES256_GCM,data:++euVvjsEexlDblwxFAe3g6kKZDF2EmH4BPP+4XfVdnzMAb9QSXMjlkJIDYmlp7JqI+tBzetP2FTMNrCewDd0UanmefqSAw=,iv:6CPFW0hH8X0ppwvbmE04P0DwsUmGDEHEQCp6heTsuWQ=,tag:ESfbvBRFP4Bgy+lIIgPtSQ==,type:comment]
    #ENC[AES256_GCM,data:iOaQa8CufXpJXGRdGNOC2CB3bZwE/vUHqi9a/FKpF9SZuV70hv8VHVxF2Vvbs9rdJqQDt+mA,iv:9ia8WfAchb1mVx6+pDSG5GQpd2t0Mm6V8pogzd6TC/w=,tag:2q8o2mNL1G6TWuWLWuqiNw==,type:comment]
    DOCKERHUB_USER: ENC[AES256_GCM,data:lOnwO/U05r0=,iv:TElSCMun75BqtX7bJpWWHkOOCnL5287XQCoHNd4sy3Q=,tag:tLo3gFds64WiRE8OHlN6dw==,type:str]
    DOCKERHUB_PASSWORD: ENC[AES256_GCM,data:0BYxRzxrKJdbuklIT7GzyWcnpW662mhYAC6bCeBKnV68eBya,iv:kqu4aFY80lJur7smyhi11NG0X949MTzaLyE+RfOkm+M=,tag:76QJr8n21u4B+eXl/M7V7g==,type:str]
    #ENC[AES256_GCM,data:b9RuhyvM07YJF+CP528=,iv:BtOyTawDy44k7w4QWRyrV0qxNf3sZ4LNaXvx5zRg9qA=,tag:SPvwujMdOxLEEMz4B1ztaQ==,type:comment]
    PODNET: ENC[AES256_GCM,data:4hbLXIgAilxp5GuO0A==,iv:2ztRDm5GLMq7DVJfBGvlLWQaE15S3L7DBllZn+k1no8=,tag:4cp62qOlOQFhUuXC87F1Og==,type:str]
    SVCNET: ENC[AES256_GCM,data:YEF4YZPDWmeNFwURTQ==,iv:wapw+cCPCtrfbd8QR4pyhJuGA2DeosMojcOL6eCO9Rg=,tag:WuA6xuFk1dyv41EFFlQ6bA==,type:str]
    #ENC[AES256_GCM,data:L60TgnPq1h0IZvAykeyNy0fFe1LZ7BkLO0M=,iv:zEZGkojKz11FIZq93NhjurFhojPHMJg2W2tajpJGc4s=,tag:60l7mBv/PemUYlXDx1Fctw==,type:comment]
    BASE_DOMAIN: ENC[AES256_GCM,data:Rh7CUKtPsAKwza6OeuoA6Q==,iv:kg3VyrBjJ7Bcwqa8RpQZRh9cguPK5criEaDWSURu8sE=,tag:qld0OpvfZE3DE0VpX18PdQ==,type:str]
    #ENC[AES256_GCM,data:2noHpU7qo0A=,iv:d++HhfxV/zUR70K41a/YCAqdojfwVba4CWu57Ox9dRw=,tag:W5xwlV+3v0qlK9H5kWqR+A==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:Op8YLXyoEB9L9m0DzWUb,iv:nQZZSo6+hDYTckTIaUR94NCtIuGgZStiUmHb1dKaA9s=,tag:p2bPw0xG8Irh/ysZ/5gCcA==,type:str]
    #ENC[AES256_GCM,data:ueJeeN1hRt/riMZy,iv:ttF6z8OGfQIiBZzF/v3x0+SXQohjczowljKQINevl4g=,tag:T40txkJkBCVAk8FgzZYAsQ==,type:comment]
    CERTMANAGER_ISSUER: ENC[AES256_GCM,data:vd8ydJ186HQDKMN2Zlm1uNbd+KECnOvP,iv:GXGSU3yRIJZakuDrEBHaJsWFymkSjyZH3mbe8n/6P10=,tag:AESV/RKcgVM0DqWlmNUhiQ==,type:str]
    #ENC[AES256_GCM,data:0XOUHTPIEROUrc3U7v9zG9MbT6o=,iv:85RZPzYfdh0vFV2t22q/G204tkj8n+QnYIwbUvlXPQU=,tag:rLd0AZnZ73zbwbTm7D7UWQ==,type:comment]
    STORJ_ACCESS_KEY: ENC[AES256_GCM,data:Tj58zmH0Rwat/485WGyfKCiNGH5LPbP1i2ElLg==,iv:7JXXNU3hOfUUREJrn6u3Yp9srdUJzpf5IUMeKeDXXds=,tag:vAzWcRy2wgnuIM6wheJOsQ==,type:str]
    STORJ_SECRET_KEY: ENC[AES256_GCM,data:TujdLe3rg0xSnF40uTVQDMzH8TJxtCsKkMwsbCYfi2D4H1u3qJdi8z35HPR5TxCxK2lVvlY=,iv:PeYEERf37hVvjgpCHmbXy+a+XHdaSwY3z1SjqKuDjfU=,tag:Z6TUarMoRs95NlgiCZz1Tw==,type:str]
    STORJ_URL: ENC[AES256_GCM,data:SDVCygj8MoqGaF11ZJrrnHSQe/JyVvY8F/s8TTU=,iv:yJgPlJTh+3OdNKU7fAzEvGKd9SVo56Q9bAaJzybFonI=,tag:6uKNGQe3ItTtYH2lpq5Tgg==,type:str]
    STORJ_BUCKET: ENC[AES256_GCM,data:XTkN0jVZPNoPnAqf,iv:QvpYFkcnuylKMJ1Rkd/ouY1PDE9BYn04s36T3PPAxEo=,tag:SeE94hdWfJXl4wouql2CxQ==,type:str]
    STORJ_VOLSYNC_ENCRYPTION_KEY: ENC[AES256_GCM,data:A4cAyVTwFJLt+tQ21Go9poJ1RXgvmd1P2d1nT89x,iv:lix1qu+8uqarh6jJWBWBrNE0Gy/WJMdkobPFKrpgW+E=,tag:01AewPgWpZf+8Jz2PhvVLg==,type:str]
    #ENC[AES256_GCM,data:MFaulkJOp3HZ26cRGLkQX3UK/aYlKh2bNTSVo8elPCte,iv:cQnRjK6lEZH1aSQ94pJxm9vRQTMO0BPDoH9SWenFXPQ=,tag:KWeaMYxguSvAnEXPA0xhHQ==,type:comment]
    NFS_HOST: ENC[AES256_GCM,data:/f4QVjfu6o1Jm80my8k=,iv:zIMuneaeTqfmCcXj+u38g5pulvpeIcrKGUgbvvZH36s=,tag:b0GaTztBzbpUEL9yVveDjg==,type:str]
    #ENC[AES256_GCM,data:sSWIvTc+x+6/6YzhsHTg2itp,iv:trVcSmhDW5ZrBY9ZXJcMoFIgqFWtDdGz/AbR9qP+AyI=,tag:hSpievatkcFID1qABr8NkQ==,type:comment]
    BAHUMA_ABRECHNUNG_PAPERLESS_PASSWORD: ENC[AES256_GCM,data:bzx8Rr/tbmefBGUcNAR8qvBLShknjQc7OWRXlaEmjb1OQyF2Iqk=,iv:6FRdp7nOSfoThym0EnWr7O7yPAo9j609NoMRXj6/0OM=,tag:gNZj8caGRykvdyp3CvPP4Q==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:BSFwJw==,iv:IAHOhGbdk0rwWzVyq6VnrsN5eSUbYGQxUuCpuisyqGk=,tag:pCjGM23YfT2BNzLMtkN0SA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwOHJsdlZmTlNINVd0ZnZW
            RUdoR1diVzFiTXdOY1dZNVZuMTd4QVZFSVhVCjNzSEY2SW5ZMy9nVEtaWTFyQm1q
            RmZ2RHBpMzVLclNSK2JORzlLVlU5V0EKLS0tIFJoK1BieUZCWUkwMXhnTVpqRUJB
            cldaS2xXYXh1M0ZvcVVMTTRWU1doaXMKOwAnjsJGrVYe1YyQgRli+QXXPfRHMBmC
            DkJ1n8+Ys1Cfb9YttadWntkdoKkP1fukrdsNWLxUOLixJDi+jqeKsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-04T09:40:21Z"
    mac: ENC[AES256_GCM,data:0gTj5JBrU8XFc7dcqPl+2ePIgLPq+0TPVof+F1JNdlvuxlwHZQ9vAdAYvz/Wv+1eL2xeJJMkcXJhD5RSuqTHKXmc76siwDolGQShoH7+4PxQ83UxqZ6DdIsHoqnChJADMbEWG93KMTAwSqUcir5JDhsdYyoAwW5EHlCq/0qfAfc=,iv:qqOlYQpzc0u7omBcV/+VzjfxXBZkS+AsWqkkT7sLsJ8=,tag:wAmUKHdEMTV0c08U3pJPsg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
