apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:KGxdhZspn2fc8nb540oa8OfBaDYj//8ky1D0JNug32xD7uxp9j7l/RxE83qP/A19t9VzDrnDz6hpsVVZHL/0yWzp+PcmM6fd1bbp322yZziEryWdP5+3apwIMsRNGLPzsvPCFs3iQDu0MBLKV978/6Ur4oOBT+0i2640cPGsLkCuERfr6dWXT5F+nw60om4mOWqXeWG1UvxSN4fecZD7gVPDqrKygQ77UluPT2SrIW1kkyA1G19jf06NAAPY58fx8dpJc2iB9wxmZLkWxGWHF68TgvieZowa16KIDp3tlExTDNwItWKNg9TCG+y6mPGHP4uOajc/gO6fYbNhuboGHK0CsQscshibTpt73kegcSlHArQDKWuKFu39rG8TSr93,iv:pNp0E2VnhaAWaRnliJhkyDxqoWPd4kCGg73B1pROAdE=,tag:m6TF2J7m++psBr6dzYcPcQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:lRyhmGB+wwEbCSoiwbWocztj6Kh3hqH293MgWSa3RMC3nF+Y3Nqad6WEgk9LEdfW5qYGo2X6z2gC2vPhBT0EUXPfkdzhuR7ftGih3hB/PenHDVb8+sAPqZw0KuzLY1L2Ib55+RqKdi/LVobnKuqkqbLAV+xw3pzC3Ik0W9aRTscUnzhAqail/IWu/cNqPVe9m9Pv3BPPaXiya/Sb0B7AYh9fcri5u8CFCbpcpNpIZQFT4gHEYLnM9F/xGCCnVw2ceZlhpeZu3HRyErRNcg==,iv:XJlYC8qo5NOwVOocP6b8sMqXNdMMsNDC8GIkvFgQjpk=,tag:lbC28EstLKXg5eDlqdhr/A==,type:str]
    known_hosts: ENC[AES256_GCM,data:x4H7xqywBqwQMY7KJ3hH3ONn5WU0s8zMlxUypwZJ+wgdjW1j7a97H1m/URZGsGgTMF+10NP9M6LZph7AkUqNkaqIWz3cvn4DqX8/sg5xVjLP6otkYFfrt6aUSdyDx0k4+i6qQk3cNRy0RbJNp8gg59qbG36kBOFJRmENg60opgB7ThA+2rEnQUhICTAIuXVM3G7BCl4NJuzzIJW3DEVa9XbgWKtEySEU4zsl,iv:bMhYJKs+6cW3GYWNZjx6CWsbwtR635n2vtJS72vBMRE=,tag:ZTEzbklQRKqm/JtH5Ofjug==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpd2QxM1dNQnNlUmpYVFU4
            a05EajQ5M0dFZ0ZvZjhKRS9OemxRcDhnWERRCkhZMDFQajR2YzJVR2d2SWJoZTdz
            RnM1RDQwVkhFSVRzZ3N2NjFoRjdLbEkKLS0tIDVvbWdXZE5GUVJGMWZDeFZwWXhN
            RHlNcEVPM043Q1Y2aForc2h6SEEyKzAKFezyMmQioMvCFVrtIkeM9SBTaQywTV8W
            41yrTp7rOno+d4c/4bvhrayB1lN7lYiNbkntVjX3Ct5YPrQVm0jr1g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-06-08T19:47:54Z"
    mac: ENC[AES256_GCM,data:I3AQTowxV4IzqcmCIHD0EKFY/4iZtBHHhr4guUJAwP8ot+dNxG8brblBkLqUie8CzjgeFmx2lnHMUPe2HdTVPIScKJfAcEevivt8gXcSotDDAt9xQFlFS61LTlyrpx5n9TpkkZIc5LpTmCpE9FFuMJN9f5mXoqOGu75mu6W1f/s=,iv:gg3OGmiCazRpTKLLJMn17AI2HdTtzvA+F+G8DA5s+fw=,tag:/8/NAwcFdc/0gLxE6D3Tag==,type:str]
    shamir_threshold: 3
    version: 3.13.1
