apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:4QxxMcTOuJk2v89s4OfQSqMF73YdPAV+hkNDBbYh1rilpY/e0f7Ewp3IwClzDcA+1Lm7xhbR7HQgPiJ6xmpTa299n340zY3dYKXFqV/4cEV1T6Xj55AnqhlGwcbHU7kYm+Q++ZXO/eYI0IrFu96INa5fDtbL/m856EsKN/mjSQlKJDkjV6JywENFXZcBCiLhZQeos0pwoYw0V4p86lzA4rgEKlRNMH3xVpznmST2dCXqVKpykzg2YpEH01eW0H22MKxDjeXpvsdGDvMHPk7Bd3RjtPwUFSo4piMNq5Qq4EIfT2I7AW+sP4f+5jJBliswdRB07m1A3ZPKbQFYDrC3rEINHWYZtC6z5Kr5e/SKNeCQzXfN+kyozgp2TtZRT/+U,iv:RbJMadAqAgneqzHrbL2jNEkOhtM5S1Gi/KehLKqj0sc=,tag:S4N2p89xEATN4SxnBewVpg==,type:str]
    identity.pub: ENC[AES256_GCM,data:D2XpIbi9Ub+nWePNkiyLBHXnJ43SyPapBAMFhBhnu9TJSiJzoLn15yQjxJk9homsGl19PlzOYr97aKcwyBvBC8LMiI5ZZ7YF4Z7u7ba8rxhpfXuuNbuq6FjifsEPFSkTW3PtH0WmRomG3zr3fWkaj9+y6RLUjdD/lWFfal3f0I7U57DO86pc/duL9luD7no/uiCBwj+FVh622dUEbAdI6wctANm0SuFDhkedlvdUjAagsEbsfP+RDFpdRE01ACbmZlktZiRs0L5ihANYpQ==,iv:yHvWAy9X6EB2B4RN4fLNudIq8mNDvO3kVhrTR8ts1vQ=,tag:etkvKH0qWQA2GhLY3MPfXA==,type:str]
    known_hosts: ENC[AES256_GCM,data:w7J83JcWxNch4soREH8L5gSIXT34MHtyXB1nf4qaOZf3Z1cv5tfH6njrmHnrqJkmEMbI+zbLIkEWGjT3hytiosYwBZtjtQ70POJbWIf3bYNK5r7i4QamBwuzG58dWv14UhHhTckUQowGF+YXC9FGS6w07jil+SUJnRihUyKNl0qywBKM9MtreUKK5aZ6sdaYrKyFA6EIomJFBYGUpFO4qjnuDl74UxayMe0L,iv:dslG1VEBo9qfDcClmJ9Bq2exruGd8kaYN5mhPswK6pw=,tag:06K0VkKmGOAh/IdbHbOMVQ==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtVTdNL2FWd2J4dFFEMDR2
            OTFFa2tVeWtYYTJWOG0rczJBVk1vZDFORGtJCk1peTFtcjNYZlAxdkhQVWVSaHcy
            dlBlT1hFM3hDK0NlZjRidEcwRkRBNGMKLS0tIGlYcTN3RWZVUGtBOWFDNFVXbklC
            b2VhZG9BK1puVXFDUC9lbGc5dW1PTkkKi2sHTXqHiRMK37/uo+mzalsIm3nd3cr1
            +hMjZced214cWUNRD7KPcFGZXRVBD0Dyu/UCvs69dX8r5A1FOVNKRQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-06-08T22:34:01Z"
    mac: ENC[AES256_GCM,data:GFMsF13z6dBHKo8wibyvnh8lhp+P7VcTekv5w42kfi045HyJqM66fOmGHKA0uNvnRcGOuDKEjUODmhJvz/RkgHEWP8VGm+Ps6TUCVpmSjEbLV0zIT8/+xW0cDmul03wk+Klhhp/+xQSl4ZO2ZzkHm4TNiOZeN9gAG1xSrrn8GTE=,iv:ZfSCGKFMIRuGu+P4LVl8hbmzoMjh5ab3mnzl8IWylbs=,tag:Vw7UE9v+ZepUSOXYCBKDyA==,type:str]
    shamir_threshold: 3
    version: 3.13.1
