apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:FnYrwh2qFi/ZYEBgrSdEyLsY1embHGjrPSA7g+8Fk9hMC+dqD9fDfBhBY1ywTJJtapABrp9P3hGNWzmpvMQpeKmW1DVloXE6sgrJGhJkZeE/Nr0HFCBTZpdL0XdNrc5ZgyQ9/NQZ1KwCzdg4oAPv/QwQn+uwWxhcoz41pylm6JkO/BCa28bBHcZjhEu0VwQ75DBQ7P16bEWE+HfCvSsQ3yMLYhnkP7DlfRUhM9ahr1K77itA4ZfcgJvApB+uRVRUVqzmZqIp2g1+y4w44OnGq/FIvZeTrRcI8qc6JvEYnvq1Q0L2lnOFH7ZjdN/DakL2xiSad6jipIQ1A3LPHCwf8N3XYwj3Repv7fttiVnXSKoOERSDOlcHyuOd4C9DZV+b,iv:GWBywlOfuA7bcVQ5wVO8jo4xGp7Fk3dMm4HyknKe/1o=,tag:OEAokSqbeHSkZPccxmiW4Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:1d/jY4sAIS/nknrel0mYUKsIu6ci9sK1eOXnR/8B8KOmIZcR+kPgTX7GyMaAKpejm5kJbMgeNdBMclEKYEInJ1FPue0Jch/ywRgn6+6NHqpahIOjhXjGXPR/cqPOMiN+mPsMOdmkuRwMcjOWsnAn79YG4HdeqY8rjiBQ/VVavN4MjBdDAMVo5HWeE6KJpG7sicaqwt3tFxzVXN67I5Rzl4r3PZqtCu9OBNv3qdP+hCwD2kqEeUtya8VtMXQp1GdqhKbuG1WTR0Utp0iwhA==,iv:fIzZzX9tVBwG+j/OTDtrvtomFUzpYyqaYvZcLoca7Yc=,tag:saDFaxDnVCiWtsC5CAQizQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:ZJ6fk0pUbyvet/EQ7xZMc+B6s52zheXyjs5Ya/ajCUu4u/a9/50Sth+P7OIM6LJIx8BQeyP3H45R0a7hDMOQWe7lPIYlZ9h7YrdYvoLPQWynwEHWh69JyIQnRFkSC/2vRCf3eaWuNDCOMy8SD4VEkd3uMxAr8yXj+8oRK/rbNPjjgoZTJM3RrvPEkRXxyL5TO/WOG6UGIzcFnjrTYjBw2anDFehyNlHISsSi,iv:1qgybmIQEiJ9IyPsGVLowSS+KsWnUngEch2uMSpabYY=,tag:ZhKDUSQyX9VLvzscEqJygw==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoZGN4Y2pSUzNQZVVxN0h0
            L1I2ZDRaRjRMYVExYVZHanQ1bGYvakZZM2pVClBJaTVwRUtzMXE1SWREM1lMb0Fr
            U0djam1kNmtZQk5rbnd1YURsR2srSU0KLS0tIEUxRFN0RTB6VGZRa2ZXMXdzVXhQ
            VUFFQ3V0ekVsYyswNDAvYWQyNTMydk0KIRAbbev3j2EYlNniYxSKv5gES1vFIGAS
            oerLrY+YHtEemHg8aXVnASpirxE3ZryxAEPWayZWVLYJuVBRduN/+w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-07-18T22:20:29Z"
    mac: ENC[AES256_GCM,data:3vvDjAJegmiwhPznP26DKpa/AT5D/5MuWW7hFYzFhtKH0quspaXimVdnrvam5L2xlix9PhObqSc/lxw9ytXI0GOi2CkXum2mEI6E4jU/aOqFW5rX3B3HAhBkfoJlAwcWL09LUwA1M/Z3EiQjKgpZOKsMdWR0eZcCNqaZSEcoJ54=,iv:TTIpjD8QXu6bbHYcmuPuEi01G2yRfy23jGzqqnXU98E=,tag:0xce9NvhAtx+4ZpzTiFU7A==,type:str]
    shamir_threshold: 3
    version: 3.13.1
