apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bahuma-abrechnung
  namespace: bahuma-abrechnung
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 15.16.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  releaseName: bahuma-abrechnung
  values:
    TZ: Europe/Berlin
    image:
      pullPolicy: Always
      repository: ghcr.io/bahuma20/bahuma-abrechnung
      tag: "1.3.0"
    securityContext:
      container:
        UMASK: "0022"
        readOnlyRootFilesystem: false
        runAsGroup: 0
        runAsNonRoot: false
        runAsUser: 0
    service:
      main:
        ports:
          main:
            port: 80
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: bahuma-abrechnung.${BASE_DOMAIN}
        integrations:
          certManager:
            enabled: true
            certificateIssuer: ${CERTMANAGER_ISSUER}
          homepage:
            enabled: true
            group: Sonstiges
            icon: "mdi-receipt-text-outline-#5bb66f"
            name: "Bahuma Abrechnung"
            description: "Erstellung einer Excel-Übersicht für die Steuer aus den Rechnungen in Paperless"
            widget:
              enabled: false
    resources: { }
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                CUSTOM_FIELD_BETRAG: "5"
                CUSTOM_FIELD_RECHNUNGSNUMMER_EINGANGSRECHNUNG: "3"
                CUSTOM_FIELD_RECHNUNGSNUMMER_AUSGANGSRECHNUNG: "6"
                DOCUMENT_TYPE_AUSGANGSRECHNUNG: "26"
                DOCUMENT_TYPE_EINGANGSRECHNUNG: "25"
                PAPERLESS_URL: https://dok.base.noitl.space
                PAPERLESS_TOKEN: ${BAHUMA_ABRECHNUNG_PAPERLESS_TOKEN}
                EXCLUDED_TAGS: "1"
