apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bahuma-abrechnung
  namespace: bahuma-abrechnung
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 14.2.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  releaseName: bahuma-abrechnung
  values:
    TZ: Europe/Berlin
    securityContext:
      container:
        UMASK: "0022"
        readOnlyRootFilesystem: false
        runAsGroup: 0
        runAsNonRoot: false
        runAsUser: 0
    service:
      main:
        ports:
          main:
            port: 9117
    ingress:
      main:
        enabled: true
        hosts:
          - host: bahuma-abrechnung.${BASE_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          certManager:
            enabled: true
            certificateIssuer: ${CERTMANAGER_ISSUER}
          traefik:
            enabled: true
    resources: { }
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                CUSTOM_FIELD_BETRAG: "4"
                CUSTOM_FIELD_RECHNUNGSNUMMER: "3"
                DOCUMENT_TYPE_AUSGANGSRECHNUNG: "26"
                DOCUMENT_TYPE_EINGANGSRECHNUNG: "25"
                PAPERLESS_PASSWORD: ${BAHUMA_ABRECHNUNG_PAPERLESS_PASSWORD}
                PAPERLESS_URL: https://dok.base.noitl.space
                PAPERLESS_USERNAME: bahuma
