apiVersion: v1
kind: Secret
metadata:
    name: hetzner-secret
    namespace: cert-manager
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:rYTGDYUEx2158RVmd16cy7iQHqX1D2s+lfwO4S6GXKK70SJPBCGUQaNbxys=,iv:fA+PWn7ghO277EGPCgpXvyVtrufM720dgJBqrbkhMMQ=,tag:6UXWzjMcDSNlttUlVsqqVQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOMjdJZ25oL0MxL1RKR3Jv
            dFdwcXQ4cGVoZVBGc1lXN0pYNmVtZTQza1ZrCjFORWpIaUNxbm1oNnU4MzdnUm5T
            RVNmendNanR0NUJPMlovTzJpMndITXMKLS0tIFlEQWVhcVM5VzBQU0NvRXdtRnFV
            WkNOMmVpbFh0MXB0a0dHazFUcU5XVzgK1RIhPuU2qQnf1HIKeKhC+++GhIPnuVYo
            UkvfKxx90dYPQX1Xgck0oLsFUMtsv/taDjnZuWwvTXZqVhSJQg+CPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-24T12:44:11Z"
    mac: ENC[AES256_GCM,data:TZAkGHk3+ITUZZy81iAtYZLDt6TPIp95/K7nLbSte+dEnlsFTxjuYJ0/RgdK/yWufYYrlouXzhhBNGmFZDe+yjgZB5I/Y/3pYqTjXf3xMdjTmZ1ZpiA1vNhnbGW5C0CyMRaDYZHzpEWLhaitJL1T5LSOq0MYTJK6Q7ie+h/3DkU=,iv:LmFvT+TbueW/KygJmVyDocwRoy4gH7klRYy4Iw5z0tQ=,tag:JGw+BeFc8tkb+HfQ5m2uuQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
