apiVersion: v1
kind: Secret
metadata:
    name: hetzner-secret
    namespace: cert-manager
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:p3IMpvZdMOJj26afXAf47C6zzkM5QXrxVQ86t9S09/sviObedAY6mOCokLg=,iv:HgnhULQ0LQM8Jk1V6Un4qFWpmBmABgGvTnX79vXm27g=,tag:5pP6WWYoOFSZsFE+t4e8UA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHN2VqQnNjYTVQbTNaaStv
            eGdxMG1rUGVrbUpwTmpJWkdtVHYwanlKckZNCmlUYVh3VWtuNTBBeTJNczlUSWJ6
            cXp5NU11RGUxanMxYzNMOHN1T01yNE0KLS0tIHhtclZWNCtleEh0VnB0TDBSV1lY
            M3lDWURvaXd1ME1Vek1tSWRocTdGTHMKC9UZscxuCTLEPrhyoZtEM8Sl9u6nMbVA
            RJB4KKZHpLXdHJTMP1Kxl6Lk0o6077kpUhnQ2h2ca6WPdkwIEtIzsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-03T23:25:47Z"
    mac: ENC[AES256_GCM,data:7ti/XorebzbmuSB3jDQ4EKnY7hH6wY3QmsLeePKifYpOqULayLXbx6bUB30lSWPi1sGZEya63hh3cingk7VcBSJPuse1sCdBb8SahO/uel/lw1UTXvf5ZKUK+b0rGLicmB9EtjhsXpEFLXhMMLMM803IynnGat2jGGVIr+KxSBs=,iv:0kp2PzBya2vNsrCTKg6HNGdz/fadx7/0lQapBzXokNE=,tag:eIu1mMYOXfpYSXcgsAZPew==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
