apiVersion: v1
kind: Secret
metadata:
    name: hetzner-secret
    namespace: cert-manager
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:QrpKcRDBmuzvFFuDUkxenyRaLtrV9mFVimv8qmRGczUAX2aDul2zD2pSzOo=,iv:CkcBSTuySduEB15fzZ41S7g9wzjZCVTOvXHEQJlSzoY=,tag:s+yvC8nIrMqmKaxif2HQJw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGWkYrd3pVL0oyU3RXdlVB
            Vm1QM1RrVXdpL1c1VklVZXQxM0ZXdjlMOWk0ClR1MzV0ZE9jL1VGMHhZZlNMOWZK
            aklHVXRkVkU0dFN3SU9Ed3hobzNobDgKLS0tIDZYQTJkMzMxbXNJMUxYY2xVT0hr
            dnhCZ2hnTEx0K1BLQnE2WVpvT0JFVUkKGYGv2YBA7czghe/mPeLSJvUrKZwiDu90
            9GCevOMg1z5PFV6BUENdIMHFT0DNHbPgpr5lSZBlCa089PMD7nsKsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-20T11:18:58Z"
    mac: ENC[AES256_GCM,data:6ObhT8vOTFss5oP+/PtsRAx66QIKG12H0dNNeI1OwtWwK/7JPen+3Qvs3QhHxHuQs4Q4rK4oKCCgcDTNXfGdpOiD6f1CLeO+m8qQD1G/lvklYkZQKS+4dQrQo21+iNI6zj2wwoRewZhWKePusoGi7liFbbqu35NNGYRxgBXKVf8=,iv:6B1+YizDYkcNWwYC/IY1Jv1BPD4SlSC6SEKPpShcqJM=,tag:ec8c8SF1CimqiNPLpVWYvg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
