apiVersion: v1
kind: Secret
metadata:
    name: hetzner-secret
    namespace: cert-manager
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:U47xZ53wMmCS/ogoNB0u1e83u5ZY8TnJJ4USCrNj+iOcd9Ny6091oTi73V0=,iv:+AotwfvgUVD7D3Krt7qwfbPpiGNuOI11aN7xUXJ9nRU=,tag:p4ZtmoPV/aLRJLiqSa6bCw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvN1JnVDJwYVdabFhCd3RL
            TjlOaTQ4UXVqN2JiT3NMTmxEeFNmcjBHS0JnCkthblJPWkNuSU9aYzdsNm5tRUlu
            dFR2M2lJYjZ0WkdES2JFTkZWc1ExTkkKLS0tIGV5OXVVdVB6ZFdldUwwZ1E3eU9p
            ZFowVWdJbjNHVlhubTlwYUJuUStBRzQKnVu1Pf8Ck+cboG53YEA8bFNgV5lOUhnw
            qJDj0OAIiJiWJP2WjSpMTVHJlhcRjJmD95xlf50IuA4AFjxOfQ0Ebw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-14T20:24:21Z"
    mac: ENC[AES256_GCM,data:arTwPmHb+H/Tcxlu1vvnEoMOCtcasofqqfQedoen7xRKhrYHp7Ksp6lwspAyd5gFWlj+Zum8BQg2B9i3cdt5CROqu6vOc5Ck5haV2meuR/6fGVFM8dbHVEz7eBP7JH9o0zikoeWlipKcM53vnlQgNjenwlZrAAX5AZvm1FgL/9g=,iv:mGiGpLjrV8K2TtbUgXAaZpR3W8gJScMqMDUJlBUi0U0=,tag:MPLfqIFllUEuMPnSiaX8nw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
