apiVersion: v1
kind: Secret
metadata:
    name: hetzner-secret
    namespace: cert-manager
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:7DMMPZY3M740OXLGcFkHANOA4/yhbvq2v/VYCiohzlqhIg13ENxlSrtZ1x4=,iv:PlLUlK55kcFb16QdhnaGkbVhRiKTma7v9Q3jG9+mG1Y=,tag:Am2KJOhL6U9VwBZF4CEvQQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTV25zRFpORnFPWTdyL0xu
            NnRtL3djc0dUc0hxOFFkWTBJQ2dxNmoyQlFvCnd5c3ZXQmpmRWxBRXdsU3BKRDVD
            a0xKeDZwb1JpOXJQMXhZbW12Z2dWK1UKLS0tIHpoQmcwVmMzeXozS0tMMmp3UWpP
            bnlERDBqSW1pdEk4ekRPemhRdEtyTEUKuQnmXrHAw4m31lFglLkHPZCz2aQ3cyVS
            AtK1/gAcQXwZX2ldFF/rdhqYTcPhsh3g24/fZW7Q5crAiQ/W2mPWWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-06T12:34:50Z"
    mac: ENC[AES256_GCM,data:uHGkQweByOQ9+jVEmlS+iq31EbVZ9cJLC43Cx6Yxhi9DoShOQkZjyCq8wD4Vhbjrre+w5pzlqkt+riEJ9P4PPA3d8tiPCy5/hsSHaNbeCyZ1qjjQx9qjPjyrTHA6SdqewuCvY4AAFzIe2ZhmO1pniDwln+y4YlsBr8xd5iWFwqk=,iv:PH7R1B/Qb2sERqC/O4GBtvmkf9dya71TsYDlCKm+5Zw=,tag:yk4BIbwa03aJL0PJcI46Vw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
