apiVersion: v1
kind: Secret
metadata:
    name: hetzner-secret
    namespace: cert-manager
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:Q5oHLeMIAZsOLfnISVK1P60x5JoMBL8qxFsFmI+4vk0HKb1uyUcHdQ4SdM4=,iv:dAm/g/wV3B3MXGdkGgo2Ol5HxZQO7Ktjg/mD6W+bYRU=,tag:OrbvyTziavSlhtmtf4fxyw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxTEVCdzRRNEpqcFR0YlZ5
            OFJhWkdTWTU5dkFKSGFBanZleUhRa2p1ZG00ClNFeVBSckJOaElYRndYTWd6Y2xl
            RU5NK3kzZVR1QzNUcUxYRWZiQUpmZDAKLS0tIHZoNW5walFDOGQ2R3FlSVQwR3lo
            RGNwdmZ4RkFOd0k4M0dxR2JQM1g0aU0KWryFXHSrexFa8bYGazfhZvxb+wpVnhVR
            KtsjHKrA5Pudl2xdHAwcQ6z+32yZH1yXuD/iQSCmpk+6UD/6G/OQjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-24T13:20:40Z"
    mac: ENC[AES256_GCM,data:tDGLpC12PjaBkAq8X5yJ+NSfBq0U/riwc7mQuL65imaLYcKH2XE9HNFPAPAN/bLyyQd4wvXCugApmaHwKFezn7S2SNlSOstA7EnxRx01R+Jia1tcveLUBLqaCVr5hJ+UgthMsD/gjVLJmxN4I22rzlDzrGi0G6UtbENnedlfL4o=,iv:MWQwxMSfOA9ccWaefFw+HUFRT3SWspFagn9XUCEqO8Q=,tag:isFj1TitLkBv+btqrQLbWQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
