apiVersion: v1
kind: Secret
metadata:
    name: hetzner-secret
    namespace: cert-manager
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:xX8JkjctUtaakTIQIHbEt8132fd2Ecq27WRTYby+t8s7ShFv+jN50nE2qIY=,iv:jLnUiInC/whAX9R5b+HDmNEZmaeh/WN8nwynAdXdPPc=,tag:D0cYOQDDqdTA7mywH2leWg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBESy9JZmU5a0F6VW9TakhG
            N1F3dlRnbGY4aGhPQXJqRnJYcFNvRUxySHdzCkJqVkgwcHEwWll4YVBjbUZ0NnF1
            VDZVYndwQVVhTGNVSzdmQWpxS3hvUzgKLS0tIFpwTlV0dEM1M3NHd0VpcjFJcWZp
            MnlIWHJxWlMwallldDdKbGhWUnMrekEKm1VF9JyDW88qPfMMcqRIfDGwog32NPxZ
            JSeVntohoKHITy8IkGCOQgX7+sE7iqsBj3WFZHWSz4tbWjSYWPWHxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-18T18:24:28Z"
    mac: ENC[AES256_GCM,data:Te4Wd26ahS0ucOQqOe6vpMt71U6sR47wW+QnLpvTOTzJ/ippmgQv9XnY9WxphYsrVP9tygNqqdRiY8BpsRxoopjNB7UkKpCVXsFm8e9r8gnnuokAa8cWwnQ7d1Crto/DO8ydUOM3bssUdvnbOfA7gCjEaixQdKxR+Lg0+/9leJs=,iv:U53rNJollgXdnr3iX3J+i/AIHb+QFnVAxiGZ0/wd7+E=,tag:zDDQEKT4sb28Y7LHxMxW5w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
