apiVersion: v1
kind: Secret
metadata:
    name: hetzner-secret
    namespace: cert-manager
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:ScS+BsjPrGkh1eX4Imbjg37zYJjfvqunJFcNQNLWMz228+tMBpkmvv6Zzbs=,iv:/4sSuu2HCiH9HwEIWXjHgYGrdYmzOY9SlwlJDo6EbiY=,tag:yTon/oGptItlrIDD55Kj/A==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBycWphaXNKb2s4cFZ2VmZz
            WEUrbWZPWk5LUk5ud0dZVlVXWXJxSFo4bWhzCkZDc3VaaHNGMDFVa3p3ZHdCajQv
            V3ZVaE1LUUNkZHZrdnRCVWZBcEhia0kKLS0tIEk3RXBoZmxGRmhCbjQ0akZBTTg1
            cnk3MW4zaDZyYms3elh3YlZmaTRISE0KM/c0W8QSQmawNIf+CtrEtnMOYxbjDb8Q
            f9KLq8PlFzb3v1uJtmqwU/u7c2fmy/Cg6sorFH4r8Jzbt6stQdC4kA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-03T22:14:36Z"
    mac: ENC[AES256_GCM,data:EDBYknvH/Qdu3jq8aBmeotA/wDPIIvTsethfgTNuhdwzxPMSQxxsDxkdXGZK/nADPNy8wtmgIYugvIJAWgIGdTEWU1M13hpEkZpRkeLgM8awqqFZZVop/GjInfTO8TeKS+A/nlH4yugVCUThyzxM3T0OPGjVNYPPPB+r5z681+k=,iv:aaMNB85AOqJpqonD3fD7RWax4dusZuJWVj4CsKE967M=,tag:bEJBmymV9HmjyzcvGeMX4g==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
