apiVersion: v1
kind: Secret
metadata:
    name: hetzner-secret
    namespace: cert-manager
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:Zp2x6+d840iL3iSC+NAwpciSUoz1c4kC2RT7PMa87hm7t4oKAE1lvriQj20=,iv:/L99ZNPFp4E6yEiVD6EO5bECjXHbFmO5+vaX82TKcPE=,tag:yxyCXN4BPRtKFepEr3Gfsg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIQnoxZFQxemRVNmxaK3Nn
            S1ppS25XZWM4L1N5SGFTc0thMVM4Nk1GUlI0CjVlM2Ixelg1eGhZbjZYQXdNVUxu
            MlU5VmNkcHRQelM2NlhRTTZidEtLQm8KLS0tIGxqOVlJdU5YVXNKSTlIOUV6T0Ji
            T0ZSSmx2SmFFNm53ZDNOa1hjVkxwVWcKV2DGv8Fz+osk9cflSKXe9ByApQc9e6LI
            i/PP9mx65AIpNFH6tai6S9ma+Cs1XS3I0YJg6OjScmEC6x9y+KV3vQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-25T14:50:57Z"
    mac: ENC[AES256_GCM,data:2Jig7a/7LzhwMghL2M51MmHP9CBE1B4vvamEJtQZJYPVGn/7nadMJ+dJWFUzVuuhK3AsDS2FfBTzMLuk4pwHI7aMAPQvRwJDDs2jEIL0ok/DAT68L8I3ZSYNswX9EasoJYYHXyFro21JdSpHjEcvHcNcHwnRtfQS6LFmaF+pR44=,iv:H83rs7he+wtk3aR3SbdCZxaZYt+jG0ssMPINLLYO0JM=,tag:sfUGNeK3nINu70swRFtGBg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
