apiVersion: v1
kind: Secret
metadata:
    name: hetzner-secret
    namespace: cert-manager
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:h3auUk/r7YGrprcU9eXZlV0xDBL048W3hBzgEQSs5At7tS64ed9k/9ys3O0=,iv:430h/nqSPPg+uxjYYmoubORZtzi1ze/yvSNt0idpWFc=,tag:KlZoPo258knMHjt3gKRsJQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbEsvTFF6TFpNNnMzQkNC
            cWx0cGwycjRSZkY3NS9MYm5LdDBaSFh5WTFBCjZ2OUlVWnJpbHlCM0xjcTJDR2NE
            WGpmakdKQWEyTVAvSmhvUjFPRVh0c0EKLS0tIGpRVWVrMUtJM3lSZEhXTnRDbHNT
            dGtwNXRPVmFJdmJXWW5LbmVLcUNleE0KyJisB/09+1NRpR5O1mJ4T7rlLn183Q1P
            V/YDAPwDvY4IFbqXeVjFuQCtT9A8NvkdXwfBreFS5wv2e8oFvjGing==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-14T10:42:56Z"
    mac: ENC[AES256_GCM,data:ZFpWXZGaEaJjH0Plv5DRhBJC91HBO8IUBF4DLtCwa6I4goU2dU5O8ZZZtgvrDZ7UGX/blFx7ddmDd43SIlZ4MauimZwU7P4p6F5JAjiCKPGmI9Apl9Zwn1aYYkY2/T2VRtKMe9qw06Ux/WoT2uqAKl01c5/jFbUaItIt16ZToxY=,iv:QysQu3/HnDe0cOsltLPbU4po0JLhzdkMVbU5MxdI/ZU=,tag:4SGJYmTIaZMX+4sKNfd7EA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
