apiVersion: v1
kind: Secret
metadata:
    name: hetzner-secret
    namespace: cert-manager
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:89cfhGs59Fr4utlXOWOzIud7APzG1WR9yZbTlfh+cn4JfvskkQsETTof9fA=,iv:8htb/ryVnnuk2avaw9JYrTZA4+ngOtyLaeowdnkZ6xs=,tag:Fqtl5ZlCO9QOvm4eERzSEA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBITG9JNnM0MmtnUzNXOFky
            Z2Nxc3ozbmFBbFJHTXMvVmthYUREZWlRUVVzCm1kMnY1WXpnc1RGWEp2a0FjMVhJ
            VlZjNE1kMFpGU2NQcm1PUm9XcEs2YlEKLS0tIHlqa2psQ1ZaVkpGZEMvVTVYWkNX
            Y0MybkRHU3A5dFkxNyswdkEyam91K2sKVwlX0HOB1/JpOSMSBiMKzHcKiFxw/iQ2
            BrdJVk8hbrlUezBdvx0O5k5jcwTX0dleIQw+IjennEg5/zO1HJDe2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-05T20:56:03Z"
    mac: ENC[AES256_GCM,data:B7rpOxo8sJ1GgYlLkwdfo+vWr4mpnqJFtZWRzx7jTgnuHsDBI5ArKYAceBJ3r96I3N1KRYmR95At+RTknkETWLD67z9KF1kqUyH1bG9LiVIRMPgYo5gxvAm2DSJyvyGOiqdmK08xcCbUjuvfWX+cYQ53W94r8ZQw3LNwx2eDg1c=,iv:ytFwR25VPCakSOVob48DyzrpHM0l3wFeiCXMh+ZaNPc=,tag:W6c1BTmvjTg7mlLk9ihdjQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
