apiVersion: v1
kind: Secret
metadata:
    name: hetzner-secret
    namespace: cert-manager
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:AkQM7GzoeVWRqGudrJWXEjv40Ao5ZSw2wMgnxIbPsi3QSXBl14X0OLJEjko=,iv:91hmPr5POHnfxhsbAoukzX0GC4OuN/pqUIsTy5fimec=,tag:FiICJ+O8hfhNDq3SJcOefQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqWkQ5YVdHV093UEU4Zzh6
            ZU9EUFU0alJFVFdsY2JUWUh3M3hXeTJVSldVClJSWnpQcDB4RTUwMFU1NmtrSVZG
            K3g5aUdzR3FKM0FTZkM4ZWpESStzck0KLS0tIE5MNU9udGwydFpIaW9kTStOaHRD
            YUw2QStzTnc0UG55T0Y0STBsZFllMmcKtTIukR+CcMecZCTk/0skU/68Uz5j6k0v
            ckH+ObbN4L+LbS/CQOnuOP0IR0gggn5XIAcQCPtsUsiOZdVb4ZAffw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-06T23:28:51Z"
    mac: ENC[AES256_GCM,data:eLP2DDAooq65qejhkTkO5Y62PCO7/NeoRVGb2zUMNlQd/vry7suN38I1Cmvlad7kWD1dc7NOIaui1NN4k5grUPw+P2T/XyTANramo5CW73jdtcre0hBOEaC8DJMz50gN2l10koAxtpoP3OmFkeLOtz+jReaGsx0ePG6plxG6Sco=,iv:1K0c2eY0vc0VHySEirCJt10AQ76ka58m63WDGe6BnjM=,tag:Bv0FkjOsVgRbD3Sh5Pu+0Q==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
