apiVersion: v1
kind: Secret
metadata:
    name: hetzner-secret
    namespace: cert-manager
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:I7DCrJxrLdfKSvGmOk9z7Fp16Gg9/AhUW+JfFptYLU8iLGd52mezGCZ3CDg=,iv:8wyC6oe6z4BeoJV4e/q9krbsZQwDI5YNnarqktoIjyc=,tag:1bt+TZNsylw0fc2C4PZc+g==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3T0FFQXJ2alYwWnZQWkRH
            d05BRk9ITEN6alZQb2hJaXVPdHNJZDJrUTBZCjdFUGNZaHR1Y0dId3ZqNUVWZmFi
            aDNkRUc3bVphd1ZwWXFTRXIxNDFPancKLS0tIHhzTWFxWDlDQU1zMXFiWjY3dHVT
            VVgyVHJnbDBUV3pNb2NGbm11ajhmd00KKo6jk7ITKKU+dSAPSobLM16ceMO7Hqat
            Gft7SDd1kXBwRBCe5hXOFzgCnKZXtrsEOGlPxsBxG4vG+i6UfX5CVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-25T14:10:29Z"
    mac: ENC[AES256_GCM,data:mV9YutjeixrcZ8HNU6PqLi9LvnIpOpI11oTI+G3WYx/zvhFBae/3m3iKbF/ol8jac7l5eWGd/tmFmQaNRaNmYgeCJ74mZbQ5ZSThhXYr5GYbnxIW9vVOPqbzBIbRJvRRTBnZ70J/rKwP5QEvJXZc9XAV/Z1YEi+84xro90WyCV8=,iv:08BixSu957x5eLdwcmLeSW+LTeUT6zDF2RVCvs6Trrs=,tag:x/1DtniB7z3NDyBDJoxE5w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
