apiVersion: v1
kind: Secret
metadata:
    name: hetzner-secret
    namespace: cert-manager
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:UU6mGoBGVr9TpQS4VLA5Hv15bWQyZJV64wGOeaq8+DNmgsMbMcoVbphL/x4=,iv:oaJC9O65xxeT3B6DBsooQc0O3yrnGPl6ZH3ET0J0xco=,tag:n/n00OnjyiGjZuOHNLuyNQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWG02YmdiNG9GWjBGSVNo
            UEpoTDZ2M2h2d2gwczRabWd2b3h5WUNiTUFrCnlFRjhsU0xIQ1FBSm1JSUsraWU3
            UXV4VnNXZ1B6cUdJOGpIRjRPSDhtVGcKLS0tIFZNSzRoWkp5cUdHLzVWQWdUVUZI
            SlIzTGxRUGJGTE94S3kzSjJpbEdRbXcKqvUKI4c1VrD9BFccwkEon+dQDq90RhYA
            G80EZPn3ydsrDsowuESXAB6iu4YJQXZKOULv7kAcd7Tv327HjjUCVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-03T23:03:08Z"
    mac: ENC[AES256_GCM,data:Ijg3jdJRWxoCmNxTrn07YrHe55gKpi1zTgYyUJDH7HMmL2sVfNoqLXmBpWQkH896htOruXqSAxg6mMXWWGxPSXEoFL+OYzaU1spFDLP7Q9fIbjMKzdMObO5wpNdwvp55BCsnV2sU2jJEr6dLJ79Zqf20Ri62CQumPkCSzyatIKA=,iv:eSDsDUXkBZTd5XiRceH6YcS974PWAwtNRoRz4VdO8yQ=,tag:tlqBRcrWRcXrhF97kb8AGQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
