apiVersion: v1
kind: Secret
metadata:
    name: hetzner-secret
    namespace: cert-manager
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:t+ceuk+VVFHkn1g/FxPDzMBtVT/8M/HFr4paOUbSbKuTBAUrJdiLg/MUgmU=,iv:jGJnC8FVtiwigzfSsp3vA1Otl99mofZYiph07ombnZ4=,tag:Jef2zB+C9Wbtad/bVHFChw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLQ1g5dEE5VUtPc3Y3V0Ez
            QWgvalhpWFJGVzVKOVNXbDdOZHUwVmxNVXhJCmo1VW1idEhpZHVmVWQyTlJ1anBX
            VHlKbjFPcmYxeTdlWGNOcmNoT09FYTgKLS0tICtTTERCbVIxdGJQRXJmYVh4bFo1
            ZHliVXppVUp4bzlYRUpyL0RUbUswd0UKeVrSwicSyiEHRpqI4AATB5Tzi53j3Urr
            zjJC0kwG3YI4+I3j66Elwumd8KiymTL+6zMYATAkxUtIRfqOI7zIcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-01T11:28:37Z"
    mac: ENC[AES256_GCM,data:u1gP4GFic1uwERshsrq369xc1IGImkQytlyTri7XodZponoU8aduG0U5QuHlTO2hU7fhYZqgqDjd5Rz2t6MVM4UappKK8W/o5+XgTfqtoNaDhpxWA7We0OZoPL7n88ANPdMzD1Vs38rhO36mcPsLeTHlQ6spE74xFSHae2wxS9Y=,iv:nDKPMBbP+F3me+HWZZeuJp7XAWswJJRBKGDFd8wlQf4=,tag:J/u3EU6XtxSvAG87WI748w==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
