apiVersion: v1
kind: Secret
metadata:
    name: hetzner-secret
    namespace: cert-manager
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:ydF4CyGwXxjnv+wR/ddMzsMHwI5vlmMZRs9Z+i+qFoTE+6yYLmMDDTYCx48=,iv:sEtSW05hEUzWyjmyR8j2Pa1WqmmAbFq/3tWG++kFN6Q=,tag:3+pfxRmC9VHqoaVeSSlm6A==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFS1ZZNmtFTkxvWGIzMFMw
            OU5vckFzenlPek9UTng4WDFSVGVwRTMxdjFNCk1RalQwYnpSTE9WbjNYZlUyRnhF
            Z29Xb0Y4QWtFTVVVOCtmOUlBeGVtbEUKLS0tIEFBLzJ2YlFpY2RmcDErN2pzK0tL
            Znk0ajV5WVFFYndwdjFMWUMzSm9VK28KFdrmgWKZpSp08G7q/vK+m80TrQQ4ZkDm
            zFYc3/8FZNYEqwnyOdCgnNu8vqH41xKgORgR/ftIWGeyqKGikxwLyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-10T23:06:29Z"
    mac: ENC[AES256_GCM,data:xGffFX2U2ZtC27V8U2rka9XZvMkgfSuhIaYtCVFyY+wotM4E21y6kynvLPMtZCjnIePwLFSWTTt7bDXOzcMlqNuEW00qK/c1OwbShzIZ2lI5iZQ6WL8A3vdF7GzNTzYVMv7zRLhOTjBEK6N2voSFaCNrGLt1hVG2ajkPK/DXSvY=,iv:ZMJUcTnQvDE3wcm7+jyUvRfE7KJ6iJXpP547sxpCaHg=,tag:zziptURITA2lvL4HeFoJHg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
