apiVersion: v1
kind: Secret
metadata:
    name: hetzner-secret
    namespace: cert-manager
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:mJtWYsQpXVnCbP2ipzc2rln6/hJydJCoy45uuwMVWX3yS+kLBmXgL9zMrdE=,iv:I32BON3koQTMlA3jCdo6NABDnkNnzRIGiRAB+fT6P4A=,tag:6CmuIL02nqCqYS3TbS53jA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvSnFqN3hoNEtiRDhzdE1m
            bUZ5em91TVpXWkxRd0w1aTE4ekU3V3U1Z3dvCklpM084VTY2TndjVmlhRVpwd01x
            Zi9NbXZjczZMdklpTVJ6V25DRHFnR2cKLS0tIGx0NVBMU2k4a1hWaDd1Nllka2Jq
            eVpUUjVPbnZtOXAwbDlWQlZCVjZ4Y2cK3UI8fN4ab4q8vEIHPvRDZtf2efsA8No0
            IaVLLYhIIcYDLfrnnhDznC7URj+WwdT6ROvVh+CwY84CKMKmLulRug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-07T14:46:54Z"
    mac: ENC[AES256_GCM,data:+Ep19++Rx7cfXuGgJjqwFKwGHrlIZqM5p9919htpHpWTdtD6/9gFx1J+ql/otN2vF79tWi21rDsLGClf2IhMoWR2/WeTtMfDLbdiESxXg1b6DVAtQjdUs9XP7FF2Eed3eoJplKbLYyck1CL2Ima2oLP4rleE6ULzTrJPzUEI7wI=,iv:i66owvgOforXbaXQupA8F+K1i60HLTHHBrRYf0+aXNs=,tag:7hlseVJiaGB0dFOeVAn5Xg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
