apiVersion: v1
kind: Secret
metadata:
    name: hetzner-secret
    namespace: cert-manager
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:fKaNw403f/gieexS2+HSq6X5FhGTrSbHqIv2vTHd3WMuZ3jOfquF3Tv9nqg=,iv:kW/rraZ1UoilU1pX7Gf2dbXDUlPg0W7mzYqrnpfsoSM=,tag:32aC15Vc11VtgvlSVYql7A==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTeTVlZ2ovZ0UzblZtOVhz
            YUZOdnQ2ck11SHdEaGhFaW5PUjMwalZ1bVNJCmkyRTVLSXNLSGN5b1dtb2xBMFJa
            bUZtWFBaU2lCckdLVmlvU2J4THk2MjQKLS0tIDBSQ3k2dlNrR1E4MFkvYm9EUjVp
            WDRWaDhFc3luN0M1SC9LYnFYaDBYeXcKUK23z2QUOQXf1SYJlXex4796wR4MxQLs
            ZJxRi+9WH9i+lXcJJQM9ttfE48/Tu6HFm0hnv/hhWch3FePnNO8jwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-04T09:02:38Z"
    mac: ENC[AES256_GCM,data:cgq6etSyqc3VB6hmlPmy88qW9Fe/0WYHlulLAuSWSh/E0uVqMyVPEVz+HHmVtVjjdyDfKI2GG8a3k/PxPH/YyUgLtUZlRLe+w705kJPBs1Gt2uQIopOxSLIp20LC6d0SMMES4cUxrIBJRWf4tqb88uNZAsn+oyzkieBKj8GUiOw=,iv:p1O1UlVjqQRVkAaYGrolsGN00lh6nnfFGoaaadYewAU=,tag:mmluTIZ1FC+dIxgmR90KVQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
