apiVersion: v1
kind: Secret
metadata:
    name: hetzner-secret
    namespace: cert-manager
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:6ziSLCNXJ1NWQa91vJL+3mKv34ci7FgX/fd46+tFCe2Kri0aKbaxm19qJ0Q=,iv:wpdLkiSTUHVyAQAaNBZ1bkVvGG7UrfYbl603YvxSiiE=,tag:w+QQI4OpH8CCjbAwabBnMQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4ZDhQQmdzcjlPTWR1TWRM
            SFROY1VDWGRiYlZaVG14QjR5VEVHZ21HS1NZCkx4Q3pnTnV3NW9QWGdSa2Z2SjFw
            QkxXbEJzZ2RiNVpvRHVkYkZHRGM3ZmMKLS0tIGUwWktrUk1XakZVaVlpTDlzSVBE
            cjE0YkEyUjVncHFjbllpRmkwUkJlcm8K2Ds42KVwinY5wfLv3VYtAQsoGIR2dhl0
            Eb94Gwhf7fVv9ywVLlIASa22ML5QRufLYub6/msd3CzSekaODoLFqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-03T21:50:46Z"
    mac: ENC[AES256_GCM,data:SdgkLzOqJjpPanfmG78Fs3bEomP+19Mi1YyQfCdqsRHkAJuIP1RQ3CmgSMwhsmlskMi0yeHLU8XXdcXObkhEAjk4MoYGW3ac7BBDutoqwv6rjPxphpdcPlGRHFB1QPCCR2zErdyPcJIwlX6dBiCvMQgQfcVy/hgdmbtjRC3Az6E=,iv:2RM0krDbL1O6f714aDpwPTqq8fKHw/t0XaqotZTYrXg=,tag:eEONasiqvbG0+pqrm7H9Ww==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
