apiVersion: v1
kind: Secret
metadata:
    name: hetzner-secret
    namespace: cert-manager
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:4lX5qA5y4bTnWdVZ4rOnVMfkOxyLIpcCz+nnb3ItVvxTZYfdAQlL2DGVvw0=,iv:Dqm5ugcH1G4qxp77jYbolMoWacoQoaWfnm7IkTsrbYk=,tag:cF1svZD/eQtbGqCerjyiNA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNdDltOWppUmNlNy82SFdN
            QVRKL3pabG1hV1I4dmlqb2YyRnErNUsxd24wCndOdWlCVXg4NkV5WVdLa0NjMHRQ
            NkZzbEd2SmluWEJwQU9JWTNaQlhwMHMKLS0tIDFyaHJwRHVhaU5wN095aEM2RHN0
            SEdycldtditZc0RjZlcvZ1Y4WC9QMVkKEPsuPm/4GhLTRXhFDS3i/iCbZeDhPjtB
            OhCLMk2HQxDlriRHdCvX+FgNlg7u65xH483vu3ZluCXGKpdfNf1ovg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-01T11:37:51Z"
    mac: ENC[AES256_GCM,data:6FOZefgJ0I52w6j19/DV9M/mnC4i5Yr0Cv23Qml+G0QEW4kR/MjjiHhLTD4j+QySyy+obFhg7mHzRc3gZjjEciybbVbpdmuxfzsbgDp0tGkk/ACK+IxDoMrg1rtU2V98k/pMYou7aS6zCNaO6kMib7mcfMjC4XfIxYapCUkZzi4=,iv:EXUmncsS3TQYpK0+keeJr1F0iah7oQsl/zEGBjhh+9k=,tag:vH9YiTUlPlsmVwEw21Gc9A==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
