apiVersion: v1
kind: Secret
metadata:
    name: hetzner-secret
    namespace: cert-manager
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:C4lrNWQDP7pHls1KC1VjgJwjXDpQfFDLCxr4uxyxvsQZ+FYF5326XfwURds=,iv:ZV/gi08M56ZbnPDdris+gkLZy3L26JMSwf1kUAyXLYM=,tag:Yl+ITN7nz1loiamYkuKKdQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsb0ZNVnlIZHdmVDdsckRm
            MGRGLzFVV09iU3dUQ2R3S0U3MzdCRlB6ZVFVCm1jY1JXbkVhM1FReGZPeWhjZTJV
            ZDdYVzhPeXM2bCtHSWk2R0dOQnNNQlkKLS0tIHo2LzJxNG5UM2NBZXBrYzZHTmk2
            UW9pQ2tTT0JHWHJMeDk1b2FIR3B5REkK4f/rRWjcluywMgtwaHJeM9It/1+WGQ4u
            QWWkJhpx6JFBmdqSiyUjd6ZUFkXXp8uBKTbcrfjBknmM87xDEFmKRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-30T12:27:00Z"
    mac: ENC[AES256_GCM,data:MkXUMpvWKo4Frw027nu70kizf5ZKdHdVH/NczEMIFOIbUvNj1nUrczunoo/R0Wzsd3P5Ma+XxigJg9XiWTEoMbZxFnRZ5EzFr1QV+NgC5//3AoOPQYAqNqSvDCLZzSY7LaNJmTWNX0yifdODOljdwlkboVwpgeT5DyYms1NDymw=,iv:8knGlRDk21tudNi8LEO7bloZHucHOWJ1V4dMSMTYDC8=,tag:ufr/Yww7btGFnKH+qDWGeA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
