apiVersion: v1
kind: Secret
metadata:
    name: hetzner-secret
    namespace: cert-manager
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:0zEhwFaOOqSid5UJRUE7az1EbCx1Op/u9G8e7FUloGtFhKqQv6mrUQZvvDs=,iv:hvmypaoOQfFUwxNgmC9Y2t22Qo/ThQX4CI8ah44c0Is=,tag:mTocLAjytCgB8wvGaiLvFQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHMFVmUE9DRTkrWXBCQ09W
            SWU1b2JIS2xwTE9Cd2pOa3BjV0NpaWZBZFVzCkVicGRiL1c5REF0Z1B2K203WE4r
            UHZ4RnoxRkQvRmp3ZC9RcTFGS29KQjgKLS0tIGZDWEtveWd3dWpFYVFxZlpXK0dH
            RFBuT3JZaGFUa2JwMTBSOHBFOGFtbDgKqiizDlAkkim246eAO4IPr725bgD6gOCk
            iix6HKyDKatsW7rq5gOpMcDXYnklazahpBtErufDTh0FV0yySle+Zg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-29T21:31:13Z"
    mac: ENC[AES256_GCM,data:oRCxP5JPZX+r3OSzQs7ciTn/g4YoUBmj+PIXT8NJ+wJdNjgSNNu65bdtJTThZyyAP8Cyjmb+DXz9Bmh+Q8ZN0vzCp697h0d+Bhl6XQioN0zZR4QrJzpN40gNKjviuIg89C/ACaqCie5HIC78aUA4+aIX6VjqgwT7ntdBLMZVxJc=,iv:j/cEaEI+5QopZbsXVA4uOcXhk3FHxn9W6z8xxYJ6zLU=,tag:MsjxaJ2FsaL0sSI3IvOlLA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
