apiVersion: v1
kind: Secret
metadata:
    name: hetzner-secret
    namespace: cert-manager
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:4gOoP5lbTYz0TQlJ+65jzKO2M2FojBYBghRdQKVx1mmP6vcENQYvqI4e1iM=,iv:xzsdN3BXXMhhpfVZPVtgNAzRDpypGuLf9w4AkPqKjEU=,tag:ugB2lLz2vZFMyUj/8g7hdw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpanprWm9scTZ0MDNNZnZC
            KzczRXV2NHVOVU1wTnJhZ1pwdXpiWnlyeUdrCjJDMWZuaXdJb0lVZW0xZ0NaMEQ2
            bFpiVloxekowSjYwYzRoT0hWT25tZTQKLS0tIFk0bkE5cTF0emY5b1NvdjBwVFFy
            UXFrbGpFdzJ1SkpTK1BlU1plWVZ5SmcKx54tMHrN6Pexli1H0PbZnM9YSR1+z+k5
            KECQ/VU/So/l6aG2QdMxXdt+999d+IKUGQzAy0/sEXAi44NeCFo/4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-05T20:41:10Z"
    mac: ENC[AES256_GCM,data:n8LtA5iyR7Qyn1w0amO327WXLA4UIkGDmuFESU3jWyxMcQaABd32Q6ZIfEMTmpv/K+d0w+r4WMUBkA0FU/RY4mJNQaZJst+6hAf+Cl+MNRd4qEl1meDC6Aio00GkyshEx/SES6Xquh6DzUGDLt9U5/R43MEhiLLyyUNOBtFz5QQ=,iv:VVD3HCzj56akvjuEIq7NhbHesHCrwMm9owxMHr9ShX8=,tag:gkbp376rOTinDb1pRDogbw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
