apiVersion: v1
kind: Secret
metadata:
    name: hetzner-secret
    namespace: cert-manager
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:C4L7DNit1v36nqgkxqcOOdFSkdhV3aZ6lI4APi253R9qolSDv4hoF9eqHSU=,iv:FjcTRJgRyF/r+6gAQUu99NawoF1kzzkJB31F1DzFNcA=,tag:WtOIaU9tNj/xg5t4VEtWbA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrSGtia21xNVJLZ1ZJSTZN
            dDdQejVEV0Z4SE56SHJ0WllHWXRwamZnclVVCmFXMy9Ib2NvVktDVUh4TURMUWVP
            SjVqNXhQRHNGbnQyeTZSUUMyRXV1UzgKLS0tIElvMlh3bkVoNkFLeTRrQkRjWVJW
            WlhNNkhGZjUwZGJKVlBCRHpmWi9jWFUKeA2ii0Z+ncv2HMbbA0z3VI406f1+vWqT
            I+uGj9K5hWP0wc/ZWDbvAMl8Y5+vGdfHgvq+fZdbqP0jusq6p/DTag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-06T15:40:56Z"
    mac: ENC[AES256_GCM,data:WNQv968kUC5+31kG/wfqBwwqUGPthwBwZb1StfviwmCRjWXJ4zw/ToM2+h4ySPDsgQauPmHautvCAZ32to39JwL6rvFUjJie20PJSKOEpTmXr5NJ+dYxMTqADXXHhYKQpM5igS+tjQ279U232OfvHERDvUztESEGj4CfMPQsyJ4=,iv:Z9O9xf7fz7jaihcXhI4hjtTX8J7clvphOkxDWaL70pw=,tag:yoVSDjVvit+AbOo/smc32w==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
