apiVersion: v1
kind: Secret
metadata:
    name: hetzner-secret
    namespace: cert-manager
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:qPAz2H5GPrpQOpCHcEi870ahuh4zPV+KiuxOCWzmP/eouwsFsUZjZD8gQ/Y=,iv:0+Wy8lXMbtOBJ3ws4SNRJVGhVWcTwW+5caQGhj7KbhQ=,tag:MBJn/iTMGHTVu7dDKAolCQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBobWxQV1ZwUjBSSUJybjhm
            OGNEQkJiSkZiYjBFdEkrNG1ZU29yL0hvem00CkU4Szg1NkozOVhVSjJQVTR4Z0xC
            dnZoMWxvUmQ5bE0vLzdQTjlkbDZsWkUKLS0tIG9iREkxTmFod3htYzJSbkFHWWI1
            QjgyQU9zV0JHNU9JdStYMGpvdEdSTzQKlU8UuPEv9katE7rKvgUohGsaiMMIp6Zl
            xRNp3PyoyHT+UCHfYCy5KSirCaaLkAGAmvlWgVU6R2PoUpQo1b3lyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-05T12:02:54Z"
    mac: ENC[AES256_GCM,data:TpCsjOUc6vbmhOfUzD2m5SWNIUAuFf+nY2DO1Jddr8P/A8PSZkfRp0WQYQ0uPdUYp0fW1owVpZMofohEO/xf9PBw8OApka7GRtH2NRo0f9LpMxZoO/2XFVEvc8qh1adS5NbyA3EaRIH/yc9+wfc8fktbJVqjK6rvxXnl7mqWUPw=,iv:Lm2xE+3H6TalDZSDHdH9ro8Bh/2DzPMdd0KfozwDc6U=,tag:Vmk20Fc0HoHhirqJ6PE/ag==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
