apiVersion: v1
kind: Secret
metadata:
    name: hetzner-secret
    namespace: cert-manager
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:EYtKUNETLJJVxFhWmDptBgw2IJzHS6tHp5F30grO3cCqH5rVzot5zQGx2p0=,iv:z0lIDUVO++OmvJZnwee5Yuqi6bFItONgIsLjlMsr4l4=,tag:HWHAeNzyMZnWq1sHijrcAg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYNnNlNzcrRE9wVzg4YjA1
            cmNsSDNHNnRmOThOS0tINlJTWmV4T1hPRlFjCld2Wk5rZFhMZUhqeHNhTDZRc2tk
            YVBuNG9OUUdhcTFhTlo3WHREN3ZEQlUKLS0tIHFmek51RG5obnhSRlhsNTZFWFB4
            TlJMdm5yL1NheDRmcTdaUTM5WEpGZ3MKjRxTTgrgTH/HfVWPUGlA8/+l9QkP2og0
            LqgAoYQokF73oaTA5uqf1VB7aKrwEY3ZEmFA1MgA1rEuL7C/gKH4bQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-06T10:23:03Z"
    mac: ENC[AES256_GCM,data:Ezlf3g5RS8Raj9ZCLhWGYIXIrhexilGv84kBaCG/xGebgREJ0t2aHkUURpB/n4UjVJmaN4QFscJOfC10Vr8gMcVwwEnZ4hkXt3v9yJn2AE25Hp/PtD4Lq4gdQtl8uUQVKPRO8+0kr0LDycjpiDFnBubrnONRlGStfee5EPVrqn0=,iv:xlbL7F0aUGzw/FK2wrQe6ARUvgDOoLxcQ9PAo93buow=,tag:6ndMw0tmT2ETjJByzIkeCw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
