apiVersion: v1
kind: Secret
metadata:
    name: hetzner-secret
    namespace: cert-manager
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:cxzgFoDJr9ybAYfkieMU0C9/av3QEL+pzXoHwc+vWtJVV5tAmofZWJcnGTs=,iv:e6nG2osjrAtydvxvDTKFBGRYDK8ymInN5ww3wjZtOtA=,tag:656Ly6kjsI8FVz6NNjHAFw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGdTY1dG9GbGh6NGRkRVNS
            SVZiKzF1bThPNEo3NWtFTjFHMThlRkl4aVJzClJRbDA3WHpkNmxWNzFWVHplQ0VT
            QloyQjhrU3MxZHN0cnhTU1ZNT01CQXcKLS0tIDVpM01oT0lpSWp1RWw3OVZLK3RS
            Q05jL3VSdnhPU3M4SllWNVlZODJCZ1UKmrMJL5SGZLwRIumPQ/sdHdH72ZjCdYsF
            bA/od5+owc7FUzhvf4FXr1HJP/7zkcNjNLf3VwI2tgFsvWB+4yYgPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-10T10:08:05Z"
    mac: ENC[AES256_GCM,data:l22R29V0UhYlAsgjKWBD69g6XCTfDUFyOiYVUlz3LYaeWYyOrKrQGzJ3KUmP8zE0jB6XlZFMmJ9WG5yyzLTz33jR3QfdRu0TFGR+hRz1ISIft/6fplB0MJDvDtMWaDFPDtBbipLMxwxCWo8T5j/b5MMY3/YmW9I/N4wwScPJxKc=,iv:sU4Z81+yeCldd5PZiPgpiis5HxHVgzVwAJ8rEjfxKzM=,tag:mnyx09xiWXjxDf06wMkikg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
