apiVersion: v1
kind: Secret
metadata:
    name: hetzner-secret
    namespace: cert-manager
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:dX42jf8BfV0yQkPT9oYKbf4PvASO3pB89bI869dcwgGjltCporI9QVo0mEY=,iv:XedDMbbbV3UhaZhYXmCdLhFylWwUU7ygf0dynbRkMXI=,tag:pG8E2W2BVdluCKer+sVRpw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxRjdLL0w3Vi9LOFJQbUhR
            MnA1NllDZWQ3OGU2UTM5K2lxUEcvbkRUNEZjCjZBMzBDazNheU1sTEtaaVhVcHZF
            aTVrUklRTWt0RkRvS1JYUGlyNWhySUUKLS0tIHlMb1pKUWVFcFprUEhHbTQ5MzlJ
            KzUyVzRTQjl1R0xZdkxobmRLbm5pa0UKWpU9cBeBzmEIfApQPpzzLtbaEVbuSBgZ
            NL93SWoywBADKBDq5pp5yFSwDnea2gmR31bpBVWNffoC84iuoeMVTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-06T23:32:22Z"
    mac: ENC[AES256_GCM,data:cVWAK0/y2CGWbed2lRehflmEU+q9G2YfJ1BZvICrnsmkym2BcP8RMP/s9nTMhcBPv5wlgJxE+E3BdkRHsWl2DPg4SJfXLC+vEyKwgE69VzW7TtCvYt5tJUN51s321jfQp5yWtFgheMUmxM0JQm/0Zehfj1AOnt47FYdBtnqqy3s=,iv:6JKl0jDAHOjHokzMo4/JYUob4JTEvxIgmSL7Y8XnM5g=,tag:oLt8s34ELDQymfYURWCNcQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
