apiVersion: v1
kind: Secret
metadata:
    name: hetzner-secret
    namespace: cert-manager
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:mDjdV2wKe7O2onq+c/OWidthwRECRrtb66lhUsMavwKrwzxYDdzXLvdx8p0=,iv:upeoA+IVzyxm9DHpxDAZMc1gleMHe88trHuU1K+SApM=,tag:zRoasZmf9DhuNJtxiWa66A==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrY1JrWThCb1VCc3lpaWUv
            NzNJajlHN1dQd1A5a2k2TDdmTzVGOHpTWTNjCkNsZENEWnZjcFFkR0hiVDNuRmxv
            OElXTGU3TS9IRjJuR1hzWG9WQkQ0cjAKLS0tIHJIQjU5eE1CM1ByREsycUw3VDJ5
            M3pxZTB4WXBXLzBJdUdCTXRHVGppaVkK8u5CnS0RzW9NK25PuY8nZZhx1ffkDaau
            EQrAeK9yDPhXR9eobTzpCDJ8dm1ZSBnl+I5nW8CA9ng58KD+qyWC0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-31T22:45:06Z"
    mac: ENC[AES256_GCM,data:fDhSwX8mkbVmEloukjoUtxuZKMudfZJRzZD0cU6MYedlsi85mcCQtMFGIXgsMcKG2ZvJw8bAB/yOKH1xzvYVjGfh7C/6HBXB7b6qdS4HCU3KT3UR49bIHFQLE3tC0W6LCWBNOJd74dhIAhtxiuB8u/nAf+zCTVd/ORDwJtfCooA=,iv://hYsvpu7ZIxvePlk/mqiyb34ROcMPLAfsECxYul2Sc=,tag:Unos1ZDIYG39R4JtnCqsog==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
