apiVersion: v1
kind: Secret
metadata:
    name: hetzner-secret
    namespace: cert-manager
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:hGXl9lu++JPI2yR36uA12Ut/rJslpqNZLOWCFPrGT40ekx7/NSQD9f73kFc=,iv:kz7INOTbyWGkeF9Vb3/ily9TKDL+bSD5x1HGnzS7Alw=,tag:Mi7CkaDggWUdw4o3lRTYmQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvT1hHdTlsd2JsdVhoVVhy
            STd4TGVGR2cxMXZwV0NIaCswTXVaNWlGampjCjl2d1hBaSszd0wzWXpRNVJ1WkN1
            TDlyZ3lURlFLOWpFVjBlMVRES3ZLcDgKLS0tIHd3YmxJVk1ybTBHeFFHMldOVVBk
            OURrYjM5K2M3UWV4elphNGhsWTZiZlkKS5eqIioKpAAoZ5juJi+XJwi8Ft2u/jWE
            lSLNxzg7MqL2E0u9BFcF5i2vLJXzqFB7ReyLT5ucmAXJrTHWLFB7FQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-05T21:25:36Z"
    mac: ENC[AES256_GCM,data:4fYy982xGJclsgB+SavkQNKGc1ljrcfvpiTErHh3a566O7T+jb6qQUkHweLNMAUC7mYQ8SEQvQOmCJAiTPJdoCa2NaLbyXWbGSDjkr/tqK2Xn9R+a/FtsDzvMS+53NwhNA959A4Fv7BsIB2Snq8BzDlxlEwg2muV90RWg1K2/Dw=,iv:5zTK/oXp7c0+nx9wo2WOHp3Chs+1IpzZKLeooatLYi8=,tag:Q2cJgmcY8o3YGXe7FpD1JA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
