apiVersion: v1
kind: Secret
metadata:
    name: hetzner-secret
    namespace: cert-manager
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:U4oY8Nd+Yg5J5YnZ1VjXmbIvXL/4BkuT1B4FmSD76oBDNaFZkL92/rPLUVk=,iv:o/tJ+SCLjawfuQGc1aMgNThHluQOJ0GkxEodXO5eT38=,tag:+w7xOAaUgwYdxVPAPbG8kA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ZVpzNzc0eUJNbHBPSVN4
            akp0MjlETTM3dEdtRmtjL1BzWGVmTlJEc1dZCnZLSyt5dkN5dlRFcCs3RlpueDBs
            SkJMaXFIKzZBV2loUnZpWG1TZktVZWMKLS0tIHVvK2UvWVo0dVptL2xrMlpzMUhk
            enQ3ZUdpUFNmUXhhenVvTGRHUVBPUEUKVHJ5tQlJlbF9pZUP2hzjgfkuw9wzTY2O
            9x5JXO0jf757dx8kgPMRL8JlQnsXF1lbN5xiF3QTDEvu9eC7YPKg/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-01T12:49:53Z"
    mac: ENC[AES256_GCM,data:zCL5UGmdivtCYkvOh7cvcp3fZDIlhDsrcDyQ7PqPaQr4hUCghRv9bmoAhCzUMNqzzRHJla4Pf63Kb2v1z+z+5lkDL87FWPgDTcvHfUx2nDH1RanfChqLISLJBfg7wm7vdCvZEY92r1wPG9pw2sydgIOSeOBKCaLcnNDvIQdURtE=,iv:1NwM0b4JN/9F9vI1nUml2EZXaBkMavt123R6meJSUpY=,tag:y3rP2iZzPDB+7OMMIfQ0FA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
