apiVersion: v1
kind: Secret
metadata:
    name: hetzner-secret
    namespace: cert-manager
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:WKbo8FzU7yKcZXnCsv6CSMs9UzMunzvV8P6PTesfZUOa5EQzw+vvfjySBPQ=,iv:sq4QoWVdTayYDWoVGj51U1rNdyeiT7mPxMiiHUlgi/0=,tag:JltiT0/FI5R4hFSD6nu9CA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyTkVyY3NKK2tRWVA2bzkz
            VG9zSkwyaWxxbWVmaEo4ZFdmeXVLZDBNUjNzCktZM3Z4R2R0YjNSWFZHWnVTV1lz
            enhHYlpzdmZWdU5scUh1QVNZOTBDU2MKLS0tIHlXMTdObnkrdWI0dURkK3ZadldC
            c2pSc1R5OXU5S3B5RHBjd1g4c1lYYkEKY8A+8fB+WDwis4OkYyPZK1g6FMr6WlaP
            yrXyTwI/ZivYV9zYGOmIIbS4cWS1hA5BT6o4HoEdqUDNr08oYl94Yg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-08T21:10:14Z"
    mac: ENC[AES256_GCM,data:8JJ0RbPJiuVufysLAcBjQwqMPqySzSZQeSgBk8osGdt0WTNlBbuXK0V4NMokBFELnuox4orARSeiuONSAvgNeGXZvFRx/qMeMkp2wTpLXUs2BSvgbgDE4oIFYV3/HxseFCzf7Mrt3aKpo7GT7Zhxv801hYfmJ1q3clOUWANpnT4=,iv:tJFg8w9PVEMZ88YXi7ZWOUMcPQeHdadRY6nIKryoGA4=,tag:PSBAF/6zFzIDw2uvxWVrdg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
