apiVersion: v1
kind: Secret
metadata:
    name: hetzner-secret
    namespace: cert-manager
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:4x+qKhU6h1fRVtSsz5k5dFIV9cCrhlmk9t7Qqc+kFwj/qX7nk/YSVf0yNR4=,iv:RblNYk8jMm3LDAYYX5wc5dtDfRtWhWQAepHdERqU2Sc=,tag:pBOxLxlbL5/CKwUuVGNz+Q==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6M0F0dHRlTmY0ZzYvWlA2
            OHVnM0pJVzY2WUFud0lFS1NZSERsSjlhMW5JCks2a3BmSjd2RXU0TXh2M2JRdUNs
            dWovQzZaVzEyNS9XdGVtUThMR3BNMjgKLS0tIE5NNExFRGlFMnZXdks3RXVEbStq
            alZHc21aWjRURk91V28wN3R5OFI4M0UKF+GGt/S57pfrT9EmYKiiILold6bvyFiG
            wh3Cv1jOITIXS/E+Ns0svllsRiY+3r57WrNRfijlNyaK7bNEoSD1ag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-08T15:08:25Z"
    mac: ENC[AES256_GCM,data:Ftcr7SO3LemnJETBpTsa436SADAJ5jajLoQp+2shr4E6As9kL7Mu3FYCwQCBO8chRN36SdgCFM4iVv6mvsYTsCMQlKCNVnDmvnrxOEfztn6MhtJidhKndrKYR6uy9XkHhIVT6mwSNxBTJxrLiLLSGDG0VgEY/b3mDzoYmazksMA=,iv:X4DQl7uY1iHDZb6c43x1lHTLI/12xjqoE5aGMbny+gE=,tag:f0qZ3bckN6tqlyjH2458KQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
