apiVersion: v1
kind: Secret
metadata:
    name: hetzner-secret
    namespace: cert-manager
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:zH79i+1tdZzIYKY91an4IINLGXZoG76+FNcjAZ363lS7XOC1kpZq933mScU=,iv:dRVor0edzJjuN+QYSCCZUoE/I0pir4u6xcgkbUdJszM=,tag:Rvqai4F4jawoApKvlPa1+g==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSWkJrWEU0ZFdIZTNSZW5V
            YkNZbVhhWmJsTnlPcHNTbzR2cSs4N1puOFVFCmkrdHhlRm1FTXM0OW1CQm9vTS9H
            V0VtQ3hYdkgzTmgyRXpmbHlhamIzMDQKLS0tIFUrZnl3dUp0cm1sbjFMUEhOM1Zv
            WDFpUlB4eFhWTmRLaVprNjh5elg2YlkK9G2qJVofsO6sq3uTUhbnOEgY9i60T3hO
            99KOJh5QdJxwc1RLNej4YBVpwNunWQXWMoHJEdutOhUOz4yZRR4wWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-14T11:49:10Z"
    mac: ENC[AES256_GCM,data:pOmig7jzz/+TYxUcLrPYg7eVMX3NOc539orRB/rq+Pk7KDKur8a2uFYxub2S9FwLXw+p6EIwLd11hwjKJSn3/McT+9fwBMbmIzVGtljcFHoIqSgrpc7cm4JXXwGMe/mNRUQkJpYl+8BhlSgykeP/zw5jXCmbPL4EfwwA7p8c6xc=,iv:t8wNFsq58Nmcb81mFK2EBAW8ENeXilZ79DPjRGsacUc=,tag:tRkVJBUpPtqWMyKHBHnBVQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
