apiVersion: v1
kind: Secret
metadata:
    name: hetzner-secret
    namespace: cert-manager
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:rgDLbjA3f03+ohRMZhDAJX3bM18QmA/kkxbY145HPNqOGH6rgIFAydyI2fQ=,iv:4x7qrsSM7GWlWbJYObzJt6YI007I1iEtvMSORrJHGNg=,tag:GfAFyIdl/2+bO8bRpPkpkw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRMTl2ZU8rUllUT2xqOW0v
            U04yTVJzTzVQUFl4bG9MZnBGUG1IWTdKakdVClRveEhGbFc3WXllVFJ1NlRPVHhj
            R1AxVU5yWEZWbFFjRTdDL3dhOHRnQjgKLS0tIGlGdWpwWTI2MXlDU0RYVjhmNVg3
            aWhKTXNtZ3IxTlQwbmJWYW85cWN2SVEKBUWlOmqXSShgqpTEObmUhDT5CHm82BmI
            zQii8UWfZ0ENkeCLwNLookgfwqkii6nKNFqr+ho5YnMicFrBHHTjLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-14T20:18:23Z"
    mac: ENC[AES256_GCM,data:bmsCxK5Upy4EP4LE4VchCFxgyEtLHtJBLUSzUvhCLvkuVVkhqfpc+vHTmyDthJhal4sSW5Ju9dX3jxaXVpxTBUEPzTgMzFVTPimaD+Y4ZLTFPQbotN/+hLDfLcMvl2DIW8X7R9N5+a4PiVGgfi7vp3olPnw3g/H5oKqRkR2QKGI=,iv:OVy8CTCkvj+2UTOzK9jMBw6lZ+M2kCCB8gScVNQH6po=,tag:sPgvm28lGGwo9eO9dZProw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
