apiVersion: v1
kind: Secret
metadata:
    name: hetzner-secret
    namespace: cert-manager
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:iJqa2/gS4Ls+3LlPwvzVuXtY4Xr2EJsst9HX7WE+h5WVMh/vxI/BienfFZw=,iv:Bfy1En4KyzxzaZVr+Dqk0V3nYd1dICDyZPoPhEDBmH4=,tag:ZA+NVxyMTxiA1mmkcrUgdQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZmU1aFprUVJEMVpjM3pl
            c2JldTlja0toRXRIaWQ2VTFiMTRlV0l5V0gwCk9QSFgvN0llMHZqREc2a1VaQUxz
            SENXc05POEZSRjlzbS94Yk4xTktPM1UKLS0tIE93TEdZeE9jcnhYZm42SEVmWjJn
            T2tldDBlTWQrSU94alNNL2xmb1I4YkkKUohIvxAlr77Irt3M5k5YELYVUOHEjklo
            yMF19UBifJHHyLQAvyuJyWsOHDyoOhANQASLl1DifGKXBmN5Sg+tuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-30T07:20:52Z"
    mac: ENC[AES256_GCM,data:iYs+ZJDvt4CwUxPhg0IBAyKzPLASaM8KqH8MLg00Plkavk//5CS1vOYpueDFy4lr75IWxMsCt5SuEKOYxZUKOm0h4Epjx0sOsklrThvUH21Y+cr699BcWtuDuKHk/yLc10LAcK1LPkE/2QAH1K1LFwKnu0sQYXkyKERoO1n1lC4=,iv:RBA2asmPzwOPddCuvi5EWJehQwRVQRteThNFakjqfBo=,tag:lXrxsynS7SpsvUfTNsED3A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
