apiVersion: v1
kind: Secret
metadata:
    name: hetzner-secret
    namespace: cert-manager
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:/BDwJsoUNB1ANBXnitUYk00S8dVMmKshb3PfxbE2z0hFL7blz1T/StBdMaI=,iv:6rGhd9UZXAH2ZT18tJ9osnks+PycMXt6vBIQ16jkUz8=,tag:CQbs/UpLKWZp8v+0yVORnA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkbXFGRFUvYlE2RE4wNnQz
            WGVKa2JiU29yU1d1Yndwb2xrNU1qSlNRZERzCmNFRFU4dzc1MG9POVdhdndmaE84
            NW5nc1JmS251MlBreTRwTi9XRTJyMFkKLS0tIHZzMHdUS2JMWHN0cjlrMmhnb0pE
            OUVmRi9pNTRkSHNJckpXTC9LeDJRU2MKDMe1wXd0xWgpSDtLXyzg+9yGEPPFaazG
            wFoZhrI87ScPgqur/HZPd9BiXDtivsvoaTEbhci+hzpzQ8xsEZ4Upg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-28T20:03:01Z"
    mac: ENC[AES256_GCM,data:liwngPiz9uVlGjbgP1gN9GVjo9HkAeVxzkrMSf0vxC3Oyb49IPK4E40tmmgTooTFxO1IX6LOxhJjQFEdN7kni7gwOq90gSCcysyPGNYjmqB2RjMQy6sgKu2JlxSTGzTFOdvTQUtTp9vHUQG9exHwUHP4dVshSv2FdTy3FzPCWl8=,iv:wfodyfexFB6Z4RbzqaM07IOVwkzy3Lx+heIId30YubU=,tag:oTrhu5jHsXVl1dy+DfFZ3g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
