apiVersion: v1
kind: Secret
metadata:
    name: hetzner-secret
    namespace: cert-manager
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:/E8/lJqyv3GaE61bY5U/h36H+pHzPkFrYn6W9hvovg/CPh19hR3nDTOpl64=,iv:1wKFqNTi+pleFezx7UH+ZxItu7rBO6h8sFc4Owt2qQo=,tag:iv3wRUVhzHIgEd6Im4q1sg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJdjZic1dvQWt4QVVxRVJL
            V1FhUE1vbmZuV05IcU1vMVdwYkpyM3RvVDFVCmFqTGs2MXczSzV1RG00WXFhMXp6
            eDRqWGtIbWZweWp2R1JNeEN0WHZMMG8KLS0tIFVRUERVbWpHVWFQZDNEcWhBQlhm
            eU5OSWVlbDMzdEVlbCtjNmNmWlpBUlUKyhGWYxH9I52nMY6Na2aJc4Ht0zpkrUQx
            qm5kaUWOvcg0uOvYFJpO+wGk6nGoJlLTSazph/ion77KY+kj5+DCKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-19T15:20:23Z"
    mac: ENC[AES256_GCM,data:S2p6CcCTah37Zg2KqFEMeB0lfIyvqi8ltfSVV5o4DdA18AG1FtrMFp51FEP3aX7SaLNBgll0/B1TFhoktro4uuszNdJ7NjdF09msY3Dy/pI259nHKilxR4o4hq1E9BCrKbkqRAe/8EabFyslDi0fP/ypAAJH9krvLUlr4MqBkXg=,iv:IBld6Dml5mPx2AJr9o/ANs9eiAPQsrWsqcNNTsB0nI4=,tag:EmHRvDuyich3YtalsKksvg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
