apiVersion: v1
kind: Secret
metadata:
    name: hetzner-secret
    namespace: cert-manager
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:JNd2RViosS0RMyDQ1Z/67oPqLIn4Hk+ECdZT3OYiLpCXLmKBhA0UFWur5qQ=,iv:xQXSYnlPc3MiHhUnuoxNM+L6KI7LsG7XqnKRy3aVCqU=,tag:DzGIQY+DnSfUzHRpvcTDug==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpQ0NFUnRhU09obUkrYjNu
            REF3TmNJMUlJWXhXRGRTRXFOVFNsaEl0TG5NCmI1a2gyT3lBd0k3Yi8vcnViRE1M
            VjB0M2licFl1QXVRS1M2NytaUjY1RzAKLS0tIFU3c2NpVHNBRGgvY0pvb0g5dWtX
            WEtXRTZDR3FlT1lVeWF3cTBFbXBQSGMKNtXZ7IY+7WrNl140b0n/4kM6HqcUeyIM
            wfNjJRZvljiATh7nktiP5eKebtLqCAHSqOr1uA6njI93ebHkXcI+9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-28T16:41:58Z"
    mac: ENC[AES256_GCM,data:YrLsO68cAVMyn0H8PDLHsCZ2N5A0XzZno72rrsHUBA/jbdotteyRelzeuvBJQj1Qm3TeHnlHnOTygdX4HQUcqJCnD1uU9+zmqaQaftV3ijuNiNjyfJAZ4MlqFRZmu3iLRrA8KeZxTsLP1vsF+HIJutoYYKqHh3VyWSEX0m3iF+A=,iv:LA5uZamPVHNmFzjDoKe3EuUaLgMIXTtJ4bIJHS6TrO8=,tag:wwlcW9K8+S9U/rVZw5B7Hg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
