apiVersion: v1
kind: Secret
metadata:
    name: hetzner-secret
    namespace: cert-manager
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:BdXbtlmaoH+W+eB6fH1CvqMDWsWb6y7Vbr7/vM00gFgw27He4Uqj+tVqsyo=,iv:hSwszaiIR58pbaeCElFYpRKvqH6l9Y9xievAKUHMx5o=,tag:mxjBz7QrPHQvOXzj+TlUDA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSRUluYWhoRXJNenhvb3Mx
            eVBRcUdPMnQ3a0w2aC9xUHNIWStQakR0aEhZCmtkc0FUWENRcFlacVQ2MjlydEc5
            Tks1UzEvUDJ3TDZLVlJlV1h2V0tPODQKLS0tIHVMYlRRYlVWbW9qcUxMTGh6cVVi
            eklMSXloVDBHMWVIRUVmbll4SjVvaFkKPqNlBkMz2rULkno40QlnECFcfr1cCtXb
            UQISDnvpJIdi8BwgKHgsLWzckk+/tBlMwvzVA6GVTXiJDKULglF7sA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-28T20:18:49Z"
    mac: ENC[AES256_GCM,data:ngIZQVgolWzkn7F3k0b2cYem7BUwUzCN+tKJYrGFQIyfep4oEWd8zwXvo1x3JU3MRpW6tBRpZXZkIfMSZKSVTWFTeCDloZUj+HDZH/XUPtrprujUHjbLNUdzdVU6C8ndbZiLSNPv+NlFX2g/QtwpsOl62my6JLPGFtnsXzBrNk0=,iv:QZAq0I6FacaJdEUyI94BpxwR5RMWs68dXEX+YL1R4bs=,tag:Jcicb7Johiu/tioC2uLpMg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
