apiVersion: v1
kind: Secret
metadata:
    name: hetzner-secret
    namespace: cert-manager
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:CcHx3yVta9k0Y6RB2epHFxr/Iv6IgU/zAtxsZZaFGDl+ApcKhrL2bUVyN0s=,iv:WfnFypgbQL9SPnuNul2QgzbyqsVStwhaFrIudEaNQT0=,tag:evSA6niu/6ijRgb2ZmbM3g==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVThieXQxSW1ONElNYUM3
            SkhhRlA1ck1oK0Rmd0JGa3JoRytvZ1h0NWkwClRhSTQxUmxtb0U5eGhhTDVTZ3FB
            S1BFMENsakpOZnArMUh5TmdhV2x6Z1kKLS0tIHh4ZC9iTVV5dHZYRjQ0UitOSnJl
            V2RkYU5FeDBjblhVSURGMUlGazJvbjgK3qLuB08fuqjwB4yh58UHaxUMd+dpiPmh
            9fHqVC2p9D8f7JS12ZNkBJmxsKkU/IKLvH4lhsXabOUr5qfPlbCUOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-10T23:01:35Z"
    mac: ENC[AES256_GCM,data:fIBQ9im5TR+PVpxfIKvS/bO5XcWMyS1E1d80uPucsxNWlzNNhDDLgulO+whQnc8L20UNLA6NtEdyngIglLFGdoGOQg3vB7jZq4B+TVd76bFE7FoyDAtEo3qKBy6bOsWKd0b0zP0lJI79pCtzIU/MSuIH7xoVhaPp365ls1+wwzw=,iv:iu2H5+n6eyzs7kUXUtao2IPJdU3NGqlx9Fef5J85vEc=,tag:D84zFL4YK8yV+py+bycKXQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
