apiVersion: v1
kind: Secret
metadata:
    name: hetzner-secret
    namespace: cert-manager
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:8+9GTedRjpJ4wgqb5ZsDyJhMdZuH5CmsYvvG96tZc75m4ZV69SIqqfHmVSI=,iv:QJvTW15eM/VD1jcv1NeT9gcP/ggt4z1HO+KEbzd1HlE=,tag:t+oJrklU/BM4JGGXzFK7/w==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0NzJiNlhIb2pPZzVJRDlh
            ZkhONDJpVVBsS3AzZWVaV1d5NStJMXFxZmxnCnRJV1lodnJ6ZVZKWjkvSElPU3Uz
            UE1oZTQ3aWd3NmpiemlkL2h3S1hkR2MKLS0tIEhJNGQyZ1BWZVl0MEVSaXVncWND
            R0lUR1QzZWRKTitQM0xmNUgyUzFLN0kKexA+9nxN1IHBZ3Z6v0IBbY92EYcWIU7P
            lSIsJ5aZgSGFnra2hl265yOyTLmcdUiZmg5jhTYQhBIwyzcznrxBeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-20T10:55:51Z"
    mac: ENC[AES256_GCM,data:SwyQKiLDhHyMSTfHMttmMrAvnprdaPxTulErFmnzfjoJQ8fhpny3vmqvot/BcCyZrGF94BgHqPzHPUZgE40r/VgOo2e/y/NiMqZFyfYuwv0r+18Tv0xk4ffsRVrHB8A33rT5gBoNGKi64Os8dxHPWQkqCGewk4mjFrIdWgrgNrg=,iv:QBppWpqKd+abB6D0k38cgRfPORtemO+eWlC5fp51W7I=,tag:eNyDmb6Qj4muKbmO+LBXIQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
