apiVersion: v1
kind: Secret
metadata:
    name: hetzner-secret
    namespace: cert-manager
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:QmeAuhAK3ii3zD0EI9pmJT0465S6f7kfhlZKvW3BPcacTIIpVRxOXgwVgEI=,iv:GA8cLcl2mZhUxo+CQMHeY6HaW23I60l0AaBunfZ5SHg=,tag:B6rzx9byecHIJlI6+syzAQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBndVV3SmtSdnlZaTFnVk9y
            cnR3OUdtQkprMHNVODlVRTF6b1NVdzM2aTI4CktTdTBDL1hOU3VTQlpZODZJYmpH
            WTRZUHZLWTZFN2F5d1duaCs0eWx3WkUKLS0tIDVRSkpLWWsrUkZNSmoyOEZnb3E4
            aUpPVGFHMStQTW5ySS8xaU5LbFVWOHcKmzBzgMNXAbBNd4djSxjIwU0eKgOs531r
            Ei5DxTBtII9W5mM3QoQ6ryb8UGz0DcDu7Q3U5QK+j/ksirODQEuz+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-18T18:56:27Z"
    mac: ENC[AES256_GCM,data:217nikwxPKaSJuLhy5FOQG4Ubb1+BLrUz7D7rmvw8WTrFVwqoKfg3wyrG7ffrAbv2ZOvM566e2xy5Iw0f6UEIwTdVzj0iq48BpsrygjM08MIJGI9KdEEIcwo0KIi/GogdDgqKQ9j0RaLEW9AFQfEquMLG9QLocy6GeOk5JnlekQ=,iv:wkKsT/c/Btu+vqS/Qm9HXpV9IvWR6Rve420S8YXq4Ac=,tag:sBT/giYx6orqY/0a2oFe/w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
