apiVersion: v1
kind: Secret
metadata:
    name: hetzner-secret
    namespace: cert-manager
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:q7PT/9zMsSZ1ojvZekBm1f38TGgNqiuHOuaXv5p+3abqwiws21+CTE1uFWQ=,iv:SQV2MD6CqmfCsF9plmRlXrCjuwku+94Aare8BdtL8Mk=,tag:dMpiCJPXMwwOW0nXCOT4/g==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4ZjZtKytRQ2JTOGFCTTJQ
            bHlJVGtQNFlMVG5Va0I0b1NSd29GRkw2cDBnCkJiUnp0cXo3eEFodnNZRWF3WUVW
            NVVjZ29TUVNSRkVJS3N3OWJrSy84R0kKLS0tIFhzUWNUWEMxTDRRNGErYnoxSEFM
            cHJJNzFpZU42a0VFVEs5bStXR2Y4QkkKS8U7bq1eQ7XQ6+hsmjH9r8hc84rTDJi7
            wOGiXxZIJLT/C83g8zQf1bEU2tUTbZJ5dYPU2xWGJEj3KvIfadFn8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-24T13:38:26Z"
    mac: ENC[AES256_GCM,data:KYtbA1eGp8HJWc/BNC4LPe1Lc1qCCofwtjhL0GR2yFAX7ktrU5gN3MTzIR87CPBPg7rs/AFmf0Am3G/wTZIwqmTpU7Tm1aWHotmRSC0EpkA/kWtcvteLbt2J42bcKMS7M0yafy3Vf+N67eGPwXlX8X5ZsgrIqg0nQtnE90BUHSU=,iv:89SB8Ue6N8AZlbodTmr1jII13iUhHkZCQnMsV0RC9AQ=,tag:OJY65TiBrZWrrgWao3S3Pg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
