apiVersion: v1
kind: Secret
metadata:
    name: hetzner-secret
    namespace: cert-manager
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:mIhQGNuRAN80a4IQUVohK+aSJys85onXK2Bl2v9I94rkERwvjm9+vySyfVw=,iv:byhJEDvmnlXb8+QzrgcFBmWobQEPMyenjPuNIJy8qfU=,tag:Jhq1OQh56QCuoX++QTtsnw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3eG1GUWw4aFdmYnVjbEta
            RDR4TFNraEhFci84cFZadnlVa1FVZjV1R2tVClVOSFhIWS8wbUFkNjZUVHFHbXk2
            T3RvUGFEOW9xaGZTME1vTVNiVndWL0UKLS0tIFZYSjZzU2VRTTNEQ0U5MzhReUxu
            MlJ3OXhtS2pmd0VmcnozRGNxSGJWQ28KZxqK8GEkJfI6zw8SL7SZtGGXT3gKbA2N
            jLI7Qc4z4HdgRYdrVqhrD+kk8huF6vnQhHT919mHEslAEej0c+/IkA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-05T19:04:07Z"
    mac: ENC[AES256_GCM,data:USd5SFxGvlsKj2w6r03yTsT4QdX7n4Jo+OdcIgl6z9ysHlXImeswleVpbKc1mp1fEdpW8lR+RTia60XUGeSNE41XE7SA1b1IcJWnT+KBDesJYZFJ4baVwi+rjBXmMJtYBniDGfLHopDRBHeUYi+zc7ryH2m6T36+45o/ysmC/xQ=,iv:8upPdTgvHLZMOdbJA+tj+66WUXA4IBTEzmEKgzXYT7s=,tag:MIquSI2x2ixNS/9GFLLzBg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
