# Allow the service account `cert-manager-hetzner-certmanagerwebhookhetzner` in the `cert-manager` namespace
# to access the secret `hetzner-secret` in the `cert-manager` namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cert-manager-hetzner:secret-reader
  namespace: cert-manager
rules:
- apiGroups:
  - ""
  resourceNames:
  - hetzner-secret
  resources:
  - secrets
  verbs:
  - get
  - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-manager-hetzner:secret-reader
  namespace: cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cert-manager-hetzner:secret-reader
subjects:
- kind: ServiceAccount
  name: cert-manager-hetzner-certmanagerwebhookhetzner
  namespace: cert-manager

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cert-manager-hetzner:hetzner-creator
  namespace: cert-manager
rules:
- apiGroups:
  - ""
  resources:
  - hetzner
  verbs:
  - create
  - update
  - get
  - watch
  - delete

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-manager-hetzner:hetzner-creator
  namespace: cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cert-manager-hetzner:hetzner-creator
subjects:
- kind: ServiceAccount
  name: cert-manager-certmanager
  namespace: cert-manager