---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm-release.yaml
  - alertmanagerconfig.yaml
  - pagerduty-secret.yaml
  - prometheus-rules-volsync.yaml
  - prometheus-rules-cnpg.yaml
