apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 15m
  chart:
    spec:
      chart: nextcloud
      version: 38.3.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  releaseName: nextcloud
  values:
    TZ: Europe/Berlin
    podOptions:
      hostUsers: true
    credentials:
      storj:
        type: s3
        name: storj
        url: https://gateway.storjshare.io
        accessKey: ${STORJ_ACCESS_KEY}
        secretKey: ${STORJ_SECRET_KEY}
        bucket: ${STORJ_BUCKET}
        encrKey: ${STORJ_VOLSYNC_ENCRYPTION_KEY}
        path: ""
      aws:
        type: s3
        name: aws
        url: "https://s3.eu-central-1.amazonaws.com"
        accessKey: ${AWS_ACCESS_KEY}
        secretKey: ${AWS_SECRET_KEY}
        bucket: "talos-cnpg-backups"
        encrKey: ${AWS_ENCRYPTION_KEY}
        path: ""
    cnpg:
      main:
        password: "${NEXTCLOUD_POSTGRES_PASSWORD}"
        cluster:
          instances: 1
          singleNode: true
        mode: standalone
        backups:
          enabled: true
          credentials: aws
          revision: "6"
          retentionPolicy: "2d"
        recovery:
          method: object_store
          credentials: aws
    ingress:
      main:
        enabled: true
        ingressClassName: external
        hosts:
          - host: cloud.noitl.space
            paths:
            - path: /
              pathType: Prefix
        integrations:
          certManager:
            enabled: true
            certificateIssuer: ${CERTMANAGER_ISSUER}
          homepage:
            enabled: true
            group: Dateien
            widget:
              custom:
                key: "${NEXTCLOUD_NC_TOKEN}"
    nextcloud:
      collabora:
        enabled: true
        dictionaries:
          - de_DE
          - en_GB
          - en_US
        interface_mode: default
        password: "${NEXTCLOUD_COLLABORA_PASSWORD}"
      general:
        accessIP: ${NGINX_EXTERNAL_IP}
        default_phone_region: DE
        run_optimize: false
    persistence:
      config:
        volsync:
          - name: app-config
            type: restic
            credentials: storj
            src:
              enabled: true
            dest:
              enabled: false
      data:
        type: nfs
        server: ${NFS_HOST}
        path: /mnt/pool1/Nextcloud
        readOnly: false
        autoPermissions:
          enabled: false
      html:
        volsync:
          - name: app-html
            type: restic
            credentials: storj
            src:
              enabled: true
            dest:
              enabled: false
    resources: {}
    securityContext:
      container:
        UMASK: "0022"
        runAsGroup: 568
        runAsUser: 568
      pod:
        fsGroupChangePolicy: OnRootMismatch