apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft-router
  namespace: minecraft-router
spec:
  interval: 15m
  chart:
    spec:
      chart: minecraft-router
      version: 1.4.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  values:
    TZ: Europe/Berlin
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${MINECRAFT_ROUTER_IP}
    workload:
      main:
        podSpec:
          automountServiceAccountToken: true
          containers:
            main:
              env:
                AUTO_SCALE_UP: "true"
                IN_KUBE_CLUSTER: "true"
                DEBUG: "true"
    serviceAccount:
      main:
        enabled: true
        primary: true
    rbac:
      MinecraftAutoScaleUp:
        enabled: true
        primary: true
        clusterWide: true
        serviceAccounts:
          - main
        rules:
          - apiGroups: [ "" ]
            resources: [ "services" ]
            verbs: [ "watch","list" ]
          - apiGroups: [ "apps" ]
            resources: [ "statefulsets", "statefulsets/scale" ]
            verbs: [ "watch","list","get","update" ]
    resources: { }