apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: qbittorrent
spec:
  interval: 15m
  chart:
    spec:
      chart: qbittorrent
      version: 23.3.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  releaseName: qbittorrent
  values:
    TZ: Europe/Berlin
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: download.${BASE_DOMAIN}
        integrations:
          certManager:
            enabled: true
            certificateIssuer: ${CERTMANAGER_ISSUER}
          homepage:
            enabled: true
            group: Dateien
    persistence:
      backup-google-max:
        enabled: true
        type: nfs
        server: ${NFS_HOST}
        path: /mnt/pool1/backup/backup-google-max
        mountPath: /var/backup-google-max
        autoPermissions:
          enabled: false
        readOnly: false
    service:
      torrent:
        enabled: false
      gluetun:
        enabled: false
    workload:
      qbitportforward:
        enabled: false
    resources: {}
    securityContext:
      container:
        UMASK: "0022"
        readOnlyRootFilesystem: false
        runAsGroup: 0
        runAsNonRoot: false
        runAsUser: 0
      pod:
        fsGroupChangePolicy: OnRootMismatch