apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: datadog-operator
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/system/datadog-operator/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster

