apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: odoo
  namespace: odoo
spec:
  interval: 15m
  chart:
    spec:
      chart: odoo
      version: 20.2.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  values:
    TZ: Europe/Berlin
    test: bla
    credentials:
      storj:
        type: s3
        name: storj
        url: https://gateway.storjshare.io
        accessKey: ${STORJ_ACCESS_KEY}
        secretKey: ${STORJ_SECRET_KEY}
        bucket: ${STORJ_BUCKET}
        encrKey: ${STORJ_VOLSYNC_ENCRYPTION_KEY}
        path: ""
    cnpg:
      main:
        cluster:
          instances: 1
          singleNode: true
        backups:
          enabled: true
          credentials: storj
        recovery:
          method: object_store
          credentials: storj
    ingress:
      main:
        enabled: true
        hosts:
          - host: odoo.${BASE_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          certManager:
            enabled: true
            certificateIssuer: ${CERTMANAGER_ISSUER}
          traefik:
            enabled: true
          homepage:
            enabled: true
            group: Sonstiges
    persistence:
      odoo:
        volsync:
          - name: app-odoo
            type: restic
            credentials: storj
            src:
              enabled: true
            dest:
              enabled: true
      addons:
        volsync:
          - name: app-addons
            type: restic
            credentials: storj
            src:
              enabled: true
            dest:
              enabled: true
    resources: {}
