apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: homepage
spec:
  interval: 15m
  chart:
    spec:
      chart: homepage
      version: 11.3.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  values:
    TZ: Europe/Berlin
    ingress:
      main:
        enabled: false
        ingressClassName: internal
        hosts:
          - host: ${BASE_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          certManager:
            enabled: true
            certificateIssuer: ${CERTMANAGER_ISSUER}
          traefik:
            enabled: false
          nginx:
            enabled: true
    forceConfigFromValues: false
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                HOMEPAGE_ALLOWED_HOSTS: ${BASE_DOMAIN}
    configmap:
      config:
        data:
          settings.yaml: |
            ---
            # For configuration options and examples, please see:
            # https://gethomepage.dev/latest/configs/settings

            title: Noitl.Base
            color: stone
            layout:
              Medien:
                icon: mdi-multimedia
              Dateien:
                icon: mdi-file-multiple
              Sonstiges:
                icon: mdi-dots-hexagon
              System:
                icon: mdi-cog-outline
            headerStyle: boxedWidgets
            language: de
            showStatus: true
            statusStyle: dot

          widgets.yaml: |
            ---
            # For configuration options and examples, please see:
            # https://gethomepage.dev/latest/configs/widgets

            - resources:
                cpu: true
                memory: true
                disk: /
          services.yaml: |
            ---
            # For configuration options and examples, please see:
            # https://gethomepage.dev/latest/configs/services

            - Sonstiges:
              - Home Assistant:
                  href: https://home.noitl.space
                  icon: home-assistant
                  description: Smart Home Automatisierungs- und Analyse-Plattform
                  ping: "192.168.188.30"
          bookmarks.yaml: |
            ---
            # For configuration options and examples, please see:
            # https://gethomepage.dev/latest/configs/bookmarks

            # No bookmarks