apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: homepage
spec:
  interval: 15m
  chart:
    spec:
      chart: homepage
      version: 9.3.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  values:
    TZ: Europe/Berlin
    ingress:
      main:
        enabled: true
        hosts:
          - host: ${BASE_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          certManager:
            enabled: true
            certificateIssuer: ${CERTMANAGER_ISSUER}
          traefik:
            enabled: true
    forceConfigFromValues: true
    configmap:
      config:
        data:
          settings.yaml: |
            ---
            # For configuration options and examples, please see:
            # https://gethomepage.dev/latest/configs/settings

            title: Noitl.Base
            color: stone
            layout:
              Medien:
                icon: mdi-multimedia
              Dateien:
                icon: mdi-file-multiple
              Sonstiges:
                icon: mdi-dots-hexagon
              System:
                icon: mdi-cog-outline
            headerStyle: boxedWidgets
            language: de
            showStatus: true
            statusStyle: dot

          widgets.yaml: |
            ---
            # For configuration options and examples, please see:
            # https://gethomepage.dev/latest/configs/widgets

            - resources:
                cpu: true
                memory: true
                disk: /
          services.yaml: |
            ---
            # For configuration options and examples, please see:
            # https://gethomepage.dev/latest/configs/services

            # No services
          bookmarks.yaml: |
            ---
            # For configuration options and examples, please see:
            # https://gethomepage.dev/latest/configs/bookmarks

            # No bookmarks