apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft-proxy
  namespace: minecraft-proxy
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 14.4.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  values:
    TZ: Europe/Berlin
    image:
      repository: bahuma20/lazymc-kubernetes
      pullPolicy: IfNotPresent
      tag: latest@sha256:3d9c0697924dcaac691fdb33df0517e02145fef7ed8186784ec0d811dacb31b7
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${MINECRAFT_PROXY_IP}
        ports:
          main:
            enabled: true
            protocol: tcp
            port: 25565
          query:
            enabled: true
            protocol: udp
            port: 25565
    workload:
      main:
        podSpec:
          automountServiceAccountToken: true
          containers:
            main:
              probes:
                liveness:
                  enabled: false
                  type: tcp
                readiness:
                  enabled: false
                  type: tcp
                startup:
                  enabled: false
                  type: tcp
              env:
                RUST_LOG: trace
                RUST_BACKTRACE: 1
                APP_SERVER: minecraft-minecraft-java.minecraft.svc.cluster.local
                APP_NAMESPACE: minecraft
                APP_STATEFULSET_NAME: minecraft-minecraft-java
    persistence:
      configfiles:
        enabled: true
        type: "emptyDir"
        medium: Memory
        size: 20Mi
        targetSelector:
          main:
            main:
              mountPath: /app/config
              readOnly: false
    serviceAccount:
      main:
        enabled: true
        primary: true
    rbac:
      main:
        enabled: true
        primary: true
        clusterWide: true
        serviceAccounts:
          - main
        rules:
          - apiGroups: [ "" ]
            resources: [ "services" ]
            verbs: [ "watch","list" ]
          - apiGroups: [ "apps" ]
            resources: [ "statefulsets", "statefulsets/scale" ]
            verbs: [ "watch","list","get","update","patch" ]
    resources: { }