apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft-proxy
  namespace: minecraft-proxy
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 14.4.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  values:
    TZ: Europe/Berlin
    image:
      repository: bahuma20/lazymc-kubernetes@sha256:fc4dd0dc1897e97cc7e1934348167000f6d71bbff07f2f28d52cb4cba3e1f6bd
      pullPolicy: IfNotPresent
      tag: v0.0.4
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${MINECRAFT_PROXY_IP}
        ports:
          main:
            port: 25565
    workload:
      main:
        podSpec:
          automountServiceAccountToken: true
          containers:
            main:
              probes:
                liveness:
                  enabled: false
                  type: tcp
                readiness:
                  enabled: false
                  type: tcp
                startup:
                  enabled: false
                  type: tcp
              env:
                RUST_LOG: debug
                RUST_BACKTRACE: 1
                APP_SERVER: minecraft-minecraft-java.minecraft.svc.cluster.local
                APP_NAMESPACE: minecraft
                APP_STATEFULSET_NAME: minecraft-minecraft-java
    persistence:
      configfiles:
        enabled: true
        type: "emptyDir"
        medium: memory
        size: 20MiB
        targetSelector:
          main:
            main:
              mountPath: /app/config
              readOnly: false
    serviceAccount:
      main:
        enabled: true
        primary: true
    rbac:
      main:
        enabled: true
        primary: true
        clusterWide: true
        serviceAccounts:
          - main
        rules:
          - apiGroups: [ "" ]
            resources: [ "services" ]
            verbs: [ "watch","list" ]
          - apiGroups: [ "apps" ]
            resources: [ "statefulsets", "statefulsets/scale" ]
            verbs: [ "watch","list","get","update" ]
    resources: { }