apiVersion: v1
kind: Service
metadata:
  name: prometheus-main
  namespace: prometheus
spec:
  type: NodePort
  ports:
    - name: web
      nodePort: 30900
      port: 9090
      protocol: TCP
      targetPort: web
  selector:
    prometheus: main