---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 15m
  chart:
    spec:
      chart: traefik
      version: 30.4.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: Europe/Berlin
    defaultCertificate: ""
    service:
      lb:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: ${TRAEFIK_IP}
        externalTrafficPolicy: Local
        ports:
          web2:
            enabled: true
            port: 80
            protocol: http
            redirectTo: websecure
            # Options: Empty, 0 (ingore), or positive int
            # redirectPort:
            # -- Configure (Forwarded Headers)[https://doc.traefik.io/traefik/routing/entrypoints/#forwarded-headers] Support
            forwardedHeaders:
              enabled: false
              # -- List of trusted IP and CIDR references
              trustedIPs: []
              # -- Trust all forwarded headers
              insecureMode: false
            # -- Configure (Proxy Protocol Headers)[https://doc.traefik.io/traefik/routing/entrypoints/#proxyprotocol] Support
            proxyProtocol:
              enabled: false
              # -- Only IPs in trustedIPs will lead to remote client address replacement
              trustedIPs: []
              # -- Trust every incoming connection
              insecureMode: false
          websecure2:
            enabled: true
            port: 443
            protocol: https
            # -- Configure (Forwarded Headers)[https://doc.traefik.io/traefik/routing/entrypoints/#forwarded-headers] Support
            forwardedHeaders:
              enabled: false
              # -- List of trusted IP and CIDR references
              trustedIPs: []
              # -- Trust all forwarded headers
              insecureMode: false
            # -- Configure (Proxy Protocol Headers)[https://doc.traefik.io/traefik/routing/entrypoints/#proxyprotocol] Support
            proxyProtocol:
              enabled: false
              # -- Only IPs in trustedIPs will lead to remote client address replacement
              trustedIPs: []
              # -- Trust every incoming connection
              insecureMode: false
        #      tcpexample:
        #        enabled: true
        #        targetPort: 9443
        #        protocol: tcp
        #        tls:
        #          enabled: false
        #          # this is the name of a TLSOption definition
        #          options: ""
        #          certResolver: ""
        #          domains: []
        #          # - main: example.com
        #          #   sans:
        #          #     - foo.example.com
        #          #     - bar.example.com
      tcp:
        type: NodePort
#        loadBalancerIP: ${TRAEFIK_IP}
        ports:
          web:
            nodePort: 30080
          websecure:
            nodePort: 30443
    middlewares:
      ipWhiteList:
        - name: local
          sourceRange:
            - 192.168.188.0/24
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
          certManager:
            enabled: true
            certificateIssuer: ${CERTMANAGER_ISSUER}
          homepage:
            enabled: true
            group: System
        hosts:
          - host: traefik.${BASE_DOMAIN}
            paths:
              - path: /
                pathType: Prefix