---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 15m
  chart:
    spec:
      chart: traefik
      version: 30.4.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: Europe/Berlin
    defaultCertificate: ""
    service:
      tcp:
        type: NodePort
#        loadBalancerIP: ${TRAEFIK_IP}
        ports:
          web:
            nodePort: 80
          websecure:
            nodePort: 443
    middlewares:
      ipWhiteList:
        - name: local
          sourceRange:
            - 192.168.188.0/24
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
          certManager:
            enabled: true
            certificateIssuer: ${CERTMANAGER_ISSUER}
          homepage:
            enabled: true
            group: System
        hosts:
          - host: traefik.${BASE_DOMAIN}
            paths:
              - path: /
                pathType: Prefix