apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: traefik
    namespace: traefik
spec:
    interval: 15m
    chart:
        spec:
            chart: traefik
            version: 27.0.15
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    install:
        createNamespace: true
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        cleanupOnFail: true
        crds: CreateReplace
        remediation:
            retries: 3
    uninstall:
        keepHistory: false
    values:
        TZ: Europe/Berlin
        logs:
            access:
                enabled: false
                fields:
                    general:
                        defaultmode: keep
                    headers:
                        defaultmode: drop
                filters:
                    minduration: 10ms
                    retryattempts: true
                    statuscodes: 200,300-302
                format: common
            general:
                format: common
                level: ERROR
        defaultCertificate: ""
        service:
            main:
                type: ClusterIP
            tcp:
                loadBalancerIP: ${TRAEFIK_IP}
                externalTrafficPolicy: Local
                ports:
                    web:
                        enabled: true
                        port: 80
                        protocol: http
                        redirectTo: websecure
                    websecure:
                        enabled: true
                        port: 443
                        protocol: https
                        forwardedHeaders:
                            enabled: false
                            insecureMode: false
                        proxyProtocol:
                            enabled: false
                            insecureMode: false
        ingress:
            main:
                enabled: true
                integrations:
                    traefik:
                        enabled: true
                    certManager:
                        enabled: true
                        certificateIssuer: ${CERTMANAGER_ISSUER}
                hosts:
                    - host: traefik.${BASE_DOMAIN}
                      paths:
                        - path: /
                          pathType: Prefix