apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: filesystem-trim
  namespace: longhorn-system
spec:
  concurrency: 1
  cron: 0 23 * * *
  groups:
    - default
  name: filesystem-trim
  retain: 0
  task: filesystem-trim

---

apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: snapshot-delete
  namespace: longhorn-system
spec:
  concurrency: 1
  cron: 00 22 * * *
  groups:
    - default
  name: delete
  retain: 0
  task: snapshot-delete

---

apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: snapshot-cleanup
  namespace: longhorn-system
spec:
  concurrency: 1
  cron: 30 22 * * *
  groups:
    - default
  name: snapshot-cleanup
  retain: 0
  task: snapshot-cleanup