apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: minecraft-monitor
  namespace: minecraft
  labels:
    prometheus: main
spec:
  selector:
    matchLabels:
      release: minecraft
      service.name: main
  endpoints:
    - port: z-prometheus