apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: minecraft-server
  namespace: minecraft
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: minecraft-minecraft-java
  pollingInterval: 5 # Überprüfe alle 5 Sekunden
  cooldownPeriod: 60
  minReplicaCount: 0
  maxReplicaCount: 1
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus.prometheus.svc.cluster.local:9090
        metricName: mc_players_online_total
        query: sum(mc_players_online_total)
        threshold: '1'
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 60