apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kvb-kt
  namespace: kvb-kt
spec:
  interval: 15m
  chart:
    spec:
      chart: external-service
      version: 16.4.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  releaseName: kvb-kt
  values:
    service:
      main:
        externalIP: "192.168.188.90"
        ports:
          main:
            port: 443
            protocol: https
    ingress:
      main:
        enabled: true
        ingressClassName: external
        hosts:
          - host: kvb-kt.noitl.space
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        integrations:
          certManager:
            enabled: true
            certificateIssuer: ${CERTMANAGER_ISSUER}
          homepage:
            enabled: true
            group: Sonstige
            name: KVB Kartenterminal
            icon: mdi-smart-card-reader
            description: Remote Schnittstelle des Cherry Kartenterminals
            widget:
              enabled: false
