apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  namespace: kube-prometheus-stack
  name: volsync-out-of-sync
spec:
  groups:
    - name: ./example.rules
      rules:
        - alert: ExampleAlert
          expr: vector(1)